// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// AllergyIntoleranceParticipant represents the AllergyIntolerance.participant backbone element.
// Who or what participated in the activities related to the allergy or intolerance and how they were involved
type AllergyIntoleranceParticipant struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of involvement
	Function *CodeableConcept `json:"function,omitempty"`
	// Who or what participated in the activities related to the allergy or intolerance
	Actor Reference `json:"actor,omitempty"`
}

// AllergyIntoleranceReaction represents the AllergyIntolerance.reaction backbone element.
// Adverse Reaction Events linked to exposure to substance
type AllergyIntoleranceReaction struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Specific substance or pharmaceutical product considered to be responsible for event
	Substance *CodeableConcept `json:"substance,omitempty"`
	// Clinical symptoms/signs associated with the Event
	Manifestation []CodeableReference `json:"manifestation,omitempty"`
	// Description of the event as a whole
	Description *string `json:"description,omitempty"`
	// Date(/time) when manifestations showed
	Onset *string `json:"onset,omitempty"`
	// mild | moderate | severe (of event as a whole)
	Severity *AllergyIntoleranceSeverity `json:"severity,omitempty"`
	// How the subject was exposed to the substance
	ExposureRoute *CodeableConcept `json:"exposureRoute,omitempty"`
	// Text about event not captured in other fields
	Note []Annotation `json:"note,omitempty"`
}
