// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// AppointmentParticipant represents the Appointment.participant backbone element.
// Participants involved in appointment
type AppointmentParticipant struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Role of participant in the appointment
	Type []CodeableConcept `json:"type,omitempty"`
	// Participation period of the actor
	Period *Period `json:"period,omitempty"`
	// The individual, device, location, or service participating in the appointment
	Actor *Reference `json:"actor,omitempty"`
	// The participant is required to attend (optional when false)
	Required *bool `json:"required,omitempty"`
	// accepted | declined | tentative | needs-action
	Status *ParticipationStatus `json:"status,omitempty"`
}

// AppointmentRecurrenceTemplate represents the Appointment.recurrenceTemplate backbone element.
// Details of the recurrence pattern/template used to generate occurrences
type AppointmentRecurrenceTemplate struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// The timezone of the occurrences
	Timezone *CodeableConcept `json:"timezone,omitempty"`
	// The frequency of the recurrence
	RecurrenceType CodeableConcept `json:"recurrenceType,omitempty"`
	// The date when the recurrence should end
	LastOccurrenceDate *string `json:"lastOccurrenceDate,omitempty"`
	// The number of planned occurrences
	OccurrenceCount *uint32 `json:"occurrenceCount,omitempty"`
	// Specific dates for a recurring set of appointments (no template)
	OccurrenceDate []string `json:"occurrenceDate,omitempty"`
	// Information about weekly recurring appointments
	WeeklyTemplate *AppointmentRecurrenceTemplateWeeklyTemplate `json:"weeklyTemplate,omitempty"`
	// Information about monthly recurring appointments
	MonthlyTemplate *AppointmentRecurrenceTemplateMonthlyTemplate `json:"monthlyTemplate,omitempty"`
	// Information about yearly recurring appointments
	YearlyTemplate *AppointmentRecurrenceTemplateYearlyTemplate `json:"yearlyTemplate,omitempty"`
	// Any dates that should be excluded from the series
	ExcludingDate []string `json:"excludingDate,omitempty"`
	// Any recurrence IDs that should be excluded from the recurrence
	ExcludingRecurrenceId []uint32 `json:"excludingRecurrenceId,omitempty"`
}

// AppointmentRecurrenceTemplateMonthlyTemplate represents the Appointment.recurrenceTemplate.monthlyTemplate backbone element.
// Information about monthly recurring appointments
type AppointmentRecurrenceTemplateMonthlyTemplate struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Recurs on a specific day of the month
	DayOfMonth *uint32 `json:"dayOfMonth,omitempty"`
	// Indicates which week of the month the appointment should occur
	NthWeekOfMonth *Coding `json:"nthWeekOfMonth,omitempty"`
	// Indicates which day of the week the appointment should occur
	DayOfWeek *Coding `json:"dayOfWeek,omitempty"`
	// Recurs every nth month
	MonthInterval *uint32 `json:"monthInterval,omitempty"`
}

// AppointmentRecurrenceTemplateWeeklyTemplate represents the Appointment.recurrenceTemplate.weeklyTemplate backbone element.
// Information about weekly recurring appointments
type AppointmentRecurrenceTemplateWeeklyTemplate struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Recurs on Mondays
	Monday *bool `json:"monday,omitempty"`
	// Recurs on Tuesday
	Tuesday *bool `json:"tuesday,omitempty"`
	// Recurs on Wednesday
	Wednesday *bool `json:"wednesday,omitempty"`
	// Recurs on Thursday
	Thursday *bool `json:"thursday,omitempty"`
	// Recurs on Friday
	Friday *bool `json:"friday,omitempty"`
	// Recurs on Saturday
	Saturday *bool `json:"saturday,omitempty"`
	// Recurs on Sunday
	Sunday *bool `json:"sunday,omitempty"`
	// Recurs every nth week
	WeekInterval *uint32 `json:"weekInterval,omitempty"`
}

// AppointmentRecurrenceTemplateYearlyTemplate represents the Appointment.recurrenceTemplate.yearlyTemplate backbone element.
// Information about yearly recurring appointments
type AppointmentRecurrenceTemplateYearlyTemplate struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Recurs every nth year
	YearInterval *uint32 `json:"yearInterval,omitempty"`
}
