// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// VisionPrescriptionLensSpecification represents the VisionPrescription.lensSpecification backbone element.
// Vision lens authorization
type VisionPrescriptionLensSpecification struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Product to be supplied
	Product CodeableConcept `json:"product,omitempty"`
	// right | left
	Eye *VisionEyes `json:"eye,omitempty"`
	// Power of the lens
	Sphere *float64 `json:"sphere,omitempty"`
	// Lens power for astigmatism
	Cylinder *float64 `json:"cylinder,omitempty"`
	// Lens meridian which contain no power for astigmatism
	Axis *int `json:"axis,omitempty"`
	// Eye alignment compensation
	Prism []VisionPrescriptionLensSpecificationPrism `json:"prism,omitempty"`
	// Added power for multifocal levels
	Add *float64 `json:"add,omitempty"`
	// Contact lens power
	Power *float64 `json:"power,omitempty"`
	// Contact lens back curvature
	BackCurve *float64 `json:"backCurve,omitempty"`
	// Contact lens diameter
	Diameter *float64 `json:"diameter,omitempty"`
	// Lens wear duration
	Duration *Quantity `json:"duration,omitempty"`
	// Color required
	Color *string `json:"color,omitempty"`
	// Brand required
	Brand *string `json:"brand,omitempty"`
	// Notes for coatings
	Note []Annotation `json:"note,omitempty"`
}

// VisionPrescriptionLensSpecificationPrism represents the VisionPrescription.lensSpecification.prism backbone element.
// Eye alignment compensation
type VisionPrescriptionLensSpecificationPrism struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Amount of adjustment
	Amount *float64 `json:"amount,omitempty"`
	// up | down | in | out
	Base *VisionBase `json:"base,omitempty"`
}
