// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// NutritionIntakeConsumedItem represents the NutritionIntake.consumedItem backbone element.
// What food or fluid product or item was consumed
type NutritionIntakeConsumedItem struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// The type of food or fluid product
	Type CodeableConcept `json:"type,omitempty"`
	// Code that identifies the food or fluid product that was consumed
	NutritionProduct CodeableReference `json:"nutritionProduct,omitempty"`
	// Scheduled frequency of consumption
	Schedule *Timing `json:"schedule,omitempty"`
	// Quantity of the specified food
	Amount *Quantity `json:"amount,omitempty"`
	// Rate at which enteral feeding was administered
	Rate *Quantity `json:"rate,omitempty"`
	// Flag to indicate if the food or fluid item was refused or otherwise not consumed
	NotConsumed *bool `json:"notConsumed,omitempty"`
	// Reason food or fluid was not consumed
	NotConsumedReason *CodeableConcept `json:"notConsumedReason,omitempty"`
}

// NutritionIntakeIngredientLabel represents the NutritionIntake.ingredientLabel backbone element.
// Total nutrient for the whole meal, product, serving
type NutritionIntakeIngredientLabel struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Total nutrient consumed
	Nutrient CodeableReference `json:"nutrient,omitempty"`
	// Total amount of nutrient consumed
	Amount Quantity `json:"amount,omitempty"`
}

// NutritionIntakePerformer represents the NutritionIntake.performer backbone element.
// Who was performed in the intake
type NutritionIntakePerformer struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of performer
	Function *CodeableConcept `json:"function,omitempty"`
	// Who performed the intake
	Actor Reference `json:"actor,omitempty"`
}
