// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// CoverageClass represents the Coverage.class backbone element.
// Additional coverage classifications
type CoverageClass struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of class such as 'group' or 'plan'
	Type CodeableConcept `json:"type,omitempty"`
	// Value associated with the type
	Value Identifier `json:"value,omitempty"`
	// Human readable description of the type and value
	Name *string `json:"name,omitempty"`
}

// CoverageCostToBeneficiary represents the Coverage.costToBeneficiary backbone element.
// Patient payments for services/products
type CoverageCostToBeneficiary struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Cost category
	Type *CodeableConcept `json:"type,omitempty"`
	// Benefit classification
	Category *CodeableConcept `json:"category,omitempty"`
	// In or out of network
	Network *CodeableConcept `json:"network,omitempty"`
	// Individual or family
	Unit *CodeableConcept `json:"unit,omitempty"`
	// Annual or lifetime
	Term *CodeableConcept `json:"term,omitempty"`
	// The amount or percentage due from the beneficiary
	ValueQuantity *Quantity `json:"valueQuantity,omitempty"`
	// The amount or percentage due from the beneficiary
	ValueMoney *Money `json:"valueMoney,omitempty"`
	// Exceptions for patient payments
	Exception []CoverageCostToBeneficiaryException `json:"exception,omitempty"`
}

// CoverageCostToBeneficiaryException represents the Coverage.costToBeneficiary.exception backbone element.
// Exceptions for patient payments
type CoverageCostToBeneficiaryException struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Exception category
	Type CodeableConcept `json:"type,omitempty"`
	// The effective period of the exception
	Period *Period `json:"period,omitempty"`
}

// CoveragePaymentBy represents the Coverage.paymentBy backbone element.
// Self-pay parties and responsibility
type CoveragePaymentBy struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Parties performing self-payment
	Party Reference `json:"party,omitempty"`
	// Party's responsibility
	Responsibility *string `json:"responsibility,omitempty"`
}
