// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r5

package r5

// ImmunizationRecommendationRecommendation represents the ImmunizationRecommendation.recommendation backbone element.
// Vaccine administration recommendations
type ImmunizationRecommendationRecommendation struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Vaccine  or vaccine group recommendation applies to
	VaccineCode []CodeableConcept `json:"vaccineCode,omitempty"`
	// Disease to be immunized against
	TargetDisease []CodeableConcept `json:"targetDisease,omitempty"`
	// Vaccine which is contraindicated to fulfill the recommendation
	ContraindicatedVaccineCode []CodeableConcept `json:"contraindicatedVaccineCode,omitempty"`
	// Vaccine recommendation status
	ForecastStatus CodeableConcept `json:"forecastStatus,omitempty"`
	// Vaccine administration status reason
	ForecastReason []CodeableConcept `json:"forecastReason,omitempty"`
	// Dates governing proposed immunization
	DateCriterion []ImmunizationRecommendationRecommendationDateCriterion `json:"dateCriterion,omitempty"`
	// Protocol details
	Description *string `json:"description,omitempty"`
	// Name of vaccination series
	Series *string `json:"series,omitempty"`
	// Recommended dose number within series
	DoseNumber *string `json:"doseNumber,omitempty"`
	// Recommended number of doses for immunity
	SeriesDoses *string `json:"seriesDoses,omitempty"`
	// Past immunizations supporting recommendation
	SupportingImmunization []Reference `json:"supportingImmunization,omitempty"`
	// Patient observations supporting recommendation
	SupportingPatientInformation []Reference `json:"supportingPatientInformation,omitempty"`
}

// ImmunizationRecommendationRecommendationDateCriterion represents the ImmunizationRecommendation.recommendation.dateCriterion backbone element.
// Dates governing proposed immunization
type ImmunizationRecommendationRecommendationDateCriterion struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Type of date
	Code CodeableConcept `json:"code,omitempty"`
	// Recommended date
	Value *string `json:"value,omitempty"`
}
