// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// SubstanceSourceMaterial - Fluent Builder
// =============================================================================

// SubstanceSourceMaterialBuilder provides a fluent API for constructing SubstanceSourceMaterial resources.
type SubstanceSourceMaterialBuilder struct {
	substanceSourceMaterial *SubstanceSourceMaterial
}

// NewSubstanceSourceMaterialBuilder creates a new SubstanceSourceMaterialBuilder.
func NewSubstanceSourceMaterialBuilder() *SubstanceSourceMaterialBuilder {
	return &SubstanceSourceMaterialBuilder{
		substanceSourceMaterial: &SubstanceSourceMaterial{},
	}
}

// Build returns the constructed SubstanceSourceMaterial resource.
func (b *SubstanceSourceMaterialBuilder) Build() *SubstanceSourceMaterial {
	return b.substanceSourceMaterial
}

// SetId sets the Id field.
func (b *SubstanceSourceMaterialBuilder) SetId(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *SubstanceSourceMaterialBuilder) SetMeta(v Meta) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *SubstanceSourceMaterialBuilder) SetImplicitRules(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *SubstanceSourceMaterialBuilder) SetLanguage(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Language = &v
	return b
}

// SetText sets the Text field.
func (b *SubstanceSourceMaterialBuilder) SetText(v Narrative) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *SubstanceSourceMaterialBuilder) AddContained(v Resource) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Contained = append(b.substanceSourceMaterial.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *SubstanceSourceMaterialBuilder) AddExtension(v Extension) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Extension = append(b.substanceSourceMaterial.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SubstanceSourceMaterialBuilder) AddModifierExtension(v Extension) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.ModifierExtension = append(b.substanceSourceMaterial.ModifierExtension, v)
	return b
}

// SetSourceMaterialClass sets the SourceMaterialClass field.
func (b *SubstanceSourceMaterialBuilder) SetSourceMaterialClass(v CodeableConcept) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.SourceMaterialClass = &v
	return b
}

// SetSourceMaterialType sets the SourceMaterialType field.
func (b *SubstanceSourceMaterialBuilder) SetSourceMaterialType(v CodeableConcept) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.SourceMaterialType = &v
	return b
}

// SetSourceMaterialState sets the SourceMaterialState field.
func (b *SubstanceSourceMaterialBuilder) SetSourceMaterialState(v CodeableConcept) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.SourceMaterialState = &v
	return b
}

// SetOrganismId sets the OrganismId field.
func (b *SubstanceSourceMaterialBuilder) SetOrganismId(v Identifier) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.OrganismId = &v
	return b
}

// SetOrganismName sets the OrganismName field.
func (b *SubstanceSourceMaterialBuilder) SetOrganismName(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.OrganismName = &v
	return b
}

// AddParentSubstanceId adds a ParentSubstanceId element.
func (b *SubstanceSourceMaterialBuilder) AddParentSubstanceId(v Identifier) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.ParentSubstanceId = append(b.substanceSourceMaterial.ParentSubstanceId, v)
	return b
}

// AddParentSubstanceName adds a ParentSubstanceName element.
func (b *SubstanceSourceMaterialBuilder) AddParentSubstanceName(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.ParentSubstanceName = append(b.substanceSourceMaterial.ParentSubstanceName, v)
	return b
}

// AddCountryOfOrigin adds a CountryOfOrigin element.
func (b *SubstanceSourceMaterialBuilder) AddCountryOfOrigin(v CodeableConcept) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.CountryOfOrigin = append(b.substanceSourceMaterial.CountryOfOrigin, v)
	return b
}

// AddGeographicalLocation adds a GeographicalLocation element.
func (b *SubstanceSourceMaterialBuilder) AddGeographicalLocation(v string) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.GeographicalLocation = append(b.substanceSourceMaterial.GeographicalLocation, v)
	return b
}

// SetDevelopmentStage sets the DevelopmentStage field.
func (b *SubstanceSourceMaterialBuilder) SetDevelopmentStage(v CodeableConcept) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.DevelopmentStage = &v
	return b
}

// AddFractionDescription adds a FractionDescription element.
func (b *SubstanceSourceMaterialBuilder) AddFractionDescription(v SubstanceSourceMaterialFractionDescription) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.FractionDescription = append(b.substanceSourceMaterial.FractionDescription, v)
	return b
}

// SetOrganism sets the Organism field.
func (b *SubstanceSourceMaterialBuilder) SetOrganism(v SubstanceSourceMaterialOrganism) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.Organism = &v
	return b
}

// AddPartDescription adds a PartDescription element.
func (b *SubstanceSourceMaterialBuilder) AddPartDescription(v SubstanceSourceMaterialPartDescription) *SubstanceSourceMaterialBuilder {
	b.substanceSourceMaterial.PartDescription = append(b.substanceSourceMaterial.PartDescription, v)
	return b
}
