// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// SpecimenDefinition - Fluent Builder
// =============================================================================

// SpecimenDefinitionBuilder provides a fluent API for constructing SpecimenDefinition resources.
type SpecimenDefinitionBuilder struct {
	specimenDefinition *SpecimenDefinition
}

// NewSpecimenDefinitionBuilder creates a new SpecimenDefinitionBuilder.
func NewSpecimenDefinitionBuilder() *SpecimenDefinitionBuilder {
	return &SpecimenDefinitionBuilder{
		specimenDefinition: &SpecimenDefinition{},
	}
}

// Build returns the constructed SpecimenDefinition resource.
func (b *SpecimenDefinitionBuilder) Build() *SpecimenDefinition {
	return b.specimenDefinition
}

// SetId sets the Id field.
func (b *SpecimenDefinitionBuilder) SetId(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *SpecimenDefinitionBuilder) SetMeta(v Meta) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *SpecimenDefinitionBuilder) SetImplicitRules(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *SpecimenDefinitionBuilder) SetLanguage(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *SpecimenDefinitionBuilder) SetText(v Narrative) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *SpecimenDefinitionBuilder) AddContained(v Resource) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Contained = append(b.specimenDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *SpecimenDefinitionBuilder) AddExtension(v Extension) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Extension = append(b.specimenDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SpecimenDefinitionBuilder) AddModifierExtension(v Extension) *SpecimenDefinitionBuilder {
	b.specimenDefinition.ModifierExtension = append(b.specimenDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *SpecimenDefinitionBuilder) SetUrl(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Url = &v
	return b
}

// SetIdentifier sets the Identifier field.
func (b *SpecimenDefinitionBuilder) SetIdentifier(v Identifier) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Identifier = &v
	return b
}

// SetVersion sets the Version field.
func (b *SpecimenDefinitionBuilder) SetVersion(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *SpecimenDefinitionBuilder) SetVersionAlgorithmString(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *SpecimenDefinitionBuilder) SetVersionAlgorithmStringExt(v Element) *SpecimenDefinitionBuilder {
	b.specimenDefinition.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *SpecimenDefinitionBuilder) SetVersionAlgorithmCoding(v Coding) *SpecimenDefinitionBuilder {
	b.specimenDefinition.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *SpecimenDefinitionBuilder) SetName(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *SpecimenDefinitionBuilder) SetTitle(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Title = &v
	return b
}

// AddDerivedFromCanonical adds a DerivedFromCanonical element.
func (b *SpecimenDefinitionBuilder) AddDerivedFromCanonical(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.DerivedFromCanonical = append(b.specimenDefinition.DerivedFromCanonical, v)
	return b
}

// AddDerivedFromUri adds a DerivedFromUri element.
func (b *SpecimenDefinitionBuilder) AddDerivedFromUri(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.DerivedFromUri = append(b.specimenDefinition.DerivedFromUri, v)
	return b
}

// SetStatus sets the Status field.
func (b *SpecimenDefinitionBuilder) SetStatus(v PublicationStatus) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *SpecimenDefinitionBuilder) SetExperimental(v bool) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Experimental = &v
	return b
}

// SetSubjectCodeableConcept sets the SubjectCodeableConcept field.
func (b *SpecimenDefinitionBuilder) SetSubjectCodeableConcept(v CodeableConcept) *SpecimenDefinitionBuilder {
	b.specimenDefinition.SubjectCodeableConcept = &v
	return b
}

// SetSubjectReference sets the SubjectReference field.
func (b *SpecimenDefinitionBuilder) SetSubjectReference(v Reference) *SpecimenDefinitionBuilder {
	b.specimenDefinition.SubjectReference = &v
	return b
}

// SetDate sets the Date field.
func (b *SpecimenDefinitionBuilder) SetDate(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *SpecimenDefinitionBuilder) SetPublisher(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *SpecimenDefinitionBuilder) AddContact(v ContactDetail) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Contact = append(b.specimenDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *SpecimenDefinitionBuilder) SetDescription(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *SpecimenDefinitionBuilder) AddUseContext(v UsageContext) *SpecimenDefinitionBuilder {
	b.specimenDefinition.UseContext = append(b.specimenDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *SpecimenDefinitionBuilder) AddJurisdiction(v CodeableConcept) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Jurisdiction = append(b.specimenDefinition.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *SpecimenDefinitionBuilder) SetPurpose(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *SpecimenDefinitionBuilder) SetCopyright(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *SpecimenDefinitionBuilder) SetCopyrightLabel(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.CopyrightLabel = &v
	return b
}

// SetApprovalDate sets the ApprovalDate field.
func (b *SpecimenDefinitionBuilder) SetApprovalDate(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.ApprovalDate = &v
	return b
}

// SetLastReviewDate sets the LastReviewDate field.
func (b *SpecimenDefinitionBuilder) SetLastReviewDate(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.LastReviewDate = &v
	return b
}

// SetEffectivePeriod sets the EffectivePeriod field.
func (b *SpecimenDefinitionBuilder) SetEffectivePeriod(v Period) *SpecimenDefinitionBuilder {
	b.specimenDefinition.EffectivePeriod = &v
	return b
}

// SetTypeCollected sets the TypeCollected field.
func (b *SpecimenDefinitionBuilder) SetTypeCollected(v CodeableConcept) *SpecimenDefinitionBuilder {
	b.specimenDefinition.TypeCollected = &v
	return b
}

// AddPatientPreparation adds a PatientPreparation element.
func (b *SpecimenDefinitionBuilder) AddPatientPreparation(v CodeableConcept) *SpecimenDefinitionBuilder {
	b.specimenDefinition.PatientPreparation = append(b.specimenDefinition.PatientPreparation, v)
	return b
}

// SetTimeAspect sets the TimeAspect field.
func (b *SpecimenDefinitionBuilder) SetTimeAspect(v string) *SpecimenDefinitionBuilder {
	b.specimenDefinition.TimeAspect = &v
	return b
}

// AddCollection adds a Collection element.
func (b *SpecimenDefinitionBuilder) AddCollection(v CodeableConcept) *SpecimenDefinitionBuilder {
	b.specimenDefinition.Collection = append(b.specimenDefinition.Collection, v)
	return b
}

// AddTypeTested adds a TypeTested element.
func (b *SpecimenDefinitionBuilder) AddTypeTested(v SpecimenDefinitionTypeTested) *SpecimenDefinitionBuilder {
	b.specimenDefinition.TypeTested = append(b.specimenDefinition.TypeTested, v)
	return b
}
