// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// Measure - Fluent Builder
// =============================================================================

// MeasureBuilder provides a fluent API for constructing Measure resources.
type MeasureBuilder struct {
	measure *Measure
}

// NewMeasureBuilder creates a new MeasureBuilder.
func NewMeasureBuilder() *MeasureBuilder {
	return &MeasureBuilder{
		measure: &Measure{},
	}
}

// Build returns the constructed Measure resource.
func (b *MeasureBuilder) Build() *Measure {
	return b.measure
}

// SetId sets the Id field.
func (b *MeasureBuilder) SetId(v string) *MeasureBuilder {
	b.measure.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *MeasureBuilder) SetMeta(v Meta) *MeasureBuilder {
	b.measure.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *MeasureBuilder) SetImplicitRules(v string) *MeasureBuilder {
	b.measure.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *MeasureBuilder) SetLanguage(v string) *MeasureBuilder {
	b.measure.Language = &v
	return b
}

// SetText sets the Text field.
func (b *MeasureBuilder) SetText(v Narrative) *MeasureBuilder {
	b.measure.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *MeasureBuilder) AddContained(v Resource) *MeasureBuilder {
	b.measure.Contained = append(b.measure.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *MeasureBuilder) AddExtension(v Extension) *MeasureBuilder {
	b.measure.Extension = append(b.measure.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *MeasureBuilder) AddModifierExtension(v Extension) *MeasureBuilder {
	b.measure.ModifierExtension = append(b.measure.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *MeasureBuilder) SetUrl(v string) *MeasureBuilder {
	b.measure.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *MeasureBuilder) AddIdentifier(v Identifier) *MeasureBuilder {
	b.measure.Identifier = append(b.measure.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *MeasureBuilder) SetVersion(v string) *MeasureBuilder {
	b.measure.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *MeasureBuilder) SetVersionAlgorithmString(v string) *MeasureBuilder {
	b.measure.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *MeasureBuilder) SetVersionAlgorithmStringExt(v Element) *MeasureBuilder {
	b.measure.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *MeasureBuilder) SetVersionAlgorithmCoding(v Coding) *MeasureBuilder {
	b.measure.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *MeasureBuilder) SetName(v string) *MeasureBuilder {
	b.measure.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *MeasureBuilder) SetTitle(v string) *MeasureBuilder {
	b.measure.Title = &v
	return b
}

// SetSubtitle sets the Subtitle field.
func (b *MeasureBuilder) SetSubtitle(v string) *MeasureBuilder {
	b.measure.Subtitle = &v
	return b
}

// SetStatus sets the Status field.
func (b *MeasureBuilder) SetStatus(v PublicationStatus) *MeasureBuilder {
	b.measure.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *MeasureBuilder) SetExperimental(v bool) *MeasureBuilder {
	b.measure.Experimental = &v
	return b
}

// SetSubjectCodeableConcept sets the SubjectCodeableConcept field.
func (b *MeasureBuilder) SetSubjectCodeableConcept(v CodeableConcept) *MeasureBuilder {
	b.measure.SubjectCodeableConcept = &v
	return b
}

// SetSubjectReference sets the SubjectReference field.
func (b *MeasureBuilder) SetSubjectReference(v Reference) *MeasureBuilder {
	b.measure.SubjectReference = &v
	return b
}

// SetBasis sets the Basis field.
func (b *MeasureBuilder) SetBasis(v string) *MeasureBuilder {
	b.measure.Basis = &v
	return b
}

// SetDate sets the Date field.
func (b *MeasureBuilder) SetDate(v string) *MeasureBuilder {
	b.measure.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *MeasureBuilder) SetPublisher(v string) *MeasureBuilder {
	b.measure.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *MeasureBuilder) AddContact(v ContactDetail) *MeasureBuilder {
	b.measure.Contact = append(b.measure.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *MeasureBuilder) SetDescription(v string) *MeasureBuilder {
	b.measure.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *MeasureBuilder) AddUseContext(v UsageContext) *MeasureBuilder {
	b.measure.UseContext = append(b.measure.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *MeasureBuilder) AddJurisdiction(v CodeableConcept) *MeasureBuilder {
	b.measure.Jurisdiction = append(b.measure.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *MeasureBuilder) SetPurpose(v string) *MeasureBuilder {
	b.measure.Purpose = &v
	return b
}

// SetUsage sets the Usage field.
func (b *MeasureBuilder) SetUsage(v string) *MeasureBuilder {
	b.measure.Usage = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *MeasureBuilder) SetCopyright(v string) *MeasureBuilder {
	b.measure.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *MeasureBuilder) SetCopyrightLabel(v string) *MeasureBuilder {
	b.measure.CopyrightLabel = &v
	return b
}

// SetApprovalDate sets the ApprovalDate field.
func (b *MeasureBuilder) SetApprovalDate(v string) *MeasureBuilder {
	b.measure.ApprovalDate = &v
	return b
}

// SetLastReviewDate sets the LastReviewDate field.
func (b *MeasureBuilder) SetLastReviewDate(v string) *MeasureBuilder {
	b.measure.LastReviewDate = &v
	return b
}

// SetEffectivePeriod sets the EffectivePeriod field.
func (b *MeasureBuilder) SetEffectivePeriod(v Period) *MeasureBuilder {
	b.measure.EffectivePeriod = &v
	return b
}

// AddTopic adds a Topic element.
func (b *MeasureBuilder) AddTopic(v CodeableConcept) *MeasureBuilder {
	b.measure.Topic = append(b.measure.Topic, v)
	return b
}

// AddAuthor adds a Author element.
func (b *MeasureBuilder) AddAuthor(v ContactDetail) *MeasureBuilder {
	b.measure.Author = append(b.measure.Author, v)
	return b
}

// AddEditor adds a Editor element.
func (b *MeasureBuilder) AddEditor(v ContactDetail) *MeasureBuilder {
	b.measure.Editor = append(b.measure.Editor, v)
	return b
}

// AddReviewer adds a Reviewer element.
func (b *MeasureBuilder) AddReviewer(v ContactDetail) *MeasureBuilder {
	b.measure.Reviewer = append(b.measure.Reviewer, v)
	return b
}

// AddEndorser adds a Endorser element.
func (b *MeasureBuilder) AddEndorser(v ContactDetail) *MeasureBuilder {
	b.measure.Endorser = append(b.measure.Endorser, v)
	return b
}

// AddRelatedArtifact adds a RelatedArtifact element.
func (b *MeasureBuilder) AddRelatedArtifact(v RelatedArtifact) *MeasureBuilder {
	b.measure.RelatedArtifact = append(b.measure.RelatedArtifact, v)
	return b
}

// AddLibrary adds a Library element.
func (b *MeasureBuilder) AddLibrary(v string) *MeasureBuilder {
	b.measure.Library = append(b.measure.Library, v)
	return b
}

// SetDisclaimer sets the Disclaimer field.
func (b *MeasureBuilder) SetDisclaimer(v string) *MeasureBuilder {
	b.measure.Disclaimer = &v
	return b
}

// SetScoring sets the Scoring field.
func (b *MeasureBuilder) SetScoring(v CodeableConcept) *MeasureBuilder {
	b.measure.Scoring = &v
	return b
}

// SetScoringUnit sets the ScoringUnit field.
func (b *MeasureBuilder) SetScoringUnit(v CodeableConcept) *MeasureBuilder {
	b.measure.ScoringUnit = &v
	return b
}

// SetCompositeScoring sets the CompositeScoring field.
func (b *MeasureBuilder) SetCompositeScoring(v CodeableConcept) *MeasureBuilder {
	b.measure.CompositeScoring = &v
	return b
}

// AddType adds a Type element.
func (b *MeasureBuilder) AddType(v CodeableConcept) *MeasureBuilder {
	b.measure.Type = append(b.measure.Type, v)
	return b
}

// SetRiskAdjustment sets the RiskAdjustment field.
func (b *MeasureBuilder) SetRiskAdjustment(v string) *MeasureBuilder {
	b.measure.RiskAdjustment = &v
	return b
}

// SetRateAggregation sets the RateAggregation field.
func (b *MeasureBuilder) SetRateAggregation(v string) *MeasureBuilder {
	b.measure.RateAggregation = &v
	return b
}

// SetRationale sets the Rationale field.
func (b *MeasureBuilder) SetRationale(v string) *MeasureBuilder {
	b.measure.Rationale = &v
	return b
}

// SetClinicalRecommendationStatement sets the ClinicalRecommendationStatement field.
func (b *MeasureBuilder) SetClinicalRecommendationStatement(v string) *MeasureBuilder {
	b.measure.ClinicalRecommendationStatement = &v
	return b
}

// SetImprovementNotation sets the ImprovementNotation field.
func (b *MeasureBuilder) SetImprovementNotation(v CodeableConcept) *MeasureBuilder {
	b.measure.ImprovementNotation = &v
	return b
}

// AddTerm adds a Term element.
func (b *MeasureBuilder) AddTerm(v MeasureTerm) *MeasureBuilder {
	b.measure.Term = append(b.measure.Term, v)
	return b
}

// SetGuidance sets the Guidance field.
func (b *MeasureBuilder) SetGuidance(v string) *MeasureBuilder {
	b.measure.Guidance = &v
	return b
}

// AddGroup adds a Group element.
func (b *MeasureBuilder) AddGroup(v MeasureGroup) *MeasureBuilder {
	b.measure.Group = append(b.measure.Group, v)
	return b
}

// AddSupplementalData adds a SupplementalData element.
func (b *MeasureBuilder) AddSupplementalData(v MeasureSupplementalData) *MeasureBuilder {
	b.measure.SupplementalData = append(b.measure.SupplementalData, v)
	return b
}
