// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// ImagingSelection - Fluent Builder
// =============================================================================

// ImagingSelectionBuilder provides a fluent API for constructing ImagingSelection resources.
type ImagingSelectionBuilder struct {
	imagingSelection *ImagingSelection
}

// NewImagingSelectionBuilder creates a new ImagingSelectionBuilder.
func NewImagingSelectionBuilder() *ImagingSelectionBuilder {
	return &ImagingSelectionBuilder{
		imagingSelection: &ImagingSelection{},
	}
}

// Build returns the constructed ImagingSelection resource.
func (b *ImagingSelectionBuilder) Build() *ImagingSelection {
	return b.imagingSelection
}

// SetId sets the Id field.
func (b *ImagingSelectionBuilder) SetId(v string) *ImagingSelectionBuilder {
	b.imagingSelection.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *ImagingSelectionBuilder) SetMeta(v Meta) *ImagingSelectionBuilder {
	b.imagingSelection.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *ImagingSelectionBuilder) SetImplicitRules(v string) *ImagingSelectionBuilder {
	b.imagingSelection.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *ImagingSelectionBuilder) SetLanguage(v string) *ImagingSelectionBuilder {
	b.imagingSelection.Language = &v
	return b
}

// SetText sets the Text field.
func (b *ImagingSelectionBuilder) SetText(v Narrative) *ImagingSelectionBuilder {
	b.imagingSelection.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *ImagingSelectionBuilder) AddContained(v Resource) *ImagingSelectionBuilder {
	b.imagingSelection.Contained = append(b.imagingSelection.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *ImagingSelectionBuilder) AddExtension(v Extension) *ImagingSelectionBuilder {
	b.imagingSelection.Extension = append(b.imagingSelection.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *ImagingSelectionBuilder) AddModifierExtension(v Extension) *ImagingSelectionBuilder {
	b.imagingSelection.ModifierExtension = append(b.imagingSelection.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *ImagingSelectionBuilder) AddIdentifier(v Identifier) *ImagingSelectionBuilder {
	b.imagingSelection.Identifier = append(b.imagingSelection.Identifier, v)
	return b
}

// SetStatus sets the Status field.
func (b *ImagingSelectionBuilder) SetStatus(v ImagingSelectionStatus) *ImagingSelectionBuilder {
	b.imagingSelection.Status = &v
	return b
}

// SetSubject sets the Subject field.
func (b *ImagingSelectionBuilder) SetSubject(v Reference) *ImagingSelectionBuilder {
	b.imagingSelection.Subject = &v
	return b
}

// SetIssued sets the Issued field.
func (b *ImagingSelectionBuilder) SetIssued(v string) *ImagingSelectionBuilder {
	b.imagingSelection.Issued = &v
	return b
}

// AddPerformer adds a Performer element.
func (b *ImagingSelectionBuilder) AddPerformer(v ImagingSelectionPerformer) *ImagingSelectionBuilder {
	b.imagingSelection.Performer = append(b.imagingSelection.Performer, v)
	return b
}

// AddBasedOn adds a BasedOn element.
func (b *ImagingSelectionBuilder) AddBasedOn(v Reference) *ImagingSelectionBuilder {
	b.imagingSelection.BasedOn = append(b.imagingSelection.BasedOn, v)
	return b
}

// AddCategory adds a Category element.
func (b *ImagingSelectionBuilder) AddCategory(v CodeableConcept) *ImagingSelectionBuilder {
	b.imagingSelection.Category = append(b.imagingSelection.Category, v)
	return b
}

// SetCode sets the Code field.
func (b *ImagingSelectionBuilder) SetCode(v CodeableConcept) *ImagingSelectionBuilder {
	b.imagingSelection.Code = v
	return b
}

// SetStudyUid sets the StudyUid field.
func (b *ImagingSelectionBuilder) SetStudyUid(v string) *ImagingSelectionBuilder {
	b.imagingSelection.StudyUid = &v
	return b
}

// AddDerivedFrom adds a DerivedFrom element.
func (b *ImagingSelectionBuilder) AddDerivedFrom(v Reference) *ImagingSelectionBuilder {
	b.imagingSelection.DerivedFrom = append(b.imagingSelection.DerivedFrom, v)
	return b
}

// AddEndpoint adds a Endpoint element.
func (b *ImagingSelectionBuilder) AddEndpoint(v Reference) *ImagingSelectionBuilder {
	b.imagingSelection.Endpoint = append(b.imagingSelection.Endpoint, v)
	return b
}

// SetSeriesUid sets the SeriesUid field.
func (b *ImagingSelectionBuilder) SetSeriesUid(v string) *ImagingSelectionBuilder {
	b.imagingSelection.SeriesUid = &v
	return b
}

// SetSeriesNumber sets the SeriesNumber field.
func (b *ImagingSelectionBuilder) SetSeriesNumber(v uint32) *ImagingSelectionBuilder {
	b.imagingSelection.SeriesNumber = &v
	return b
}

// SetFrameOfReferenceUid sets the FrameOfReferenceUid field.
func (b *ImagingSelectionBuilder) SetFrameOfReferenceUid(v string) *ImagingSelectionBuilder {
	b.imagingSelection.FrameOfReferenceUid = &v
	return b
}

// SetBodySite sets the BodySite field.
func (b *ImagingSelectionBuilder) SetBodySite(v CodeableReference) *ImagingSelectionBuilder {
	b.imagingSelection.BodySite = &v
	return b
}

// AddFocus adds a Focus element.
func (b *ImagingSelectionBuilder) AddFocus(v Reference) *ImagingSelectionBuilder {
	b.imagingSelection.Focus = append(b.imagingSelection.Focus, v)
	return b
}

// AddInstance adds a Instance element.
func (b *ImagingSelectionBuilder) AddInstance(v ImagingSelectionInstance) *ImagingSelectionBuilder {
	b.imagingSelection.Instance = append(b.imagingSelection.Instance, v)
	return b
}
