// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// GraphDefinition - Fluent Builder
// =============================================================================

// GraphDefinitionBuilder provides a fluent API for constructing GraphDefinition resources.
type GraphDefinitionBuilder struct {
	graphDefinition *GraphDefinition
}

// NewGraphDefinitionBuilder creates a new GraphDefinitionBuilder.
func NewGraphDefinitionBuilder() *GraphDefinitionBuilder {
	return &GraphDefinitionBuilder{
		graphDefinition: &GraphDefinition{},
	}
}

// Build returns the constructed GraphDefinition resource.
func (b *GraphDefinitionBuilder) Build() *GraphDefinition {
	return b.graphDefinition
}

// SetId sets the Id field.
func (b *GraphDefinitionBuilder) SetId(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *GraphDefinitionBuilder) SetMeta(v Meta) *GraphDefinitionBuilder {
	b.graphDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *GraphDefinitionBuilder) SetImplicitRules(v string) *GraphDefinitionBuilder {
	b.graphDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *GraphDefinitionBuilder) SetLanguage(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *GraphDefinitionBuilder) SetText(v Narrative) *GraphDefinitionBuilder {
	b.graphDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *GraphDefinitionBuilder) AddContained(v Resource) *GraphDefinitionBuilder {
	b.graphDefinition.Contained = append(b.graphDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *GraphDefinitionBuilder) AddExtension(v Extension) *GraphDefinitionBuilder {
	b.graphDefinition.Extension = append(b.graphDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *GraphDefinitionBuilder) AddModifierExtension(v Extension) *GraphDefinitionBuilder {
	b.graphDefinition.ModifierExtension = append(b.graphDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *GraphDefinitionBuilder) SetUrl(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *GraphDefinitionBuilder) AddIdentifier(v Identifier) *GraphDefinitionBuilder {
	b.graphDefinition.Identifier = append(b.graphDefinition.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *GraphDefinitionBuilder) SetVersion(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *GraphDefinitionBuilder) SetVersionAlgorithmString(v string) *GraphDefinitionBuilder {
	b.graphDefinition.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *GraphDefinitionBuilder) SetVersionAlgorithmStringExt(v Element) *GraphDefinitionBuilder {
	b.graphDefinition.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *GraphDefinitionBuilder) SetVersionAlgorithmCoding(v Coding) *GraphDefinitionBuilder {
	b.graphDefinition.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *GraphDefinitionBuilder) SetName(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *GraphDefinitionBuilder) SetTitle(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Title = &v
	return b
}

// SetStatus sets the Status field.
func (b *GraphDefinitionBuilder) SetStatus(v PublicationStatus) *GraphDefinitionBuilder {
	b.graphDefinition.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *GraphDefinitionBuilder) SetExperimental(v bool) *GraphDefinitionBuilder {
	b.graphDefinition.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *GraphDefinitionBuilder) SetDate(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *GraphDefinitionBuilder) SetPublisher(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *GraphDefinitionBuilder) AddContact(v ContactDetail) *GraphDefinitionBuilder {
	b.graphDefinition.Contact = append(b.graphDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *GraphDefinitionBuilder) SetDescription(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *GraphDefinitionBuilder) AddUseContext(v UsageContext) *GraphDefinitionBuilder {
	b.graphDefinition.UseContext = append(b.graphDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *GraphDefinitionBuilder) AddJurisdiction(v CodeableConcept) *GraphDefinitionBuilder {
	b.graphDefinition.Jurisdiction = append(b.graphDefinition.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *GraphDefinitionBuilder) SetPurpose(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *GraphDefinitionBuilder) SetCopyright(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *GraphDefinitionBuilder) SetCopyrightLabel(v string) *GraphDefinitionBuilder {
	b.graphDefinition.CopyrightLabel = &v
	return b
}

// SetStart sets the Start field.
func (b *GraphDefinitionBuilder) SetStart(v string) *GraphDefinitionBuilder {
	b.graphDefinition.Start = &v
	return b
}

// AddNode adds a Node element.
func (b *GraphDefinitionBuilder) AddNode(v GraphDefinitionNode) *GraphDefinitionBuilder {
	b.graphDefinition.Node = append(b.graphDefinition.Node, v)
	return b
}

// AddLink adds a Link element.
func (b *GraphDefinitionBuilder) AddLink(v GraphDefinitionLink) *GraphDefinitionBuilder {
	b.graphDefinition.Link = append(b.graphDefinition.Link, v)
	return b
}
