// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// StructureMap - Fluent Builder
// =============================================================================

// StructureMapBuilder provides a fluent API for constructing StructureMap resources.
type StructureMapBuilder struct {
	structureMap *StructureMap
}

// NewStructureMapBuilder creates a new StructureMapBuilder.
func NewStructureMapBuilder() *StructureMapBuilder {
	return &StructureMapBuilder{
		structureMap: &StructureMap{},
	}
}

// Build returns the constructed StructureMap resource.
func (b *StructureMapBuilder) Build() *StructureMap {
	return b.structureMap
}

// SetId sets the Id field.
func (b *StructureMapBuilder) SetId(v string) *StructureMapBuilder {
	b.structureMap.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *StructureMapBuilder) SetMeta(v Meta) *StructureMapBuilder {
	b.structureMap.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *StructureMapBuilder) SetImplicitRules(v string) *StructureMapBuilder {
	b.structureMap.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *StructureMapBuilder) SetLanguage(v string) *StructureMapBuilder {
	b.structureMap.Language = &v
	return b
}

// SetText sets the Text field.
func (b *StructureMapBuilder) SetText(v Narrative) *StructureMapBuilder {
	b.structureMap.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *StructureMapBuilder) AddContained(v Resource) *StructureMapBuilder {
	b.structureMap.Contained = append(b.structureMap.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *StructureMapBuilder) AddExtension(v Extension) *StructureMapBuilder {
	b.structureMap.Extension = append(b.structureMap.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *StructureMapBuilder) AddModifierExtension(v Extension) *StructureMapBuilder {
	b.structureMap.ModifierExtension = append(b.structureMap.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *StructureMapBuilder) SetUrl(v string) *StructureMapBuilder {
	b.structureMap.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *StructureMapBuilder) AddIdentifier(v Identifier) *StructureMapBuilder {
	b.structureMap.Identifier = append(b.structureMap.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *StructureMapBuilder) SetVersion(v string) *StructureMapBuilder {
	b.structureMap.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *StructureMapBuilder) SetVersionAlgorithmString(v string) *StructureMapBuilder {
	b.structureMap.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *StructureMapBuilder) SetVersionAlgorithmStringExt(v Element) *StructureMapBuilder {
	b.structureMap.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *StructureMapBuilder) SetVersionAlgorithmCoding(v Coding) *StructureMapBuilder {
	b.structureMap.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *StructureMapBuilder) SetName(v string) *StructureMapBuilder {
	b.structureMap.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *StructureMapBuilder) SetTitle(v string) *StructureMapBuilder {
	b.structureMap.Title = &v
	return b
}

// SetStatus sets the Status field.
func (b *StructureMapBuilder) SetStatus(v PublicationStatus) *StructureMapBuilder {
	b.structureMap.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *StructureMapBuilder) SetExperimental(v bool) *StructureMapBuilder {
	b.structureMap.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *StructureMapBuilder) SetDate(v string) *StructureMapBuilder {
	b.structureMap.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *StructureMapBuilder) SetPublisher(v string) *StructureMapBuilder {
	b.structureMap.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *StructureMapBuilder) AddContact(v ContactDetail) *StructureMapBuilder {
	b.structureMap.Contact = append(b.structureMap.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *StructureMapBuilder) SetDescription(v string) *StructureMapBuilder {
	b.structureMap.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *StructureMapBuilder) AddUseContext(v UsageContext) *StructureMapBuilder {
	b.structureMap.UseContext = append(b.structureMap.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *StructureMapBuilder) AddJurisdiction(v CodeableConcept) *StructureMapBuilder {
	b.structureMap.Jurisdiction = append(b.structureMap.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *StructureMapBuilder) SetPurpose(v string) *StructureMapBuilder {
	b.structureMap.Purpose = &v
	return b
}

// SetCopyright sets the Copyright field.
func (b *StructureMapBuilder) SetCopyright(v string) *StructureMapBuilder {
	b.structureMap.Copyright = &v
	return b
}

// SetCopyrightLabel sets the CopyrightLabel field.
func (b *StructureMapBuilder) SetCopyrightLabel(v string) *StructureMapBuilder {
	b.structureMap.CopyrightLabel = &v
	return b
}

// AddStructure adds a Structure element.
func (b *StructureMapBuilder) AddStructure(v StructureMapStructure) *StructureMapBuilder {
	b.structureMap.Structure = append(b.structureMap.Structure, v)
	return b
}

// AddImport adds a Import element.
func (b *StructureMapBuilder) AddImport(v string) *StructureMapBuilder {
	b.structureMap.Import = append(b.structureMap.Import, v)
	return b
}

// AddConst adds a Const element.
func (b *StructureMapBuilder) AddConst(v StructureMapConst) *StructureMapBuilder {
	b.structureMap.Const = append(b.structureMap.Const, v)
	return b
}

// AddGroup adds a Group element.
func (b *StructureMapBuilder) AddGroup(v StructureMapGroup) *StructureMapBuilder {
	b.structureMap.Group = append(b.structureMap.Group, v)
	return b
}
