// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// ConditionDefinition - Fluent Builder
// =============================================================================

// ConditionDefinitionBuilder provides a fluent API for constructing ConditionDefinition resources.
type ConditionDefinitionBuilder struct {
	conditionDefinition *ConditionDefinition
}

// NewConditionDefinitionBuilder creates a new ConditionDefinitionBuilder.
func NewConditionDefinitionBuilder() *ConditionDefinitionBuilder {
	return &ConditionDefinitionBuilder{
		conditionDefinition: &ConditionDefinition{},
	}
}

// Build returns the constructed ConditionDefinition resource.
func (b *ConditionDefinitionBuilder) Build() *ConditionDefinition {
	return b.conditionDefinition
}

// SetId sets the Id field.
func (b *ConditionDefinitionBuilder) SetId(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *ConditionDefinitionBuilder) SetMeta(v Meta) *ConditionDefinitionBuilder {
	b.conditionDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *ConditionDefinitionBuilder) SetImplicitRules(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *ConditionDefinitionBuilder) SetLanguage(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *ConditionDefinitionBuilder) SetText(v Narrative) *ConditionDefinitionBuilder {
	b.conditionDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *ConditionDefinitionBuilder) AddContained(v Resource) *ConditionDefinitionBuilder {
	b.conditionDefinition.Contained = append(b.conditionDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *ConditionDefinitionBuilder) AddExtension(v Extension) *ConditionDefinitionBuilder {
	b.conditionDefinition.Extension = append(b.conditionDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *ConditionDefinitionBuilder) AddModifierExtension(v Extension) *ConditionDefinitionBuilder {
	b.conditionDefinition.ModifierExtension = append(b.conditionDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *ConditionDefinitionBuilder) SetUrl(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Url = &v
	return b
}

// AddIdentifier adds a Identifier element.
func (b *ConditionDefinitionBuilder) AddIdentifier(v Identifier) *ConditionDefinitionBuilder {
	b.conditionDefinition.Identifier = append(b.conditionDefinition.Identifier, v)
	return b
}

// SetVersion sets the Version field.
func (b *ConditionDefinitionBuilder) SetVersion(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Version = &v
	return b
}

// SetVersionAlgorithmString sets the VersionAlgorithmString field.
func (b *ConditionDefinitionBuilder) SetVersionAlgorithmString(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.VersionAlgorithmString = &v
	return b
}

// SetVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func (b *ConditionDefinitionBuilder) SetVersionAlgorithmStringExt(v Element) *ConditionDefinitionBuilder {
	b.conditionDefinition.VersionAlgorithmStringExt = &v
	return b
}

// SetVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func (b *ConditionDefinitionBuilder) SetVersionAlgorithmCoding(v Coding) *ConditionDefinitionBuilder {
	b.conditionDefinition.VersionAlgorithmCoding = &v
	return b
}

// SetName sets the Name field.
func (b *ConditionDefinitionBuilder) SetName(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *ConditionDefinitionBuilder) SetTitle(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Title = &v
	return b
}

// SetSubtitle sets the Subtitle field.
func (b *ConditionDefinitionBuilder) SetSubtitle(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Subtitle = &v
	return b
}

// SetStatus sets the Status field.
func (b *ConditionDefinitionBuilder) SetStatus(v PublicationStatus) *ConditionDefinitionBuilder {
	b.conditionDefinition.Status = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *ConditionDefinitionBuilder) SetExperimental(v bool) *ConditionDefinitionBuilder {
	b.conditionDefinition.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *ConditionDefinitionBuilder) SetDate(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *ConditionDefinitionBuilder) SetPublisher(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *ConditionDefinitionBuilder) AddContact(v ContactDetail) *ConditionDefinitionBuilder {
	b.conditionDefinition.Contact = append(b.conditionDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *ConditionDefinitionBuilder) SetDescription(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *ConditionDefinitionBuilder) AddUseContext(v UsageContext) *ConditionDefinitionBuilder {
	b.conditionDefinition.UseContext = append(b.conditionDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *ConditionDefinitionBuilder) AddJurisdiction(v CodeableConcept) *ConditionDefinitionBuilder {
	b.conditionDefinition.Jurisdiction = append(b.conditionDefinition.Jurisdiction, v)
	return b
}

// SetCode sets the Code field.
func (b *ConditionDefinitionBuilder) SetCode(v CodeableConcept) *ConditionDefinitionBuilder {
	b.conditionDefinition.Code = v
	return b
}

// SetSeverity sets the Severity field.
func (b *ConditionDefinitionBuilder) SetSeverity(v CodeableConcept) *ConditionDefinitionBuilder {
	b.conditionDefinition.Severity = &v
	return b
}

// SetBodySite sets the BodySite field.
func (b *ConditionDefinitionBuilder) SetBodySite(v CodeableConcept) *ConditionDefinitionBuilder {
	b.conditionDefinition.BodySite = &v
	return b
}

// SetStage sets the Stage field.
func (b *ConditionDefinitionBuilder) SetStage(v CodeableConcept) *ConditionDefinitionBuilder {
	b.conditionDefinition.Stage = &v
	return b
}

// SetHasSeverity sets the HasSeverity field.
func (b *ConditionDefinitionBuilder) SetHasSeverity(v bool) *ConditionDefinitionBuilder {
	b.conditionDefinition.HasSeverity = &v
	return b
}

// SetHasBodySite sets the HasBodySite field.
func (b *ConditionDefinitionBuilder) SetHasBodySite(v bool) *ConditionDefinitionBuilder {
	b.conditionDefinition.HasBodySite = &v
	return b
}

// SetHasStage sets the HasStage field.
func (b *ConditionDefinitionBuilder) SetHasStage(v bool) *ConditionDefinitionBuilder {
	b.conditionDefinition.HasStage = &v
	return b
}

// AddDefinition adds a Definition element.
func (b *ConditionDefinitionBuilder) AddDefinition(v string) *ConditionDefinitionBuilder {
	b.conditionDefinition.Definition = append(b.conditionDefinition.Definition, v)
	return b
}

// AddObservation adds a Observation element.
func (b *ConditionDefinitionBuilder) AddObservation(v ConditionDefinitionObservation) *ConditionDefinitionBuilder {
	b.conditionDefinition.Observation = append(b.conditionDefinition.Observation, v)
	return b
}

// AddMedication adds a Medication element.
func (b *ConditionDefinitionBuilder) AddMedication(v ConditionDefinitionMedication) *ConditionDefinitionBuilder {
	b.conditionDefinition.Medication = append(b.conditionDefinition.Medication, v)
	return b
}

// AddPrecondition adds a Precondition element.
func (b *ConditionDefinitionBuilder) AddPrecondition(v ConditionDefinitionPrecondition) *ConditionDefinitionBuilder {
	b.conditionDefinition.Precondition = append(b.conditionDefinition.Precondition, v)
	return b
}

// AddTeam adds a Team element.
func (b *ConditionDefinitionBuilder) AddTeam(v Reference) *ConditionDefinitionBuilder {
	b.conditionDefinition.Team = append(b.conditionDefinition.Team, v)
	return b
}

// AddQuestionnaire adds a Questionnaire element.
func (b *ConditionDefinitionBuilder) AddQuestionnaire(v ConditionDefinitionQuestionnaire) *ConditionDefinitionBuilder {
	b.conditionDefinition.Questionnaire = append(b.conditionDefinition.Questionnaire, v)
	return b
}

// AddPlan adds a Plan element.
func (b *ConditionDefinitionBuilder) AddPlan(v ConditionDefinitionPlan) *ConditionDefinitionBuilder {
	b.conditionDefinition.Plan = append(b.conditionDefinition.Plan, v)
	return b
}
