// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r5

package r5

// =============================================================================
// AppointmentResponse - Fluent Builder
// =============================================================================

// AppointmentResponseBuilder provides a fluent API for constructing AppointmentResponse resources.
type AppointmentResponseBuilder struct {
	appointmentResponse *AppointmentResponse
}

// NewAppointmentResponseBuilder creates a new AppointmentResponseBuilder.
func NewAppointmentResponseBuilder() *AppointmentResponseBuilder {
	return &AppointmentResponseBuilder{
		appointmentResponse: &AppointmentResponse{},
	}
}

// Build returns the constructed AppointmentResponse resource.
func (b *AppointmentResponseBuilder) Build() *AppointmentResponse {
	return b.appointmentResponse
}

// SetId sets the Id field.
func (b *AppointmentResponseBuilder) SetId(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *AppointmentResponseBuilder) SetMeta(v Meta) *AppointmentResponseBuilder {
	b.appointmentResponse.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *AppointmentResponseBuilder) SetImplicitRules(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *AppointmentResponseBuilder) SetLanguage(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.Language = &v
	return b
}

// SetText sets the Text field.
func (b *AppointmentResponseBuilder) SetText(v Narrative) *AppointmentResponseBuilder {
	b.appointmentResponse.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *AppointmentResponseBuilder) AddContained(v Resource) *AppointmentResponseBuilder {
	b.appointmentResponse.Contained = append(b.appointmentResponse.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *AppointmentResponseBuilder) AddExtension(v Extension) *AppointmentResponseBuilder {
	b.appointmentResponse.Extension = append(b.appointmentResponse.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *AppointmentResponseBuilder) AddModifierExtension(v Extension) *AppointmentResponseBuilder {
	b.appointmentResponse.ModifierExtension = append(b.appointmentResponse.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *AppointmentResponseBuilder) AddIdentifier(v Identifier) *AppointmentResponseBuilder {
	b.appointmentResponse.Identifier = append(b.appointmentResponse.Identifier, v)
	return b
}

// SetAppointment sets the Appointment field.
func (b *AppointmentResponseBuilder) SetAppointment(v Reference) *AppointmentResponseBuilder {
	b.appointmentResponse.Appointment = v
	return b
}

// SetProposedNewTime sets the ProposedNewTime field.
func (b *AppointmentResponseBuilder) SetProposedNewTime(v bool) *AppointmentResponseBuilder {
	b.appointmentResponse.ProposedNewTime = &v
	return b
}

// SetStart sets the Start field.
func (b *AppointmentResponseBuilder) SetStart(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.Start = &v
	return b
}

// SetEnd sets the End field.
func (b *AppointmentResponseBuilder) SetEnd(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.End = &v
	return b
}

// AddParticipantType adds a ParticipantType element.
func (b *AppointmentResponseBuilder) AddParticipantType(v CodeableConcept) *AppointmentResponseBuilder {
	b.appointmentResponse.ParticipantType = append(b.appointmentResponse.ParticipantType, v)
	return b
}

// SetActor sets the Actor field.
func (b *AppointmentResponseBuilder) SetActor(v Reference) *AppointmentResponseBuilder {
	b.appointmentResponse.Actor = &v
	return b
}

// SetParticipantStatus sets the ParticipantStatus field.
func (b *AppointmentResponseBuilder) SetParticipantStatus(v AppointmentResponseStatus) *AppointmentResponseBuilder {
	b.appointmentResponse.ParticipantStatus = &v
	return b
}

// SetComment sets the Comment field.
func (b *AppointmentResponseBuilder) SetComment(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.Comment = &v
	return b
}

// SetRecurring sets the Recurring field.
func (b *AppointmentResponseBuilder) SetRecurring(v bool) *AppointmentResponseBuilder {
	b.appointmentResponse.Recurring = &v
	return b
}

// SetOccurrenceDate sets the OccurrenceDate field.
func (b *AppointmentResponseBuilder) SetOccurrenceDate(v string) *AppointmentResponseBuilder {
	b.appointmentResponse.OccurrenceDate = &v
	return b
}

// SetRecurrenceId sets the RecurrenceId field.
func (b *AppointmentResponseBuilder) SetRecurrenceId(v uint32) *AppointmentResponseBuilder {
	b.appointmentResponse.RecurrenceId = &v
	return b
}
