// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (datatypes)
// Package: r5

package r5

// CodeableConcept represents FHIR CodeableConcept.
type CodeableConcept struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Code defined by a terminology system
	Coding []Coding `json:"coding,omitempty"`
	// Plain text representation of the concept
	Text *string `json:"text,omitempty"`
	// Extension for Text
	TextExt *Element `json:"_text,omitempty"`
}
