// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r5

package r5

// =============================================================================
// Permission - Functional Options
// =============================================================================

// PermissionOption is a functional option for configuring a Permission.
type PermissionOption func(*Permission)

// NewPermission creates a new Permission with the given options.
func NewPermission(opts ...PermissionOption) *Permission {
	r := &Permission{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithPermissionId sets the Id field.
func WithPermissionId(v string) PermissionOption {
	return func(r *Permission) {
		r.Id = &v
	}
}

// WithPermissionMeta sets the Meta field.
func WithPermissionMeta(v Meta) PermissionOption {
	return func(r *Permission) {
		r.Meta = &v
	}
}

// WithPermissionImplicitRules sets the ImplicitRules field.
func WithPermissionImplicitRules(v string) PermissionOption {
	return func(r *Permission) {
		r.ImplicitRules = &v
	}
}

// WithPermissionLanguage sets the Language field.
func WithPermissionLanguage(v string) PermissionOption {
	return func(r *Permission) {
		r.Language = &v
	}
}

// WithPermissionText sets the Text field.
func WithPermissionText(v Narrative) PermissionOption {
	return func(r *Permission) {
		r.Text = &v
	}
}

// WithPermissionContained adds a Contained to the Permission.
func WithPermissionContained(v Resource) PermissionOption {
	return func(r *Permission) {
		r.Contained = append(r.Contained, v)
	}
}

// WithPermissionExtension adds a Extension to the Permission.
func WithPermissionExtension(v Extension) PermissionOption {
	return func(r *Permission) {
		r.Extension = append(r.Extension, v)
	}
}

// WithPermissionModifierExtension adds a ModifierExtension to the Permission.
func WithPermissionModifierExtension(v Extension) PermissionOption {
	return func(r *Permission) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithPermissionStatus sets the Status field.
func WithPermissionStatus(v PermissionStatus) PermissionOption {
	return func(r *Permission) {
		r.Status = &v
	}
}

// WithPermissionAsserter sets the Asserter field.
func WithPermissionAsserter(v Reference) PermissionOption {
	return func(r *Permission) {
		r.Asserter = &v
	}
}

// WithPermissionDate adds a Date to the Permission.
func WithPermissionDate(v string) PermissionOption {
	return func(r *Permission) {
		r.Date = append(r.Date, v)
	}
}

// WithPermissionValidity sets the Validity field.
func WithPermissionValidity(v Period) PermissionOption {
	return func(r *Permission) {
		r.Validity = &v
	}
}

// WithPermissionJustification sets the Justification field.
func WithPermissionJustification(v PermissionJustification) PermissionOption {
	return func(r *Permission) {
		r.Justification = &v
	}
}

// WithPermissionCombining sets the Combining field.
func WithPermissionCombining(v PermissionRuleCombining) PermissionOption {
	return func(r *Permission) {
		r.Combining = &v
	}
}

// WithPermissionRule adds a Rule to the Permission.
func WithPermissionRule(v PermissionRule) PermissionOption {
	return func(r *Permission) {
		r.Rule = append(r.Rule, v)
	}
}
