// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r5

package r5

// =============================================================================
// Person - Functional Options
// =============================================================================

// PersonOption is a functional option for configuring a Person.
type PersonOption func(*Person)

// NewPerson creates a new Person with the given options.
func NewPerson(opts ...PersonOption) *Person {
	r := &Person{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithPersonId sets the Id field.
func WithPersonId(v string) PersonOption {
	return func(r *Person) {
		r.Id = &v
	}
}

// WithPersonMeta sets the Meta field.
func WithPersonMeta(v Meta) PersonOption {
	return func(r *Person) {
		r.Meta = &v
	}
}

// WithPersonImplicitRules sets the ImplicitRules field.
func WithPersonImplicitRules(v string) PersonOption {
	return func(r *Person) {
		r.ImplicitRules = &v
	}
}

// WithPersonLanguage sets the Language field.
func WithPersonLanguage(v string) PersonOption {
	return func(r *Person) {
		r.Language = &v
	}
}

// WithPersonText sets the Text field.
func WithPersonText(v Narrative) PersonOption {
	return func(r *Person) {
		r.Text = &v
	}
}

// WithPersonContained adds a Contained to the Person.
func WithPersonContained(v Resource) PersonOption {
	return func(r *Person) {
		r.Contained = append(r.Contained, v)
	}
}

// WithPersonExtension adds a Extension to the Person.
func WithPersonExtension(v Extension) PersonOption {
	return func(r *Person) {
		r.Extension = append(r.Extension, v)
	}
}

// WithPersonModifierExtension adds a ModifierExtension to the Person.
func WithPersonModifierExtension(v Extension) PersonOption {
	return func(r *Person) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithPersonIdentifier adds a Identifier to the Person.
func WithPersonIdentifier(v Identifier) PersonOption {
	return func(r *Person) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithPersonActive sets the Active field.
func WithPersonActive(v bool) PersonOption {
	return func(r *Person) {
		r.Active = &v
	}
}

// WithPersonName adds a Name to the Person.
func WithPersonName(v HumanName) PersonOption {
	return func(r *Person) {
		r.Name = append(r.Name, v)
	}
}

// WithPersonTelecom adds a Telecom to the Person.
func WithPersonTelecom(v ContactPoint) PersonOption {
	return func(r *Person) {
		r.Telecom = append(r.Telecom, v)
	}
}

// WithPersonGender sets the Gender field.
func WithPersonGender(v AdministrativeGender) PersonOption {
	return func(r *Person) {
		r.Gender = &v
	}
}

// WithPersonBirthDate sets the BirthDate field.
func WithPersonBirthDate(v string) PersonOption {
	return func(r *Person) {
		r.BirthDate = &v
	}
}

// WithPersonDeceasedBoolean sets the DeceasedBoolean field.
func WithPersonDeceasedBoolean(v bool) PersonOption {
	return func(r *Person) {
		r.DeceasedBoolean = &v
	}
}

// WithPersonDeceasedBooleanExt sets the DeceasedBooleanExt field.
func WithPersonDeceasedBooleanExt(v Element) PersonOption {
	return func(r *Person) {
		r.DeceasedBooleanExt = &v
	}
}

// WithPersonDeceasedDateTime sets the DeceasedDateTime field.
func WithPersonDeceasedDateTime(v string) PersonOption {
	return func(r *Person) {
		r.DeceasedDateTime = &v
	}
}

// WithPersonDeceasedDateTimeExt sets the DeceasedDateTimeExt field.
func WithPersonDeceasedDateTimeExt(v Element) PersonOption {
	return func(r *Person) {
		r.DeceasedDateTimeExt = &v
	}
}

// WithPersonAddress adds a Address to the Person.
func WithPersonAddress(v Address) PersonOption {
	return func(r *Person) {
		r.Address = append(r.Address, v)
	}
}

// WithPersonMaritalStatus sets the MaritalStatus field.
func WithPersonMaritalStatus(v CodeableConcept) PersonOption {
	return func(r *Person) {
		r.MaritalStatus = &v
	}
}

// WithPersonPhoto adds a Photo to the Person.
func WithPersonPhoto(v Attachment) PersonOption {
	return func(r *Person) {
		r.Photo = append(r.Photo, v)
	}
}

// WithPersonCommunication adds a Communication to the Person.
func WithPersonCommunication(v PersonCommunication) PersonOption {
	return func(r *Person) {
		r.Communication = append(r.Communication, v)
	}
}

// WithPersonManagingOrganization sets the ManagingOrganization field.
func WithPersonManagingOrganization(v Reference) PersonOption {
	return func(r *Person) {
		r.ManagingOrganization = &v
	}
}

// WithPersonLink adds a Link to the Person.
func WithPersonLink(v PersonLink) PersonOption {
	return func(r *Person) {
		r.Link = append(r.Link, v)
	}
}
