// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r5

package r5

// =============================================================================
// NamingSystem - Functional Options
// =============================================================================

// NamingSystemOption is a functional option for configuring a NamingSystem.
type NamingSystemOption func(*NamingSystem)

// NewNamingSystem creates a new NamingSystem with the given options.
func NewNamingSystem(opts ...NamingSystemOption) *NamingSystem {
	r := &NamingSystem{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithNamingSystemId sets the Id field.
func WithNamingSystemId(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Id = &v
	}
}

// WithNamingSystemMeta sets the Meta field.
func WithNamingSystemMeta(v Meta) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Meta = &v
	}
}

// WithNamingSystemImplicitRules sets the ImplicitRules field.
func WithNamingSystemImplicitRules(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.ImplicitRules = &v
	}
}

// WithNamingSystemLanguage sets the Language field.
func WithNamingSystemLanguage(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Language = &v
	}
}

// WithNamingSystemText sets the Text field.
func WithNamingSystemText(v Narrative) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Text = &v
	}
}

// WithNamingSystemContained adds a Contained to the NamingSystem.
func WithNamingSystemContained(v Resource) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Contained = append(r.Contained, v)
	}
}

// WithNamingSystemExtension adds a Extension to the NamingSystem.
func WithNamingSystemExtension(v Extension) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Extension = append(r.Extension, v)
	}
}

// WithNamingSystemModifierExtension adds a ModifierExtension to the NamingSystem.
func WithNamingSystemModifierExtension(v Extension) NamingSystemOption {
	return func(r *NamingSystem) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithNamingSystemUrl sets the Url field.
func WithNamingSystemUrl(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Url = &v
	}
}

// WithNamingSystemIdentifier adds a Identifier to the NamingSystem.
func WithNamingSystemIdentifier(v Identifier) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithNamingSystemVersion sets the Version field.
func WithNamingSystemVersion(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Version = &v
	}
}

// WithNamingSystemVersionAlgorithmString sets the VersionAlgorithmString field.
func WithNamingSystemVersionAlgorithmString(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.VersionAlgorithmString = &v
	}
}

// WithNamingSystemVersionAlgorithmStringExt sets the VersionAlgorithmStringExt field.
func WithNamingSystemVersionAlgorithmStringExt(v Element) NamingSystemOption {
	return func(r *NamingSystem) {
		r.VersionAlgorithmStringExt = &v
	}
}

// WithNamingSystemVersionAlgorithmCoding sets the VersionAlgorithmCoding field.
func WithNamingSystemVersionAlgorithmCoding(v Coding) NamingSystemOption {
	return func(r *NamingSystem) {
		r.VersionAlgorithmCoding = &v
	}
}

// WithNamingSystemName sets the Name field.
func WithNamingSystemName(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Name = &v
	}
}

// WithNamingSystemTitle sets the Title field.
func WithNamingSystemTitle(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Title = &v
	}
}

// WithNamingSystemStatus sets the Status field.
func WithNamingSystemStatus(v PublicationStatus) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Status = &v
	}
}

// WithNamingSystemKind sets the Kind field.
func WithNamingSystemKind(v NamingSystemType) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Kind = &v
	}
}

// WithNamingSystemExperimental sets the Experimental field.
func WithNamingSystemExperimental(v bool) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Experimental = &v
	}
}

// WithNamingSystemDate sets the Date field.
func WithNamingSystemDate(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Date = &v
	}
}

// WithNamingSystemPublisher sets the Publisher field.
func WithNamingSystemPublisher(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Publisher = &v
	}
}

// WithNamingSystemContact adds a Contact to the NamingSystem.
func WithNamingSystemContact(v ContactDetail) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Contact = append(r.Contact, v)
	}
}

// WithNamingSystemResponsible sets the Responsible field.
func WithNamingSystemResponsible(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Responsible = &v
	}
}

// WithNamingSystemType sets the Type field.
func WithNamingSystemType(v CodeableConcept) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Type = &v
	}
}

// WithNamingSystemDescription sets the Description field.
func WithNamingSystemDescription(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Description = &v
	}
}

// WithNamingSystemUseContext adds a UseContext to the NamingSystem.
func WithNamingSystemUseContext(v UsageContext) NamingSystemOption {
	return func(r *NamingSystem) {
		r.UseContext = append(r.UseContext, v)
	}
}

// WithNamingSystemJurisdiction adds a Jurisdiction to the NamingSystem.
func WithNamingSystemJurisdiction(v CodeableConcept) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Jurisdiction = append(r.Jurisdiction, v)
	}
}

// WithNamingSystemPurpose sets the Purpose field.
func WithNamingSystemPurpose(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Purpose = &v
	}
}

// WithNamingSystemCopyright sets the Copyright field.
func WithNamingSystemCopyright(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Copyright = &v
	}
}

// WithNamingSystemCopyrightLabel sets the CopyrightLabel field.
func WithNamingSystemCopyrightLabel(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.CopyrightLabel = &v
	}
}

// WithNamingSystemApprovalDate sets the ApprovalDate field.
func WithNamingSystemApprovalDate(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.ApprovalDate = &v
	}
}

// WithNamingSystemLastReviewDate sets the LastReviewDate field.
func WithNamingSystemLastReviewDate(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.LastReviewDate = &v
	}
}

// WithNamingSystemEffectivePeriod sets the EffectivePeriod field.
func WithNamingSystemEffectivePeriod(v Period) NamingSystemOption {
	return func(r *NamingSystem) {
		r.EffectivePeriod = &v
	}
}

// WithNamingSystemTopic adds a Topic to the NamingSystem.
func WithNamingSystemTopic(v CodeableConcept) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Topic = append(r.Topic, v)
	}
}

// WithNamingSystemAuthor adds a Author to the NamingSystem.
func WithNamingSystemAuthor(v ContactDetail) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Author = append(r.Author, v)
	}
}

// WithNamingSystemEditor adds a Editor to the NamingSystem.
func WithNamingSystemEditor(v ContactDetail) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Editor = append(r.Editor, v)
	}
}

// WithNamingSystemReviewer adds a Reviewer to the NamingSystem.
func WithNamingSystemReviewer(v ContactDetail) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Reviewer = append(r.Reviewer, v)
	}
}

// WithNamingSystemEndorser adds a Endorser to the NamingSystem.
func WithNamingSystemEndorser(v ContactDetail) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Endorser = append(r.Endorser, v)
	}
}

// WithNamingSystemRelatedArtifact adds a RelatedArtifact to the NamingSystem.
func WithNamingSystemRelatedArtifact(v RelatedArtifact) NamingSystemOption {
	return func(r *NamingSystem) {
		r.RelatedArtifact = append(r.RelatedArtifact, v)
	}
}

// WithNamingSystemUsage sets the Usage field.
func WithNamingSystemUsage(v string) NamingSystemOption {
	return func(r *NamingSystem) {
		r.Usage = &v
	}
}

// WithNamingSystemUniqueId adds a UniqueId to the NamingSystem.
func WithNamingSystemUniqueId(v NamingSystemUniqueId) NamingSystemOption {
	return func(r *NamingSystem) {
		r.UniqueId = append(r.UniqueId, v)
	}
}
