// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r5

package r5

// =============================================================================
// Encounter - Functional Options
// =============================================================================

// EncounterOption is a functional option for configuring a Encounter.
type EncounterOption func(*Encounter)

// NewEncounter creates a new Encounter with the given options.
func NewEncounter(opts ...EncounterOption) *Encounter {
	r := &Encounter{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithEncounterId sets the Id field.
func WithEncounterId(v string) EncounterOption {
	return func(r *Encounter) {
		r.Id = &v
	}
}

// WithEncounterMeta sets the Meta field.
func WithEncounterMeta(v Meta) EncounterOption {
	return func(r *Encounter) {
		r.Meta = &v
	}
}

// WithEncounterImplicitRules sets the ImplicitRules field.
func WithEncounterImplicitRules(v string) EncounterOption {
	return func(r *Encounter) {
		r.ImplicitRules = &v
	}
}

// WithEncounterLanguage sets the Language field.
func WithEncounterLanguage(v string) EncounterOption {
	return func(r *Encounter) {
		r.Language = &v
	}
}

// WithEncounterText sets the Text field.
func WithEncounterText(v Narrative) EncounterOption {
	return func(r *Encounter) {
		r.Text = &v
	}
}

// WithEncounterContained adds a Contained to the Encounter.
func WithEncounterContained(v Resource) EncounterOption {
	return func(r *Encounter) {
		r.Contained = append(r.Contained, v)
	}
}

// WithEncounterExtension adds a Extension to the Encounter.
func WithEncounterExtension(v Extension) EncounterOption {
	return func(r *Encounter) {
		r.Extension = append(r.Extension, v)
	}
}

// WithEncounterModifierExtension adds a ModifierExtension to the Encounter.
func WithEncounterModifierExtension(v Extension) EncounterOption {
	return func(r *Encounter) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithEncounterIdentifier adds a Identifier to the Encounter.
func WithEncounterIdentifier(v Identifier) EncounterOption {
	return func(r *Encounter) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithEncounterStatus sets the Status field.
func WithEncounterStatus(v EncounterStatus) EncounterOption {
	return func(r *Encounter) {
		r.Status = &v
	}
}

// WithEncounterClass adds a Class to the Encounter.
func WithEncounterClass(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.Class = append(r.Class, v)
	}
}

// WithEncounterPriority sets the Priority field.
func WithEncounterPriority(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.Priority = &v
	}
}

// WithEncounterType adds a Type to the Encounter.
func WithEncounterType(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.Type = append(r.Type, v)
	}
}

// WithEncounterServiceType adds a ServiceType to the Encounter.
func WithEncounterServiceType(v CodeableReference) EncounterOption {
	return func(r *Encounter) {
		r.ServiceType = append(r.ServiceType, v)
	}
}

// WithEncounterSubject sets the Subject field.
func WithEncounterSubject(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.Subject = &v
	}
}

// WithEncounterSubjectStatus sets the SubjectStatus field.
func WithEncounterSubjectStatus(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.SubjectStatus = &v
	}
}

// WithEncounterEpisodeOfCare adds a EpisodeOfCare to the Encounter.
func WithEncounterEpisodeOfCare(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.EpisodeOfCare = append(r.EpisodeOfCare, v)
	}
}

// WithEncounterBasedOn adds a BasedOn to the Encounter.
func WithEncounterBasedOn(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithEncounterCareTeam adds a CareTeam to the Encounter.
func WithEncounterCareTeam(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.CareTeam = append(r.CareTeam, v)
	}
}

// WithEncounterPartOf sets the PartOf field.
func WithEncounterPartOf(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.PartOf = &v
	}
}

// WithEncounterServiceProvider sets the ServiceProvider field.
func WithEncounterServiceProvider(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.ServiceProvider = &v
	}
}

// WithEncounterParticipant adds a Participant to the Encounter.
func WithEncounterParticipant(v EncounterParticipant) EncounterOption {
	return func(r *Encounter) {
		r.Participant = append(r.Participant, v)
	}
}

// WithEncounterAppointment adds a Appointment to the Encounter.
func WithEncounterAppointment(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.Appointment = append(r.Appointment, v)
	}
}

// WithEncounterVirtualService adds a VirtualService to the Encounter.
func WithEncounterVirtualService(v VirtualServiceDetail) EncounterOption {
	return func(r *Encounter) {
		r.VirtualService = append(r.VirtualService, v)
	}
}

// WithEncounterActualPeriod sets the ActualPeriod field.
func WithEncounterActualPeriod(v Period) EncounterOption {
	return func(r *Encounter) {
		r.ActualPeriod = &v
	}
}

// WithEncounterPlannedStartDate sets the PlannedStartDate field.
func WithEncounterPlannedStartDate(v string) EncounterOption {
	return func(r *Encounter) {
		r.PlannedStartDate = &v
	}
}

// WithEncounterPlannedEndDate sets the PlannedEndDate field.
func WithEncounterPlannedEndDate(v string) EncounterOption {
	return func(r *Encounter) {
		r.PlannedEndDate = &v
	}
}

// WithEncounterLength sets the Length field.
func WithEncounterLength(v Duration) EncounterOption {
	return func(r *Encounter) {
		r.Length = &v
	}
}

// WithEncounterReason adds a Reason to the Encounter.
func WithEncounterReason(v EncounterReason) EncounterOption {
	return func(r *Encounter) {
		r.Reason = append(r.Reason, v)
	}
}

// WithEncounterDiagnosis adds a Diagnosis to the Encounter.
func WithEncounterDiagnosis(v EncounterDiagnosis) EncounterOption {
	return func(r *Encounter) {
		r.Diagnosis = append(r.Diagnosis, v)
	}
}

// WithEncounterAccount adds a Account to the Encounter.
func WithEncounterAccount(v Reference) EncounterOption {
	return func(r *Encounter) {
		r.Account = append(r.Account, v)
	}
}

// WithEncounterDietPreference adds a DietPreference to the Encounter.
func WithEncounterDietPreference(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.DietPreference = append(r.DietPreference, v)
	}
}

// WithEncounterSpecialArrangement adds a SpecialArrangement to the Encounter.
func WithEncounterSpecialArrangement(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.SpecialArrangement = append(r.SpecialArrangement, v)
	}
}

// WithEncounterSpecialCourtesy adds a SpecialCourtesy to the Encounter.
func WithEncounterSpecialCourtesy(v CodeableConcept) EncounterOption {
	return func(r *Encounter) {
		r.SpecialCourtesy = append(r.SpecialCourtesy, v)
	}
}

// WithEncounterAdmission sets the Admission field.
func WithEncounterAdmission(v EncounterAdmission) EncounterOption {
	return func(r *Encounter) {
		r.Admission = &v
	}
}

// WithEncounterLocation adds a Location to the Encounter.
func WithEncounterLocation(v EncounterLocation) EncounterOption {
	return func(r *Encounter) {
		r.Location = append(r.Location, v)
	}
}
