// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// MolecularSequence represents FHIR MolecularSequence.
type MolecularSequence struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Unique ID for this particular sequence
	Identifier []Identifier `json:"identifier,omitempty"`
	// aa | dna | rna
	Type *SequenceType `json:"type,omitempty"`
	// Extension for Type
	TypeExt *Element `json:"_type,omitempty"`
	// Subject this sequence is associated too
	Subject *Reference `json:"subject,omitempty"`
	// What the molecular sequence is about, when it is not about the subject of record
	Focus []Reference `json:"focus,omitempty"`
	// Specimen used for sequencing
	Specimen *Reference `json:"specimen,omitempty"`
	// The method for sequencing
	Device *Reference `json:"device,omitempty"`
	// Who should be responsible for test result
	Performer *Reference `json:"performer,omitempty"`
	// Sequence that was observed
	Literal *string `json:"literal,omitempty"`
	// Extension for Literal
	LiteralExt *Element `json:"_literal,omitempty"`
	// Embedded file or a link (URL) which contains content to represent the sequence
	Formatted []Attachment `json:"formatted,omitempty"`
	// A sequence defined relative to another sequence
	Relative []MolecularSequenceRelative `json:"relative,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *MolecularSequence) GetResourceType() string {
	return "MolecularSequence"
}

// GetId returns the resource's logical ID.
func (r *MolecularSequence) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *MolecularSequence) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *MolecularSequence) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *MolecularSequence) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *MolecularSequence) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *MolecularSequence) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *MolecularSequence) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *MolecularSequence) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *MolecularSequence) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r MolecularSequence) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MolecularSequence"
	type Alias MolecularSequence
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *MolecularSequence) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias MolecularSequence
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
