// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// NutritionIntake represents FHIR NutritionIntake.
type NutritionIntake struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// External identifier
	Identifier []Identifier `json:"identifier,omitempty"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt []Element `json:"_instantiatesCanonical,omitempty"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty"`
	// Extension for InstantiatesUri
	InstantiatesUriExt []Element `json:"_instantiatesUri,omitempty"`
	// Fulfils plan, proposal or order
	BasedOn []Reference `json:"basedOn,omitempty"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status *EventStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Reason for current status
	StatusReason []CodeableConcept `json:"statusReason,omitempty"`
	// Code representing an overall type of nutrition intake
	Code *CodeableConcept `json:"code,omitempty"`
	// Who is/was consuming the food or fluid
	Subject Reference `json:"subject"`
	// Encounter associated with NutritionIntake
	Encounter *Reference `json:"encounter,omitempty"`
	// The date/time or interval when the food or fluid is/was consumed
	OccurrenceDateTime *string `json:"occurrenceDateTime,omitempty"`
	// Extension for OccurrenceDateTime
	OccurrenceDateTimeExt *Element `json:"_occurrenceDateTime,omitempty"`
	// The date/time or interval when the food or fluid is/was consumed
	OccurrencePeriod *Period `json:"occurrencePeriod,omitempty"`
	// When the intake was recorded
	Recorded *string `json:"recorded,omitempty"`
	// Extension for Recorded
	RecordedExt *Element `json:"_recorded,omitempty"`
	// Person or organization that provided the information about the consumption of this food or fluid
	ReportedBoolean *bool `json:"reportedBoolean,omitempty"`
	// Extension for ReportedBoolean
	ReportedBooleanExt *Element `json:"_reportedBoolean,omitempty"`
	// Person or organization that provided the information about the consumption of this food or fluid
	ReportedReference *Reference `json:"reportedReference,omitempty"`
	// What food or fluid product or item was consumed
	ConsumedItem []NutritionIntakeConsumedItem `json:"consumedItem,omitempty"`
	// Total nutrient for the whole meal, product, serving
	IngredientLabel []NutritionIntakeIngredientLabel `json:"ingredientLabel,omitempty"`
	// Who was performed in the intake
	Performer []NutritionIntakePerformer `json:"performer,omitempty"`
	// Where the intake occurred
	Location *Reference `json:"location,omitempty"`
	// Additional supporting information
	DerivedFrom []Reference `json:"derivedFrom,omitempty"`
	// Reason for why the food or fluid is /was consumed
	Reason []CodeableReference `json:"reason,omitempty"`
	// Further information about the consumption
	Note []Annotation `json:"note,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *NutritionIntake) GetResourceType() string {
	return "NutritionIntake"
}

// GetId returns the resource's logical ID.
func (r *NutritionIntake) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *NutritionIntake) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *NutritionIntake) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *NutritionIntake) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *NutritionIntake) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *NutritionIntake) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *NutritionIntake) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *NutritionIntake) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *NutritionIntake) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r NutritionIntake) MarshalJSON() ([]byte, error) {
	r.ResourceType = "NutritionIntake"
	type Alias NutritionIntake
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *NutritionIntake) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias NutritionIntake
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
