// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// DeviceMetric represents FHIR DeviceMetric.
type DeviceMetric struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Instance identifier
	Identifier []Identifier `json:"identifier,omitempty"`
	// Identity of metric, for example Heart Rate or PEEP Setting
	Type CodeableConcept `json:"type"`
	// Unit of Measure for the Metric
	Unit *CodeableConcept `json:"unit,omitempty"`
	// Describes the link to the Device
	Device Reference `json:"device"`
	// on | off | standby | entered-in-error
	OperationalStatus *DeviceMetricOperationalStatus `json:"operationalStatus,omitempty"`
	// Extension for OperationalStatus
	OperationalStatusExt *Element `json:"_operationalStatus,omitempty"`
	// Color name (from CSS4) or #RRGGBB code
	Color *string `json:"color,omitempty"`
	// Extension for Color
	ColorExt *Element `json:"_color,omitempty"`
	// measurement | setting | calculation | unspecified
	Category *DeviceMetricCategory `json:"category,omitempty"`
	// Extension for Category
	CategoryExt *Element `json:"_category,omitempty"`
	// Indicates how often the metric is taken or recorded
	MeasurementFrequency *Quantity `json:"measurementFrequency,omitempty"`
	// Describes the calibrations that have been performed or that are required to be performed
	Calibration []DeviceMetricCalibration `json:"calibration,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *DeviceMetric) GetResourceType() string {
	return "DeviceMetric"
}

// GetId returns the resource's logical ID.
func (r *DeviceMetric) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *DeviceMetric) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *DeviceMetric) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *DeviceMetric) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *DeviceMetric) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *DeviceMetric) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *DeviceMetric) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *DeviceMetric) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *DeviceMetric) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r DeviceMetric) MarshalJSON() ([]byte, error) {
	r.ResourceType = "DeviceMetric"
	type Alias DeviceMetric
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *DeviceMetric) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias DeviceMetric
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
