// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// Questionnaire represents FHIR Questionnaire.
type Questionnaire struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Canonical identifier for this questionnaire, represented as an absolute URI (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Business identifier for questionnaire
	Identifier []Identifier `json:"identifier,omitempty"`
	// Business version of the questionnaire
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// How to compare versions
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *Element `json:"_versionAlgorithmString,omitempty"`
	// How to compare versions
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty"`
	// Name for this questionnaire (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Name for this questionnaire (human friendly)
	Title *string `json:"title,omitempty"`
	// Extension for Title
	TitleExt *Element `json:"_title,omitempty"`
	// Based on Questionnaire
	DerivedFrom []string `json:"derivedFrom,omitempty"`
	// Extension for DerivedFrom
	DerivedFromExt []Element `json:"_derivedFrom,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Resource that can be subject of QuestionnaireResponse
	SubjectType []string `json:"subjectType,omitempty"`
	// Extension for SubjectType
	SubjectTypeExt []Element `json:"_subjectType,omitempty"`
	// Date last changed
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the questionnaire
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction for questionnaire (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this questionnaire is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty"`
	// Extension for Copyright
	CopyrightExt *Element `json:"_copyright,omitempty"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *Element `json:"_copyrightLabel,omitempty"`
	// When the questionnaire was approved by publisher
	ApprovalDate *string `json:"approvalDate,omitempty"`
	// Extension for ApprovalDate
	ApprovalDateExt *Element `json:"_approvalDate,omitempty"`
	// When the questionnaire was last reviewed by the publisher
	LastReviewDate *string `json:"lastReviewDate,omitempty"`
	// Extension for LastReviewDate
	LastReviewDateExt *Element `json:"_lastReviewDate,omitempty"`
	// When the questionnaire is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty"`
	// Concept that represents the overall questionnaire
	Code []Coding `json:"code,omitempty"`
	// Questions and sections within the Questionnaire
	Item []QuestionnaireItem `json:"item,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *Questionnaire) GetResourceType() string {
	return "Questionnaire"
}

// GetId returns the resource's logical ID.
func (r *Questionnaire) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *Questionnaire) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *Questionnaire) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *Questionnaire) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *Questionnaire) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *Questionnaire) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *Questionnaire) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *Questionnaire) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *Questionnaire) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r Questionnaire) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Questionnaire"
	type Alias Questionnaire
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *Questionnaire) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias Questionnaire
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
