// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// DeviceDispense represents FHIR DeviceDispense.
type DeviceDispense struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Business identifier for this dispensation
	Identifier []Identifier `json:"identifier,omitempty"`
	// The order or request that this dispense is fulfilling
	BasedOn []Reference `json:"basedOn,omitempty"`
	// The bigger event that this dispense is a part of
	PartOf []Reference `json:"partOf,omitempty"`
	// preparation | in-progress | cancelled | on-hold | completed | entered-in-error | stopped | declined | unknown
	Status *DeviceDispenseStatusCodes `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Why a dispense was or was not performed
	StatusReason *CodeableReference `json:"statusReason,omitempty"`
	// Type of device dispense
	Category []CodeableConcept `json:"category,omitempty"`
	// What device was supplied
	Device CodeableReference `json:"device"`
	// Who the dispense is for
	Subject Reference `json:"subject"`
	// Who collected the device or where the medication was delivered
	Receiver *Reference `json:"receiver,omitempty"`
	// Encounter associated with event
	Encounter *Reference `json:"encounter,omitempty"`
	// Information that supports the dispensing of the device
	SupportingInformation []Reference `json:"supportingInformation,omitempty"`
	// Who performed event
	Performer []DeviceDispensePerformer `json:"performer,omitempty"`
	// Where the dispense occurred
	Location *Reference `json:"location,omitempty"`
	// Trial fill, partial fill, emergency fill, etc
	Type *CodeableConcept `json:"type,omitempty"`
	// Amount dispensed
	Quantity *Quantity `json:"quantity,omitempty"`
	// When product was packaged and reviewed
	PreparedDate *string `json:"preparedDate,omitempty"`
	// Extension for PreparedDate
	PreparedDateExt *Element `json:"_preparedDate,omitempty"`
	// When product was given out
	WhenHandedOver *string `json:"whenHandedOver,omitempty"`
	// Extension for WhenHandedOver
	WhenHandedOverExt *Element `json:"_whenHandedOver,omitempty"`
	// Where the device was sent or should be sent
	Destination *Reference `json:"destination,omitempty"`
	// Information about the dispense
	Note []Annotation `json:"note,omitempty"`
	// Full representation of the usage instructions
	UsageInstruction *string `json:"usageInstruction,omitempty"`
	// Extension for UsageInstruction
	UsageInstructionExt *Element `json:"_usageInstruction,omitempty"`
	// A list of relevant lifecycle events
	EventHistory []Reference `json:"eventHistory,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *DeviceDispense) GetResourceType() string {
	return "DeviceDispense"
}

// GetId returns the resource's logical ID.
func (r *DeviceDispense) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *DeviceDispense) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *DeviceDispense) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *DeviceDispense) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *DeviceDispense) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *DeviceDispense) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *DeviceDispense) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *DeviceDispense) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *DeviceDispense) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r DeviceDispense) MarshalJSON() ([]byte, error) {
	r.ResourceType = "DeviceDispense"
	type Alias DeviceDispense
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *DeviceDispense) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias DeviceDispense
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
