// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// MedicationRequest represents FHIR MedicationRequest.
type MedicationRequest struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// External ids for this request
	Identifier []Identifier `json:"identifier,omitempty"`
	// A plan or request that is fulfilled in whole or in part by this medication request
	BasedOn []Reference `json:"basedOn,omitempty"`
	// Reference to an order/prescription that is being replaced by this MedicationRequest
	PriorPrescription *Reference `json:"priorPrescription,omitempty"`
	// Composite request this is part of
	GroupIdentifier *Identifier `json:"groupIdentifier,omitempty"`
	// active | on-hold | ended | stopped | completed | cancelled | entered-in-error | draft | unknown
	Status *MedicationrequestStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty"`
	// When the status was changed
	StatusChanged *string `json:"statusChanged,omitempty"`
	// Extension for StatusChanged
	StatusChangedExt *Element `json:"_statusChanged,omitempty"`
	// proposal | plan | order | original-order | reflex-order | filler-order | instance-order | option
	Intent *MedicationRequestIntent `json:"intent,omitempty"`
	// Extension for Intent
	IntentExt *Element `json:"_intent,omitempty"`
	// Grouping or category of medication request
	Category []CodeableConcept `json:"category,omitempty"`
	// routine | urgent | asap | stat
	Priority *RequestPriority `json:"priority,omitempty"`
	// Extension for Priority
	PriorityExt *Element `json:"_priority,omitempty"`
	// True if patient is to stop taking or not to start taking the medication
	DoNotPerform *bool `json:"doNotPerform,omitempty"`
	// Extension for DoNotPerform
	DoNotPerformExt *Element `json:"_doNotPerform,omitempty"`
	// Medication to be taken
	Medication CodeableReference `json:"medication"`
	// Individual or group for whom the medication has been requested
	Subject Reference `json:"subject"`
	// The person or organization who provided the information about this request, if the source is someone other than the requestor
	InformationSource []Reference `json:"informationSource,omitempty"`
	// Encounter created as part of encounter/admission/stay
	Encounter *Reference `json:"encounter,omitempty"`
	// Information to support fulfilling of the medication
	SupportingInformation []Reference `json:"supportingInformation,omitempty"`
	// When request was initially authored
	AuthoredOn *string `json:"authoredOn,omitempty"`
	// Extension for AuthoredOn
	AuthoredOnExt *Element `json:"_authoredOn,omitempty"`
	// Who/What requested the Request
	Requester *Reference `json:"requester,omitempty"`
	// Reported rather than primary record
	Reported *bool `json:"reported,omitempty"`
	// Extension for Reported
	ReportedExt *Element `json:"_reported,omitempty"`
	// Desired kind of performer of the medication administration
	PerformerType *CodeableConcept `json:"performerType,omitempty"`
	// Intended performer of administration
	Performer []Reference `json:"performer,omitempty"`
	// Intended type of device for the administration
	Device []CodeableReference `json:"device,omitempty"`
	// Person who entered the request
	Recorder *Reference `json:"recorder,omitempty"`
	// Reason or indication for ordering or not ordering the medication
	Reason []CodeableReference `json:"reason,omitempty"`
	// Overall pattern of medication administration
	CourseOfTherapyType *CodeableConcept `json:"courseOfTherapyType,omitempty"`
	// Associated insurance coverage
	Insurance []Reference `json:"insurance,omitempty"`
	// Information about the prescription
	Note []Annotation `json:"note,omitempty"`
	// Full representation of the dosage instructions
	RenderedDosageInstruction *string `json:"renderedDosageInstruction,omitempty"`
	// Extension for RenderedDosageInstruction
	RenderedDosageInstructionExt *Element `json:"_renderedDosageInstruction,omitempty"`
	// Period over which the medication is to be taken
	EffectiveDosePeriod *Period `json:"effectiveDosePeriod,omitempty"`
	// Specific instructions for how the medication should be taken
	DosageInstruction []Dosage `json:"dosageInstruction,omitempty"`
	// Medication supply authorization
	DispenseRequest *MedicationRequestDispenseRequest `json:"dispenseRequest,omitempty"`
	// Any restrictions on medication substitution
	Substitution *MedicationRequestSubstitution `json:"substitution,omitempty"`
	// A list of events of interest in the lifecycle
	EventHistory []Reference `json:"eventHistory,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *MedicationRequest) GetResourceType() string {
	return "MedicationRequest"
}

// GetId returns the resource's logical ID.
func (r *MedicationRequest) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *MedicationRequest) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *MedicationRequest) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *MedicationRequest) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *MedicationRequest) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *MedicationRequest) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *MedicationRequest) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *MedicationRequest) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *MedicationRequest) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r MedicationRequest) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicationRequest"
	type Alias MedicationRequest
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *MedicationRequest) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias MedicationRequest
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
