// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// SubstanceNucleicAcid represents FHIR SubstanceNucleicAcid.
type SubstanceNucleicAcid struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// The type of the sequence shall be specified based on a controlled vocabulary
	SequenceType *CodeableConcept `json:"sequenceType,omitempty"`
	// The number of linear sequences of nucleotides linked through phosphodiester bonds shall be described. Subunits would be strands of nucleic acids that are tightly associated typically through Watson-Crick base pairing. NOTE: If not specified in the reference source, the assumption is that there is 1 subunit
	NumberOfSubunits *int `json:"numberOfSubunits,omitempty"`
	// Extension for NumberOfSubunits
	NumberOfSubunitsExt *Element `json:"_numberOfSubunits,omitempty"`
	// The area of hybridisation shall be described if applicable for double stranded RNA or DNA. The number associated with the subunit followed by the number associated to the residue shall be specified in increasing order. The underscore “” shall be used as separator as follows: “Subunitnumber Residue”
	AreaOfHybridisation *string `json:"areaOfHybridisation,omitempty"`
	// Extension for AreaOfHybridisation
	AreaOfHybridisationExt *Element `json:"_areaOfHybridisation,omitempty"`
	// (TBC)
	OligoNucleotideType *CodeableConcept `json:"oligoNucleotideType,omitempty"`
	// Subunits are listed in order of decreasing length; sequences of the same length will be ordered by molecular weight; subunits that have identical sequences will be repeated multiple times
	Subunit []SubstanceNucleicAcidSubunit `json:"subunit,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *SubstanceNucleicAcid) GetResourceType() string {
	return "SubstanceNucleicAcid"
}

// GetId returns the resource's logical ID.
func (r *SubstanceNucleicAcid) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *SubstanceNucleicAcid) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *SubstanceNucleicAcid) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *SubstanceNucleicAcid) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *SubstanceNucleicAcid) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *SubstanceNucleicAcid) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *SubstanceNucleicAcid) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *SubstanceNucleicAcid) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *SubstanceNucleicAcid) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r SubstanceNucleicAcid) MarshalJSON() ([]byte, error) {
	r.ResourceType = "SubstanceNucleicAcid"
	type Alias SubstanceNucleicAcid
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *SubstanceNucleicAcid) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias SubstanceNucleicAcid
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
