// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r5

package r5

import (
	"encoding/json"
	"fmt"
)

// SpecimenDefinition represents FHIR SpecimenDefinition.
type SpecimenDefinition struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Logical canonical URL to reference this SpecimenDefinition (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Business identifier
	Identifier *Identifier `json:"identifier,omitempty"`
	// Business version of the SpecimenDefinition
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// How to compare versions
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *Element `json:"_versionAlgorithmString,omitempty"`
	// How to compare versions
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty"`
	// Name for this {{title}} (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Name for this SpecimenDefinition (Human friendly)
	Title *string `json:"title,omitempty"`
	// Extension for Title
	TitleExt *Element `json:"_title,omitempty"`
	// Based on FHIR definition of another SpecimenDefinition
	DerivedFromCanonical []string `json:"derivedFromCanonical,omitempty"`
	// Extension for DerivedFromCanonical
	DerivedFromCanonicalExt []Element `json:"_derivedFromCanonical,omitempty"`
	// Based on external definition
	DerivedFromUri []string `json:"derivedFromUri,omitempty"`
	// Extension for DerivedFromUri
	DerivedFromUriExt []Element `json:"_derivedFromUri,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// If this SpecimenDefinition is not for real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Type of subject for specimen collection
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty"`
	// Type of subject for specimen collection
	SubjectReference *Reference `json:"subjectReference,omitempty"`
	// Date status first applied
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// The name of the individual or organization that published the SpecimenDefinition
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the SpecimenDefinition
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Content intends to support these contexts
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction for this SpecimenDefinition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this SpecimenDefinition is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty"`
	// Extension for Copyright
	CopyrightExt *Element `json:"_copyright,omitempty"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *Element `json:"_copyrightLabel,omitempty"`
	// When SpecimenDefinition was approved by publisher
	ApprovalDate *string `json:"approvalDate,omitempty"`
	// Extension for ApprovalDate
	ApprovalDateExt *Element `json:"_approvalDate,omitempty"`
	// The date on which the asset content was last reviewed by the publisher
	LastReviewDate *string `json:"lastReviewDate,omitempty"`
	// Extension for LastReviewDate
	LastReviewDateExt *Element `json:"_lastReviewDate,omitempty"`
	// The effective date range for the SpecimenDefinition
	EffectivePeriod *Period `json:"effectivePeriod,omitempty"`
	// Kind of material to collect
	TypeCollected *CodeableConcept `json:"typeCollected,omitempty"`
	// Patient preparation for collection
	PatientPreparation []CodeableConcept `json:"patientPreparation,omitempty"`
	// Time aspect for collection
	TimeAspect *string `json:"timeAspect,omitempty"`
	// Extension for TimeAspect
	TimeAspectExt *Element `json:"_timeAspect,omitempty"`
	// Specimen collection procedure
	Collection []CodeableConcept `json:"collection,omitempty"`
	// Specimen in container intended for testing by lab
	TypeTested []SpecimenDefinitionTypeTested `json:"typeTested,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *SpecimenDefinition) GetResourceType() string {
	return "SpecimenDefinition"
}

// GetId returns the resource's logical ID.
func (r *SpecimenDefinition) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *SpecimenDefinition) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *SpecimenDefinition) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *SpecimenDefinition) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *SpecimenDefinition) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *SpecimenDefinition) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *SpecimenDefinition) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *SpecimenDefinition) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *SpecimenDefinition) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r SpecimenDefinition) MarshalJSON() ([]byte, error) {
	r.ResourceType = "SpecimenDefinition"
	type Alias SpecimenDefinition
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *SpecimenDefinition) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias SpecimenDefinition
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
