// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r4

package r4

// EvidenceVariableCharacteristic represents the EvidenceVariable.characteristic backbone element.
// What defines the members of the evidence element
type EvidenceVariableCharacteristic struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Natural language description of the characteristic
	Description *string `json:"description,omitempty"`
	// What code or expression defines members?
	DefinitionReference *Reference `json:"definitionReference,omitempty"`
	// What code or expression defines members?
	DefinitionCanonical *string `json:"definitionCanonical,omitempty"`
	// Extension for DefinitionCanonical
	DefinitionCanonicalExt *Element `json:"_definitionCanonical,omitempty"`
	// What code or expression defines members?
	DefinitionCodeableConcept *CodeableConcept `json:"definitionCodeableConcept,omitempty"`
	// What code or expression defines members?
	DefinitionExpression *Expression `json:"definitionExpression,omitempty"`
	// What code or expression defines members?
	DefinitionDataRequirement *DataRequirement `json:"definitionDataRequirement,omitempty"`
	// What code or expression defines members?
	DefinitionTriggerDefinition *TriggerDefinition `json:"definitionTriggerDefinition,omitempty"`
	// What code/value pairs define members?
	UsageContext []UsageContext `json:"usageContext,omitempty"`
	// Whether the characteristic includes or excludes members
	Exclude *bool `json:"exclude,omitempty"`
	// What time period do participants cover
	ParticipantEffectiveDateTime *string `json:"participantEffectiveDateTime,omitempty"`
	// Extension for ParticipantEffectiveDateTime
	ParticipantEffectiveDateTimeExt *Element `json:"_participantEffectiveDateTime,omitempty"`
	// What time period do participants cover
	ParticipantEffectivePeriod *Period `json:"participantEffectivePeriod,omitempty"`
	// What time period do participants cover
	ParticipantEffectiveDuration *Duration `json:"participantEffectiveDuration,omitempty"`
	// What time period do participants cover
	ParticipantEffectiveTiming *Timing `json:"participantEffectiveTiming,omitempty"`
	// Observation time from study start
	TimeFromStart *Duration `json:"timeFromStart,omitempty"`
	// mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median
	GroupMeasure *GroupMeasure `json:"groupMeasure,omitempty"`
}
