// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r4

package r4

// DetectedIssueEvidence represents the DetectedIssue.evidence backbone element.
// Supporting evidence
type DetectedIssueEvidence struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Manifestation
	Code []CodeableConcept `json:"code,omitempty"`
	// Supporting information
	Detail []Reference `json:"detail,omitempty"`
}

// DetectedIssueMitigation represents the DetectedIssue.mitigation backbone element.
// Step taken to address
type DetectedIssueMitigation struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// What mitigation?
	Action CodeableConcept `json:"action,omitempty"`
	// Date committed
	Date *string `json:"date,omitempty"`
	// Who is committing?
	Author *Reference `json:"author,omitempty"`
}
