// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r4

package r4

// AuditEventAgent represents the AuditEvent.agent backbone element.
// Actor involved in the event
type AuditEventAgent struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// How agent participated
	Type *CodeableConcept `json:"type,omitempty"`
	// Agent role in the event
	Role []CodeableConcept `json:"role,omitempty"`
	// Identifier of who
	Who *Reference `json:"who,omitempty"`
	// Alternative User identity
	AltId *string `json:"altId,omitempty"`
	// Human friendly name for the agent
	Name *string `json:"name,omitempty"`
	// Whether user is initiator
	Requestor *bool `json:"requestor,omitempty"`
	// Where
	Location *Reference `json:"location,omitempty"`
	// Policy that authorized event
	Policy []string `json:"policy,omitempty"`
	// Type of media
	Media *Coding `json:"media,omitempty"`
	// Logical network location for application activity
	Network *AuditEventAgentNetwork `json:"network,omitempty"`
	// Reason given for this user
	PurposeOfUse []CodeableConcept `json:"purposeOfUse,omitempty"`
}

// AuditEventAgentNetwork represents the AuditEvent.agent.network backbone element.
// Logical network location for application activity
type AuditEventAgentNetwork struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifier for the network access point of the user device
	Address *string `json:"address,omitempty"`
	// The type of network access point
	Type *AuditEventAgentNetworkType `json:"type,omitempty"`
}

// AuditEventEntity represents the AuditEvent.entity backbone element.
// Data or objects used
type AuditEventEntity struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Specific instance of resource
	What *Reference `json:"what,omitempty"`
	// Type of entity involved
	Type *Coding `json:"type,omitempty"`
	// What role the entity played
	Role *Coding `json:"role,omitempty"`
	// Life-cycle stage for the entity
	Lifecycle *Coding `json:"lifecycle,omitempty"`
	// Security labels on the entity
	SecurityLabel []Coding `json:"securityLabel,omitempty"`
	// Descriptor for entity
	Name *string `json:"name,omitempty"`
	// Descriptive text
	Description *string `json:"description,omitempty"`
	// Query parameters
	Query *string `json:"query,omitempty"`
	// Additional Information about the entity
	Detail []AuditEventEntityDetail `json:"detail,omitempty"`
}

// AuditEventEntityDetail represents the AuditEvent.entity.detail backbone element.
// Additional Information about the entity
type AuditEventEntityDetail struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Name of the property
	Type *string `json:"type,omitempty"`
	// Property value
	ValueString *string `json:"valueString,omitempty"`
	// Extension for ValueString
	ValueStringExt *Element `json:"_valueString,omitempty"`
	// Property value
	ValueBase64Binary *string `json:"valueBase64Binary,omitempty"`
	// Extension for ValueBase64Binary
	ValueBase64BinaryExt *Element `json:"_valueBase64Binary,omitempty"`
}

// AuditEventSource represents the AuditEvent.source backbone element.
// Audit Event Reporter
type AuditEventSource struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Logical source location within the enterprise
	Site *string `json:"site,omitempty"`
	// The identity of source detecting the event
	Observer Reference `json:"observer,omitempty"`
	// The type of source where event originated
	Type []Coding `json:"type,omitempty"`
}
