// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4

package r4

// =============================================================================
// Medication - Fluent Builder
// =============================================================================

// MedicationBuilder provides a fluent API for constructing Medication resources.
type MedicationBuilder struct {
	medication *Medication
}

// NewMedicationBuilder creates a new MedicationBuilder.
func NewMedicationBuilder() *MedicationBuilder {
	return &MedicationBuilder{
		medication: &Medication{},
	}
}

// Build returns the constructed Medication resource.
func (b *MedicationBuilder) Build() *Medication {
	return b.medication
}

// SetId sets the Id field.
func (b *MedicationBuilder) SetId(v string) *MedicationBuilder {
	b.medication.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *MedicationBuilder) SetMeta(v Meta) *MedicationBuilder {
	b.medication.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *MedicationBuilder) SetImplicitRules(v string) *MedicationBuilder {
	b.medication.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *MedicationBuilder) SetLanguage(v string) *MedicationBuilder {
	b.medication.Language = &v
	return b
}

// SetText sets the Text field.
func (b *MedicationBuilder) SetText(v Narrative) *MedicationBuilder {
	b.medication.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *MedicationBuilder) AddContained(v Resource) *MedicationBuilder {
	b.medication.Contained = append(b.medication.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *MedicationBuilder) AddExtension(v Extension) *MedicationBuilder {
	b.medication.Extension = append(b.medication.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *MedicationBuilder) AddModifierExtension(v Extension) *MedicationBuilder {
	b.medication.ModifierExtension = append(b.medication.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *MedicationBuilder) AddIdentifier(v Identifier) *MedicationBuilder {
	b.medication.Identifier = append(b.medication.Identifier, v)
	return b
}

// SetCode sets the Code field.
func (b *MedicationBuilder) SetCode(v CodeableConcept) *MedicationBuilder {
	b.medication.Code = &v
	return b
}

// SetStatus sets the Status field.
func (b *MedicationBuilder) SetStatus(v MedicationStatusCodes) *MedicationBuilder {
	b.medication.Status = &v
	return b
}

// SetManufacturer sets the Manufacturer field.
func (b *MedicationBuilder) SetManufacturer(v Reference) *MedicationBuilder {
	b.medication.Manufacturer = &v
	return b
}

// SetForm sets the Form field.
func (b *MedicationBuilder) SetForm(v CodeableConcept) *MedicationBuilder {
	b.medication.Form = &v
	return b
}

// SetAmount sets the Amount field.
func (b *MedicationBuilder) SetAmount(v Ratio) *MedicationBuilder {
	b.medication.Amount = &v
	return b
}

// AddIngredient adds a Ingredient element.
func (b *MedicationBuilder) AddIngredient(v MedicationIngredient) *MedicationBuilder {
	b.medication.Ingredient = append(b.medication.Ingredient, v)
	return b
}

// SetBatch sets the Batch field.
func (b *MedicationBuilder) SetBatch(v MedicationBatch) *MedicationBuilder {
	b.medication.Batch = &v
	return b
}
