// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4

package r4

// =============================================================================
// OperationDefinition - Fluent Builder
// =============================================================================

// OperationDefinitionBuilder provides a fluent API for constructing OperationDefinition resources.
type OperationDefinitionBuilder struct {
	operationDefinition *OperationDefinition
}

// NewOperationDefinitionBuilder creates a new OperationDefinitionBuilder.
func NewOperationDefinitionBuilder() *OperationDefinitionBuilder {
	return &OperationDefinitionBuilder{
		operationDefinition: &OperationDefinition{},
	}
}

// Build returns the constructed OperationDefinition resource.
func (b *OperationDefinitionBuilder) Build() *OperationDefinition {
	return b.operationDefinition
}

// SetId sets the Id field.
func (b *OperationDefinitionBuilder) SetId(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *OperationDefinitionBuilder) SetMeta(v Meta) *OperationDefinitionBuilder {
	b.operationDefinition.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *OperationDefinitionBuilder) SetImplicitRules(v string) *OperationDefinitionBuilder {
	b.operationDefinition.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *OperationDefinitionBuilder) SetLanguage(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Language = &v
	return b
}

// SetText sets the Text field.
func (b *OperationDefinitionBuilder) SetText(v Narrative) *OperationDefinitionBuilder {
	b.operationDefinition.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *OperationDefinitionBuilder) AddContained(v Resource) *OperationDefinitionBuilder {
	b.operationDefinition.Contained = append(b.operationDefinition.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *OperationDefinitionBuilder) AddExtension(v Extension) *OperationDefinitionBuilder {
	b.operationDefinition.Extension = append(b.operationDefinition.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *OperationDefinitionBuilder) AddModifierExtension(v Extension) *OperationDefinitionBuilder {
	b.operationDefinition.ModifierExtension = append(b.operationDefinition.ModifierExtension, v)
	return b
}

// SetUrl sets the Url field.
func (b *OperationDefinitionBuilder) SetUrl(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Url = &v
	return b
}

// SetVersion sets the Version field.
func (b *OperationDefinitionBuilder) SetVersion(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Version = &v
	return b
}

// SetName sets the Name field.
func (b *OperationDefinitionBuilder) SetName(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Name = &v
	return b
}

// SetTitle sets the Title field.
func (b *OperationDefinitionBuilder) SetTitle(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Title = &v
	return b
}

// SetStatus sets the Status field.
func (b *OperationDefinitionBuilder) SetStatus(v PublicationStatus) *OperationDefinitionBuilder {
	b.operationDefinition.Status = &v
	return b
}

// SetKind sets the Kind field.
func (b *OperationDefinitionBuilder) SetKind(v OperationKind) *OperationDefinitionBuilder {
	b.operationDefinition.Kind = &v
	return b
}

// SetExperimental sets the Experimental field.
func (b *OperationDefinitionBuilder) SetExperimental(v bool) *OperationDefinitionBuilder {
	b.operationDefinition.Experimental = &v
	return b
}

// SetDate sets the Date field.
func (b *OperationDefinitionBuilder) SetDate(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Date = &v
	return b
}

// SetPublisher sets the Publisher field.
func (b *OperationDefinitionBuilder) SetPublisher(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Publisher = &v
	return b
}

// AddContact adds a Contact element.
func (b *OperationDefinitionBuilder) AddContact(v ContactDetail) *OperationDefinitionBuilder {
	b.operationDefinition.Contact = append(b.operationDefinition.Contact, v)
	return b
}

// SetDescription sets the Description field.
func (b *OperationDefinitionBuilder) SetDescription(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Description = &v
	return b
}

// AddUseContext adds a UseContext element.
func (b *OperationDefinitionBuilder) AddUseContext(v UsageContext) *OperationDefinitionBuilder {
	b.operationDefinition.UseContext = append(b.operationDefinition.UseContext, v)
	return b
}

// AddJurisdiction adds a Jurisdiction element.
func (b *OperationDefinitionBuilder) AddJurisdiction(v CodeableConcept) *OperationDefinitionBuilder {
	b.operationDefinition.Jurisdiction = append(b.operationDefinition.Jurisdiction, v)
	return b
}

// SetPurpose sets the Purpose field.
func (b *OperationDefinitionBuilder) SetPurpose(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Purpose = &v
	return b
}

// SetAffectsState sets the AffectsState field.
func (b *OperationDefinitionBuilder) SetAffectsState(v bool) *OperationDefinitionBuilder {
	b.operationDefinition.AffectsState = &v
	return b
}

// SetCode sets the Code field.
func (b *OperationDefinitionBuilder) SetCode(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Code = &v
	return b
}

// SetComment sets the Comment field.
func (b *OperationDefinitionBuilder) SetComment(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Comment = &v
	return b
}

// SetBase sets the Base field.
func (b *OperationDefinitionBuilder) SetBase(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Base = &v
	return b
}

// AddResource adds a Resource element.
func (b *OperationDefinitionBuilder) AddResource(v string) *OperationDefinitionBuilder {
	b.operationDefinition.Resource = append(b.operationDefinition.Resource, v)
	return b
}

// SetSystem sets the System field.
func (b *OperationDefinitionBuilder) SetSystem(v bool) *OperationDefinitionBuilder {
	b.operationDefinition.System = &v
	return b
}

// SetType sets the Type field.
func (b *OperationDefinitionBuilder) SetType(v bool) *OperationDefinitionBuilder {
	b.operationDefinition.Type = &v
	return b
}

// SetInstance sets the Instance field.
func (b *OperationDefinitionBuilder) SetInstance(v bool) *OperationDefinitionBuilder {
	b.operationDefinition.Instance = &v
	return b
}

// SetInputProfile sets the InputProfile field.
func (b *OperationDefinitionBuilder) SetInputProfile(v string) *OperationDefinitionBuilder {
	b.operationDefinition.InputProfile = &v
	return b
}

// SetOutputProfile sets the OutputProfile field.
func (b *OperationDefinitionBuilder) SetOutputProfile(v string) *OperationDefinitionBuilder {
	b.operationDefinition.OutputProfile = &v
	return b
}

// AddParameter adds a Parameter element.
func (b *OperationDefinitionBuilder) AddParameter(v OperationDefinitionParameter) *OperationDefinitionBuilder {
	b.operationDefinition.Parameter = append(b.operationDefinition.Parameter, v)
	return b
}

// AddOverload adds a Overload element.
func (b *OperationDefinitionBuilder) AddOverload(v OperationDefinitionOverload) *OperationDefinitionBuilder {
	b.operationDefinition.Overload = append(b.operationDefinition.Overload, v)
	return b
}
