// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4

package r4

// =============================================================================
// Media - Fluent Builder
// =============================================================================

// MediaBuilder provides a fluent API for constructing Media resources.
type MediaBuilder struct {
	media *Media
}

// NewMediaBuilder creates a new MediaBuilder.
func NewMediaBuilder() *MediaBuilder {
	return &MediaBuilder{
		media: &Media{},
	}
}

// Build returns the constructed Media resource.
func (b *MediaBuilder) Build() *Media {
	return b.media
}

// SetId sets the Id field.
func (b *MediaBuilder) SetId(v string) *MediaBuilder {
	b.media.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *MediaBuilder) SetMeta(v Meta) *MediaBuilder {
	b.media.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *MediaBuilder) SetImplicitRules(v string) *MediaBuilder {
	b.media.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *MediaBuilder) SetLanguage(v string) *MediaBuilder {
	b.media.Language = &v
	return b
}

// SetText sets the Text field.
func (b *MediaBuilder) SetText(v Narrative) *MediaBuilder {
	b.media.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *MediaBuilder) AddContained(v Resource) *MediaBuilder {
	b.media.Contained = append(b.media.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *MediaBuilder) AddExtension(v Extension) *MediaBuilder {
	b.media.Extension = append(b.media.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *MediaBuilder) AddModifierExtension(v Extension) *MediaBuilder {
	b.media.ModifierExtension = append(b.media.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *MediaBuilder) AddIdentifier(v Identifier) *MediaBuilder {
	b.media.Identifier = append(b.media.Identifier, v)
	return b
}

// AddBasedOn adds a BasedOn element.
func (b *MediaBuilder) AddBasedOn(v Reference) *MediaBuilder {
	b.media.BasedOn = append(b.media.BasedOn, v)
	return b
}

// AddPartOf adds a PartOf element.
func (b *MediaBuilder) AddPartOf(v Reference) *MediaBuilder {
	b.media.PartOf = append(b.media.PartOf, v)
	return b
}

// SetStatus sets the Status field.
func (b *MediaBuilder) SetStatus(v EventStatus) *MediaBuilder {
	b.media.Status = &v
	return b
}

// SetType sets the Type field.
func (b *MediaBuilder) SetType(v CodeableConcept) *MediaBuilder {
	b.media.Type = &v
	return b
}

// SetModality sets the Modality field.
func (b *MediaBuilder) SetModality(v CodeableConcept) *MediaBuilder {
	b.media.Modality = &v
	return b
}

// SetView sets the View field.
func (b *MediaBuilder) SetView(v CodeableConcept) *MediaBuilder {
	b.media.View = &v
	return b
}

// SetSubject sets the Subject field.
func (b *MediaBuilder) SetSubject(v Reference) *MediaBuilder {
	b.media.Subject = &v
	return b
}

// SetEncounter sets the Encounter field.
func (b *MediaBuilder) SetEncounter(v Reference) *MediaBuilder {
	b.media.Encounter = &v
	return b
}

// SetCreatedDateTime sets the CreatedDateTime field.
func (b *MediaBuilder) SetCreatedDateTime(v string) *MediaBuilder {
	b.media.CreatedDateTime = &v
	return b
}

// SetCreatedDateTimeExt sets the CreatedDateTimeExt field.
func (b *MediaBuilder) SetCreatedDateTimeExt(v Element) *MediaBuilder {
	b.media.CreatedDateTimeExt = &v
	return b
}

// SetCreatedPeriod sets the CreatedPeriod field.
func (b *MediaBuilder) SetCreatedPeriod(v Period) *MediaBuilder {
	b.media.CreatedPeriod = &v
	return b
}

// SetIssued sets the Issued field.
func (b *MediaBuilder) SetIssued(v string) *MediaBuilder {
	b.media.Issued = &v
	return b
}

// SetOperator sets the Operator field.
func (b *MediaBuilder) SetOperator(v Reference) *MediaBuilder {
	b.media.Operator = &v
	return b
}

// AddReasonCode adds a ReasonCode element.
func (b *MediaBuilder) AddReasonCode(v CodeableConcept) *MediaBuilder {
	b.media.ReasonCode = append(b.media.ReasonCode, v)
	return b
}

// SetBodySite sets the BodySite field.
func (b *MediaBuilder) SetBodySite(v CodeableConcept) *MediaBuilder {
	b.media.BodySite = &v
	return b
}

// SetDeviceName sets the DeviceName field.
func (b *MediaBuilder) SetDeviceName(v string) *MediaBuilder {
	b.media.DeviceName = &v
	return b
}

// SetDevice sets the Device field.
func (b *MediaBuilder) SetDevice(v Reference) *MediaBuilder {
	b.media.Device = &v
	return b
}

// SetHeight sets the Height field.
func (b *MediaBuilder) SetHeight(v uint32) *MediaBuilder {
	b.media.Height = &v
	return b
}

// SetWidth sets the Width field.
func (b *MediaBuilder) SetWidth(v uint32) *MediaBuilder {
	b.media.Width = &v
	return b
}

// SetFrames sets the Frames field.
func (b *MediaBuilder) SetFrames(v uint32) *MediaBuilder {
	b.media.Frames = &v
	return b
}

// SetDuration sets the Duration field.
func (b *MediaBuilder) SetDuration(v float64) *MediaBuilder {
	b.media.Duration = &v
	return b
}

// SetContent sets the Content field.
func (b *MediaBuilder) SetContent(v Attachment) *MediaBuilder {
	b.media.Content = v
	return b
}

// AddNote adds a Note element.
func (b *MediaBuilder) AddNote(v Annotation) *MediaBuilder {
	b.media.Note = append(b.media.Note, v)
	return b
}
