// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4

package r4

// =============================================================================
// Slot - Fluent Builder
// =============================================================================

// SlotBuilder provides a fluent API for constructing Slot resources.
type SlotBuilder struct {
	slot *Slot
}

// NewSlotBuilder creates a new SlotBuilder.
func NewSlotBuilder() *SlotBuilder {
	return &SlotBuilder{
		slot: &Slot{},
	}
}

// Build returns the constructed Slot resource.
func (b *SlotBuilder) Build() *Slot {
	return b.slot
}

// SetId sets the Id field.
func (b *SlotBuilder) SetId(v string) *SlotBuilder {
	b.slot.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *SlotBuilder) SetMeta(v Meta) *SlotBuilder {
	b.slot.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *SlotBuilder) SetImplicitRules(v string) *SlotBuilder {
	b.slot.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *SlotBuilder) SetLanguage(v string) *SlotBuilder {
	b.slot.Language = &v
	return b
}

// SetText sets the Text field.
func (b *SlotBuilder) SetText(v Narrative) *SlotBuilder {
	b.slot.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *SlotBuilder) AddContained(v Resource) *SlotBuilder {
	b.slot.Contained = append(b.slot.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *SlotBuilder) AddExtension(v Extension) *SlotBuilder {
	b.slot.Extension = append(b.slot.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *SlotBuilder) AddModifierExtension(v Extension) *SlotBuilder {
	b.slot.ModifierExtension = append(b.slot.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *SlotBuilder) AddIdentifier(v Identifier) *SlotBuilder {
	b.slot.Identifier = append(b.slot.Identifier, v)
	return b
}

// AddServiceCategory adds a ServiceCategory element.
func (b *SlotBuilder) AddServiceCategory(v CodeableConcept) *SlotBuilder {
	b.slot.ServiceCategory = append(b.slot.ServiceCategory, v)
	return b
}

// AddServiceType adds a ServiceType element.
func (b *SlotBuilder) AddServiceType(v CodeableConcept) *SlotBuilder {
	b.slot.ServiceType = append(b.slot.ServiceType, v)
	return b
}

// AddSpecialty adds a Specialty element.
func (b *SlotBuilder) AddSpecialty(v CodeableConcept) *SlotBuilder {
	b.slot.Specialty = append(b.slot.Specialty, v)
	return b
}

// SetAppointmentType sets the AppointmentType field.
func (b *SlotBuilder) SetAppointmentType(v CodeableConcept) *SlotBuilder {
	b.slot.AppointmentType = &v
	return b
}

// SetSchedule sets the Schedule field.
func (b *SlotBuilder) SetSchedule(v Reference) *SlotBuilder {
	b.slot.Schedule = v
	return b
}

// SetStatus sets the Status field.
func (b *SlotBuilder) SetStatus(v SlotStatus) *SlotBuilder {
	b.slot.Status = &v
	return b
}

// SetStart sets the Start field.
func (b *SlotBuilder) SetStart(v string) *SlotBuilder {
	b.slot.Start = &v
	return b
}

// SetEnd sets the End field.
func (b *SlotBuilder) SetEnd(v string) *SlotBuilder {
	b.slot.End = &v
	return b
}

// SetOverbooked sets the Overbooked field.
func (b *SlotBuilder) SetOverbooked(v bool) *SlotBuilder {
	b.slot.Overbooked = &v
	return b
}

// SetComment sets the Comment field.
func (b *SlotBuilder) SetComment(v string) *SlotBuilder {
	b.slot.Comment = &v
	return b
}
