// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4

package r4

// =============================================================================
// DiagnosticReport - Functional Options
// =============================================================================

// DiagnosticReportOption is a functional option for configuring a DiagnosticReport.
type DiagnosticReportOption func(*DiagnosticReport)

// NewDiagnosticReport creates a new DiagnosticReport with the given options.
func NewDiagnosticReport(opts ...DiagnosticReportOption) *DiagnosticReport {
	r := &DiagnosticReport{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithDiagnosticReportId sets the Id field.
func WithDiagnosticReportId(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Id = &v
	}
}

// WithDiagnosticReportMeta sets the Meta field.
func WithDiagnosticReportMeta(v Meta) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Meta = &v
	}
}

// WithDiagnosticReportImplicitRules sets the ImplicitRules field.
func WithDiagnosticReportImplicitRules(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.ImplicitRules = &v
	}
}

// WithDiagnosticReportLanguage sets the Language field.
func WithDiagnosticReportLanguage(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Language = &v
	}
}

// WithDiagnosticReportText sets the Text field.
func WithDiagnosticReportText(v Narrative) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Text = &v
	}
}

// WithDiagnosticReportContained adds a Contained to the DiagnosticReport.
func WithDiagnosticReportContained(v Resource) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Contained = append(r.Contained, v)
	}
}

// WithDiagnosticReportExtension adds a Extension to the DiagnosticReport.
func WithDiagnosticReportExtension(v Extension) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Extension = append(r.Extension, v)
	}
}

// WithDiagnosticReportModifierExtension adds a ModifierExtension to the DiagnosticReport.
func WithDiagnosticReportModifierExtension(v Extension) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithDiagnosticReportIdentifier adds a Identifier to the DiagnosticReport.
func WithDiagnosticReportIdentifier(v Identifier) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithDiagnosticReportBasedOn adds a BasedOn to the DiagnosticReport.
func WithDiagnosticReportBasedOn(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithDiagnosticReportStatus sets the Status field.
func WithDiagnosticReportStatus(v DiagnosticReportStatus) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Status = &v
	}
}

// WithDiagnosticReportCategory adds a Category to the DiagnosticReport.
func WithDiagnosticReportCategory(v CodeableConcept) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Category = append(r.Category, v)
	}
}

// WithDiagnosticReportCode sets the Code field.
func WithDiagnosticReportCode(v CodeableConcept) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Code = v
	}
}

// WithDiagnosticReportSubject sets the Subject field.
func WithDiagnosticReportSubject(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Subject = &v
	}
}

// WithDiagnosticReportEncounter sets the Encounter field.
func WithDiagnosticReportEncounter(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Encounter = &v
	}
}

// WithDiagnosticReportEffectiveDateTime sets the EffectiveDateTime field.
func WithDiagnosticReportEffectiveDateTime(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.EffectiveDateTime = &v
	}
}

// WithDiagnosticReportEffectiveDateTimeExt sets the EffectiveDateTimeExt field.
func WithDiagnosticReportEffectiveDateTimeExt(v Element) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.EffectiveDateTimeExt = &v
	}
}

// WithDiagnosticReportEffectivePeriod sets the EffectivePeriod field.
func WithDiagnosticReportEffectivePeriod(v Period) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.EffectivePeriod = &v
	}
}

// WithDiagnosticReportIssued sets the Issued field.
func WithDiagnosticReportIssued(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Issued = &v
	}
}

// WithDiagnosticReportPerformer adds a Performer to the DiagnosticReport.
func WithDiagnosticReportPerformer(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Performer = append(r.Performer, v)
	}
}

// WithDiagnosticReportResultsInterpreter adds a ResultsInterpreter to the DiagnosticReport.
func WithDiagnosticReportResultsInterpreter(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.ResultsInterpreter = append(r.ResultsInterpreter, v)
	}
}

// WithDiagnosticReportSpecimen adds a Specimen to the DiagnosticReport.
func WithDiagnosticReportSpecimen(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Specimen = append(r.Specimen, v)
	}
}

// WithDiagnosticReportResult adds a Result to the DiagnosticReport.
func WithDiagnosticReportResult(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Result = append(r.Result, v)
	}
}

// WithDiagnosticReportImagingStudy adds a ImagingStudy to the DiagnosticReport.
func WithDiagnosticReportImagingStudy(v Reference) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.ImagingStudy = append(r.ImagingStudy, v)
	}
}

// WithDiagnosticReportMedia adds a Media to the DiagnosticReport.
func WithDiagnosticReportMedia(v DiagnosticReportMedia) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Media = append(r.Media, v)
	}
}

// WithDiagnosticReportConclusion sets the Conclusion field.
func WithDiagnosticReportConclusion(v string) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.Conclusion = &v
	}
}

// WithDiagnosticReportConclusionCode adds a ConclusionCode to the DiagnosticReport.
func WithDiagnosticReportConclusionCode(v CodeableConcept) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.ConclusionCode = append(r.ConclusionCode, v)
	}
}

// WithDiagnosticReportPresentedForm adds a PresentedForm to the DiagnosticReport.
func WithDiagnosticReportPresentedForm(v Attachment) DiagnosticReportOption {
	return func(r *DiagnosticReport) {
		r.PresentedForm = append(r.PresentedForm, v)
	}
}
