// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4

package r4

// =============================================================================
// EvidenceVariable - Functional Options
// =============================================================================

// EvidenceVariableOption is a functional option for configuring a EvidenceVariable.
type EvidenceVariableOption func(*EvidenceVariable)

// NewEvidenceVariable creates a new EvidenceVariable with the given options.
func NewEvidenceVariable(opts ...EvidenceVariableOption) *EvidenceVariable {
	r := &EvidenceVariable{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithEvidenceVariableId sets the Id field.
func WithEvidenceVariableId(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Id = &v
	}
}

// WithEvidenceVariableMeta sets the Meta field.
func WithEvidenceVariableMeta(v Meta) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Meta = &v
	}
}

// WithEvidenceVariableImplicitRules sets the ImplicitRules field.
func WithEvidenceVariableImplicitRules(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.ImplicitRules = &v
	}
}

// WithEvidenceVariableLanguage sets the Language field.
func WithEvidenceVariableLanguage(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Language = &v
	}
}

// WithEvidenceVariableText sets the Text field.
func WithEvidenceVariableText(v Narrative) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Text = &v
	}
}

// WithEvidenceVariableContained adds a Contained to the EvidenceVariable.
func WithEvidenceVariableContained(v Resource) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Contained = append(r.Contained, v)
	}
}

// WithEvidenceVariableExtension adds a Extension to the EvidenceVariable.
func WithEvidenceVariableExtension(v Extension) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Extension = append(r.Extension, v)
	}
}

// WithEvidenceVariableModifierExtension adds a ModifierExtension to the EvidenceVariable.
func WithEvidenceVariableModifierExtension(v Extension) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithEvidenceVariableUrl sets the Url field.
func WithEvidenceVariableUrl(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Url = &v
	}
}

// WithEvidenceVariableIdentifier adds a Identifier to the EvidenceVariable.
func WithEvidenceVariableIdentifier(v Identifier) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithEvidenceVariableVersion sets the Version field.
func WithEvidenceVariableVersion(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Version = &v
	}
}

// WithEvidenceVariableName sets the Name field.
func WithEvidenceVariableName(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Name = &v
	}
}

// WithEvidenceVariableTitle sets the Title field.
func WithEvidenceVariableTitle(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Title = &v
	}
}

// WithEvidenceVariableShortTitle sets the ShortTitle field.
func WithEvidenceVariableShortTitle(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.ShortTitle = &v
	}
}

// WithEvidenceVariableSubtitle sets the Subtitle field.
func WithEvidenceVariableSubtitle(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Subtitle = &v
	}
}

// WithEvidenceVariableStatus sets the Status field.
func WithEvidenceVariableStatus(v PublicationStatus) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Status = &v
	}
}

// WithEvidenceVariableDate sets the Date field.
func WithEvidenceVariableDate(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Date = &v
	}
}

// WithEvidenceVariablePublisher sets the Publisher field.
func WithEvidenceVariablePublisher(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Publisher = &v
	}
}

// WithEvidenceVariableContact adds a Contact to the EvidenceVariable.
func WithEvidenceVariableContact(v ContactDetail) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Contact = append(r.Contact, v)
	}
}

// WithEvidenceVariableDescription sets the Description field.
func WithEvidenceVariableDescription(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Description = &v
	}
}

// WithEvidenceVariableNote adds a Note to the EvidenceVariable.
func WithEvidenceVariableNote(v Annotation) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Note = append(r.Note, v)
	}
}

// WithEvidenceVariableUseContext adds a UseContext to the EvidenceVariable.
func WithEvidenceVariableUseContext(v UsageContext) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.UseContext = append(r.UseContext, v)
	}
}

// WithEvidenceVariableJurisdiction adds a Jurisdiction to the EvidenceVariable.
func WithEvidenceVariableJurisdiction(v CodeableConcept) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Jurisdiction = append(r.Jurisdiction, v)
	}
}

// WithEvidenceVariableCopyright sets the Copyright field.
func WithEvidenceVariableCopyright(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Copyright = &v
	}
}

// WithEvidenceVariableApprovalDate sets the ApprovalDate field.
func WithEvidenceVariableApprovalDate(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.ApprovalDate = &v
	}
}

// WithEvidenceVariableLastReviewDate sets the LastReviewDate field.
func WithEvidenceVariableLastReviewDate(v string) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.LastReviewDate = &v
	}
}

// WithEvidenceVariableEffectivePeriod sets the EffectivePeriod field.
func WithEvidenceVariableEffectivePeriod(v Period) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.EffectivePeriod = &v
	}
}

// WithEvidenceVariableTopic adds a Topic to the EvidenceVariable.
func WithEvidenceVariableTopic(v CodeableConcept) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Topic = append(r.Topic, v)
	}
}

// WithEvidenceVariableAuthor adds a Author to the EvidenceVariable.
func WithEvidenceVariableAuthor(v ContactDetail) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Author = append(r.Author, v)
	}
}

// WithEvidenceVariableEditor adds a Editor to the EvidenceVariable.
func WithEvidenceVariableEditor(v ContactDetail) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Editor = append(r.Editor, v)
	}
}

// WithEvidenceVariableReviewer adds a Reviewer to the EvidenceVariable.
func WithEvidenceVariableReviewer(v ContactDetail) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Reviewer = append(r.Reviewer, v)
	}
}

// WithEvidenceVariableEndorser adds a Endorser to the EvidenceVariable.
func WithEvidenceVariableEndorser(v ContactDetail) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Endorser = append(r.Endorser, v)
	}
}

// WithEvidenceVariableRelatedArtifact adds a RelatedArtifact to the EvidenceVariable.
func WithEvidenceVariableRelatedArtifact(v RelatedArtifact) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.RelatedArtifact = append(r.RelatedArtifact, v)
	}
}

// WithEvidenceVariableType sets the Type field.
func WithEvidenceVariableType(v EvidenceVariableType) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Type = &v
	}
}

// WithEvidenceVariableCharacteristic adds a Characteristic to the EvidenceVariable.
func WithEvidenceVariableCharacteristic(v EvidenceVariableCharacteristic) EvidenceVariableOption {
	return func(r *EvidenceVariable) {
		r.Characteristic = append(r.Characteristic, v)
	}
}
