// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4

package r4

// =============================================================================
// Procedure - Functional Options
// =============================================================================

// ProcedureOption is a functional option for configuring a Procedure.
type ProcedureOption func(*Procedure)

// NewProcedure creates a new Procedure with the given options.
func NewProcedure(opts ...ProcedureOption) *Procedure {
	r := &Procedure{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithProcedureId sets the Id field.
func WithProcedureId(v string) ProcedureOption {
	return func(r *Procedure) {
		r.Id = &v
	}
}

// WithProcedureMeta sets the Meta field.
func WithProcedureMeta(v Meta) ProcedureOption {
	return func(r *Procedure) {
		r.Meta = &v
	}
}

// WithProcedureImplicitRules sets the ImplicitRules field.
func WithProcedureImplicitRules(v string) ProcedureOption {
	return func(r *Procedure) {
		r.ImplicitRules = &v
	}
}

// WithProcedureLanguage sets the Language field.
func WithProcedureLanguage(v string) ProcedureOption {
	return func(r *Procedure) {
		r.Language = &v
	}
}

// WithProcedureText sets the Text field.
func WithProcedureText(v Narrative) ProcedureOption {
	return func(r *Procedure) {
		r.Text = &v
	}
}

// WithProcedureContained adds a Contained to the Procedure.
func WithProcedureContained(v Resource) ProcedureOption {
	return func(r *Procedure) {
		r.Contained = append(r.Contained, v)
	}
}

// WithProcedureExtension adds a Extension to the Procedure.
func WithProcedureExtension(v Extension) ProcedureOption {
	return func(r *Procedure) {
		r.Extension = append(r.Extension, v)
	}
}

// WithProcedureModifierExtension adds a ModifierExtension to the Procedure.
func WithProcedureModifierExtension(v Extension) ProcedureOption {
	return func(r *Procedure) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithProcedureIdentifier adds a Identifier to the Procedure.
func WithProcedureIdentifier(v Identifier) ProcedureOption {
	return func(r *Procedure) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithProcedureInstantiatesCanonical adds a InstantiatesCanonical to the Procedure.
func WithProcedureInstantiatesCanonical(v string) ProcedureOption {
	return func(r *Procedure) {
		r.InstantiatesCanonical = append(r.InstantiatesCanonical, v)
	}
}

// WithProcedureInstantiatesUri adds a InstantiatesUri to the Procedure.
func WithProcedureInstantiatesUri(v string) ProcedureOption {
	return func(r *Procedure) {
		r.InstantiatesUri = append(r.InstantiatesUri, v)
	}
}

// WithProcedureBasedOn adds a BasedOn to the Procedure.
func WithProcedureBasedOn(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.BasedOn = append(r.BasedOn, v)
	}
}

// WithProcedurePartOf adds a PartOf to the Procedure.
func WithProcedurePartOf(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.PartOf = append(r.PartOf, v)
	}
}

// WithProcedureStatus sets the Status field.
func WithProcedureStatus(v EventStatus) ProcedureOption {
	return func(r *Procedure) {
		r.Status = &v
	}
}

// WithProcedureStatusReason sets the StatusReason field.
func WithProcedureStatusReason(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.StatusReason = &v
	}
}

// WithProcedureCategory sets the Category field.
func WithProcedureCategory(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.Category = &v
	}
}

// WithProcedureCode sets the Code field.
func WithProcedureCode(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.Code = &v
	}
}

// WithProcedureSubject sets the Subject field.
func WithProcedureSubject(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Subject = v
	}
}

// WithProcedureEncounter sets the Encounter field.
func WithProcedureEncounter(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Encounter = &v
	}
}

// WithProcedurePerformedDateTime sets the PerformedDateTime field.
func WithProcedurePerformedDateTime(v string) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedDateTime = &v
	}
}

// WithProcedurePerformedDateTimeExt sets the PerformedDateTimeExt field.
func WithProcedurePerformedDateTimeExt(v Element) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedDateTimeExt = &v
	}
}

// WithProcedurePerformedPeriod sets the PerformedPeriod field.
func WithProcedurePerformedPeriod(v Period) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedPeriod = &v
	}
}

// WithProcedurePerformedString sets the PerformedString field.
func WithProcedurePerformedString(v string) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedString = &v
	}
}

// WithProcedurePerformedStringExt sets the PerformedStringExt field.
func WithProcedurePerformedStringExt(v Element) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedStringExt = &v
	}
}

// WithProcedurePerformedAge sets the PerformedAge field.
func WithProcedurePerformedAge(v Age) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedAge = &v
	}
}

// WithProcedurePerformedRange sets the PerformedRange field.
func WithProcedurePerformedRange(v Range) ProcedureOption {
	return func(r *Procedure) {
		r.PerformedRange = &v
	}
}

// WithProcedureRecorder sets the Recorder field.
func WithProcedureRecorder(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Recorder = &v
	}
}

// WithProcedureAsserter sets the Asserter field.
func WithProcedureAsserter(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Asserter = &v
	}
}

// WithProcedurePerformer adds a Performer to the Procedure.
func WithProcedurePerformer(v ProcedurePerformer) ProcedureOption {
	return func(r *Procedure) {
		r.Performer = append(r.Performer, v)
	}
}

// WithProcedureLocation sets the Location field.
func WithProcedureLocation(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Location = &v
	}
}

// WithProcedureReasonCode adds a ReasonCode to the Procedure.
func WithProcedureReasonCode(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.ReasonCode = append(r.ReasonCode, v)
	}
}

// WithProcedureReasonReference adds a ReasonReference to the Procedure.
func WithProcedureReasonReference(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.ReasonReference = append(r.ReasonReference, v)
	}
}

// WithProcedureBodySite adds a BodySite to the Procedure.
func WithProcedureBodySite(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.BodySite = append(r.BodySite, v)
	}
}

// WithProcedureOutcome sets the Outcome field.
func WithProcedureOutcome(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.Outcome = &v
	}
}

// WithProcedureReport adds a Report to the Procedure.
func WithProcedureReport(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.Report = append(r.Report, v)
	}
}

// WithProcedureComplication adds a Complication to the Procedure.
func WithProcedureComplication(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.Complication = append(r.Complication, v)
	}
}

// WithProcedureComplicationDetail adds a ComplicationDetail to the Procedure.
func WithProcedureComplicationDetail(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.ComplicationDetail = append(r.ComplicationDetail, v)
	}
}

// WithProcedureFollowUp adds a FollowUp to the Procedure.
func WithProcedureFollowUp(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.FollowUp = append(r.FollowUp, v)
	}
}

// WithProcedureNote adds a Note to the Procedure.
func WithProcedureNote(v Annotation) ProcedureOption {
	return func(r *Procedure) {
		r.Note = append(r.Note, v)
	}
}

// WithProcedureFocalDevice adds a FocalDevice to the Procedure.
func WithProcedureFocalDevice(v ProcedureFocalDevice) ProcedureOption {
	return func(r *Procedure) {
		r.FocalDevice = append(r.FocalDevice, v)
	}
}

// WithProcedureUsedReference adds a UsedReference to the Procedure.
func WithProcedureUsedReference(v Reference) ProcedureOption {
	return func(r *Procedure) {
		r.UsedReference = append(r.UsedReference, v)
	}
}

// WithProcedureUsedCode adds a UsedCode to the Procedure.
func WithProcedureUsedCode(v CodeableConcept) ProcedureOption {
	return func(r *Procedure) {
		r.UsedCode = append(r.UsedCode, v)
	}
}
