// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4

package r4

// =============================================================================
// VisionPrescription - Functional Options
// =============================================================================

// VisionPrescriptionOption is a functional option for configuring a VisionPrescription.
type VisionPrescriptionOption func(*VisionPrescription)

// NewVisionPrescription creates a new VisionPrescription with the given options.
func NewVisionPrescription(opts ...VisionPrescriptionOption) *VisionPrescription {
	r := &VisionPrescription{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithVisionPrescriptionId sets the Id field.
func WithVisionPrescriptionId(v string) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Id = &v
	}
}

// WithVisionPrescriptionMeta sets the Meta field.
func WithVisionPrescriptionMeta(v Meta) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Meta = &v
	}
}

// WithVisionPrescriptionImplicitRules sets the ImplicitRules field.
func WithVisionPrescriptionImplicitRules(v string) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.ImplicitRules = &v
	}
}

// WithVisionPrescriptionLanguage sets the Language field.
func WithVisionPrescriptionLanguage(v string) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Language = &v
	}
}

// WithVisionPrescriptionText sets the Text field.
func WithVisionPrescriptionText(v Narrative) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Text = &v
	}
}

// WithVisionPrescriptionContained adds a Contained to the VisionPrescription.
func WithVisionPrescriptionContained(v Resource) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Contained = append(r.Contained, v)
	}
}

// WithVisionPrescriptionExtension adds a Extension to the VisionPrescription.
func WithVisionPrescriptionExtension(v Extension) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Extension = append(r.Extension, v)
	}
}

// WithVisionPrescriptionModifierExtension adds a ModifierExtension to the VisionPrescription.
func WithVisionPrescriptionModifierExtension(v Extension) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithVisionPrescriptionIdentifier adds a Identifier to the VisionPrescription.
func WithVisionPrescriptionIdentifier(v Identifier) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithVisionPrescriptionStatus sets the Status field.
func WithVisionPrescriptionStatus(v FinancialResourceStatusCodes) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Status = &v
	}
}

// WithVisionPrescriptionCreated sets the Created field.
func WithVisionPrescriptionCreated(v string) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Created = &v
	}
}

// WithVisionPrescriptionPatient sets the Patient field.
func WithVisionPrescriptionPatient(v Reference) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Patient = v
	}
}

// WithVisionPrescriptionEncounter sets the Encounter field.
func WithVisionPrescriptionEncounter(v Reference) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Encounter = &v
	}
}

// WithVisionPrescriptionDateWritten sets the DateWritten field.
func WithVisionPrescriptionDateWritten(v string) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.DateWritten = &v
	}
}

// WithVisionPrescriptionPrescriber sets the Prescriber field.
func WithVisionPrescriptionPrescriber(v Reference) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.Prescriber = v
	}
}

// WithVisionPrescriptionLensSpecification adds a LensSpecification to the VisionPrescription.
func WithVisionPrescriptionLensSpecification(v VisionPrescriptionLensSpecification) VisionPrescriptionOption {
	return func(r *VisionPrescription) {
		r.LensSpecification = append(r.LensSpecification, v)
	}
}
