// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4

package r4

// =============================================================================
// CoverageEligibilityResponse - Functional Options
// =============================================================================

// CoverageEligibilityResponseOption is a functional option for configuring a CoverageEligibilityResponse.
type CoverageEligibilityResponseOption func(*CoverageEligibilityResponse)

// NewCoverageEligibilityResponse creates a new CoverageEligibilityResponse with the given options.
func NewCoverageEligibilityResponse(opts ...CoverageEligibilityResponseOption) *CoverageEligibilityResponse {
	r := &CoverageEligibilityResponse{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithCoverageEligibilityResponseId sets the Id field.
func WithCoverageEligibilityResponseId(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Id = &v
	}
}

// WithCoverageEligibilityResponseMeta sets the Meta field.
func WithCoverageEligibilityResponseMeta(v Meta) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Meta = &v
	}
}

// WithCoverageEligibilityResponseImplicitRules sets the ImplicitRules field.
func WithCoverageEligibilityResponseImplicitRules(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.ImplicitRules = &v
	}
}

// WithCoverageEligibilityResponseLanguage sets the Language field.
func WithCoverageEligibilityResponseLanguage(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Language = &v
	}
}

// WithCoverageEligibilityResponseText sets the Text field.
func WithCoverageEligibilityResponseText(v Narrative) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Text = &v
	}
}

// WithCoverageEligibilityResponseContained adds a Contained to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseContained(v Resource) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Contained = append(r.Contained, v)
	}
}

// WithCoverageEligibilityResponseExtension adds a Extension to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseExtension(v Extension) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Extension = append(r.Extension, v)
	}
}

// WithCoverageEligibilityResponseModifierExtension adds a ModifierExtension to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseModifierExtension(v Extension) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithCoverageEligibilityResponseIdentifier adds a Identifier to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseIdentifier(v Identifier) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithCoverageEligibilityResponseStatus sets the Status field.
func WithCoverageEligibilityResponseStatus(v FinancialResourceStatusCodes) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Status = &v
	}
}

// WithCoverageEligibilityResponsePurpose adds a Purpose to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponsePurpose(v EligibilityResponsePurpose) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Purpose = append(r.Purpose, v)
	}
}

// WithCoverageEligibilityResponsePatient sets the Patient field.
func WithCoverageEligibilityResponsePatient(v Reference) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Patient = v
	}
}

// WithCoverageEligibilityResponseServicedDate sets the ServicedDate field.
func WithCoverageEligibilityResponseServicedDate(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.ServicedDate = &v
	}
}

// WithCoverageEligibilityResponseServicedDateExt sets the ServicedDateExt field.
func WithCoverageEligibilityResponseServicedDateExt(v Element) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.ServicedDateExt = &v
	}
}

// WithCoverageEligibilityResponseServicedPeriod sets the ServicedPeriod field.
func WithCoverageEligibilityResponseServicedPeriod(v Period) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.ServicedPeriod = &v
	}
}

// WithCoverageEligibilityResponseCreated sets the Created field.
func WithCoverageEligibilityResponseCreated(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Created = &v
	}
}

// WithCoverageEligibilityResponseRequestor sets the Requestor field.
func WithCoverageEligibilityResponseRequestor(v Reference) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Requestor = &v
	}
}

// WithCoverageEligibilityResponseRequest sets the Request field.
func WithCoverageEligibilityResponseRequest(v Reference) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Request = v
	}
}

// WithCoverageEligibilityResponseOutcome sets the Outcome field.
func WithCoverageEligibilityResponseOutcome(v ClaimProcessingCodes) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Outcome = &v
	}
}

// WithCoverageEligibilityResponseDisposition sets the Disposition field.
func WithCoverageEligibilityResponseDisposition(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Disposition = &v
	}
}

// WithCoverageEligibilityResponseInsurer sets the Insurer field.
func WithCoverageEligibilityResponseInsurer(v Reference) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Insurer = v
	}
}

// WithCoverageEligibilityResponseInsurance adds a Insurance to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseInsurance(v CoverageEligibilityResponseInsurance) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Insurance = append(r.Insurance, v)
	}
}

// WithCoverageEligibilityResponsePreAuthRef sets the PreAuthRef field.
func WithCoverageEligibilityResponsePreAuthRef(v string) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.PreAuthRef = &v
	}
}

// WithCoverageEligibilityResponseForm sets the Form field.
func WithCoverageEligibilityResponseForm(v CodeableConcept) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Form = &v
	}
}

// WithCoverageEligibilityResponseError adds a Error to the CoverageEligibilityResponse.
func WithCoverageEligibilityResponseError(v CoverageEligibilityResponseError) CoverageEligibilityResponseOption {
	return func(r *CoverageEligibilityResponse) {
		r.Error = append(r.Error, v)
	}
}
