// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (registry)
// Package: r4

package r4

import (
	"encoding/json"
	"fmt"
)

// resourceFactories maps resourceType to factory function.
var resourceFactories = map[string]func() Resource{
	"Account":                           func() Resource { return &Account{} },
	"ActivityDefinition":                func() Resource { return &ActivityDefinition{} },
	"AdverseEvent":                      func() Resource { return &AdverseEvent{} },
	"AllergyIntolerance":                func() Resource { return &AllergyIntolerance{} },
	"Appointment":                       func() Resource { return &Appointment{} },
	"AppointmentResponse":               func() Resource { return &AppointmentResponse{} },
	"AuditEvent":                        func() Resource { return &AuditEvent{} },
	"Basic":                             func() Resource { return &Basic{} },
	"Binary":                            func() Resource { return &Binary{} },
	"BiologicallyDerivedProduct":        func() Resource { return &BiologicallyDerivedProduct{} },
	"BodyStructure":                     func() Resource { return &BodyStructure{} },
	"Bundle":                            func() Resource { return &Bundle{} },
	"CapabilityStatement":               func() Resource { return &CapabilityStatement{} },
	"CarePlan":                          func() Resource { return &CarePlan{} },
	"CareTeam":                          func() Resource { return &CareTeam{} },
	"CatalogEntry":                      func() Resource { return &CatalogEntry{} },
	"ChargeItem":                        func() Resource { return &ChargeItem{} },
	"ChargeItemDefinition":              func() Resource { return &ChargeItemDefinition{} },
	"Claim":                             func() Resource { return &Claim{} },
	"ClaimResponse":                     func() Resource { return &ClaimResponse{} },
	"ClinicalImpression":                func() Resource { return &ClinicalImpression{} },
	"CodeSystem":                        func() Resource { return &CodeSystem{} },
	"Communication":                     func() Resource { return &Communication{} },
	"CommunicationRequest":              func() Resource { return &CommunicationRequest{} },
	"CompartmentDefinition":             func() Resource { return &CompartmentDefinition{} },
	"Composition":                       func() Resource { return &Composition{} },
	"ConceptMap":                        func() Resource { return &ConceptMap{} },
	"Condition":                         func() Resource { return &Condition{} },
	"Consent":                           func() Resource { return &Consent{} },
	"Contract":                          func() Resource { return &Contract{} },
	"Coverage":                          func() Resource { return &Coverage{} },
	"CoverageEligibilityRequest":        func() Resource { return &CoverageEligibilityRequest{} },
	"CoverageEligibilityResponse":       func() Resource { return &CoverageEligibilityResponse{} },
	"DetectedIssue":                     func() Resource { return &DetectedIssue{} },
	"Device":                            func() Resource { return &Device{} },
	"DeviceDefinition":                  func() Resource { return &DeviceDefinition{} },
	"DeviceMetric":                      func() Resource { return &DeviceMetric{} },
	"DeviceRequest":                     func() Resource { return &DeviceRequest{} },
	"DeviceUseStatement":                func() Resource { return &DeviceUseStatement{} },
	"DiagnosticReport":                  func() Resource { return &DiagnosticReport{} },
	"DocumentManifest":                  func() Resource { return &DocumentManifest{} },
	"DocumentReference":                 func() Resource { return &DocumentReference{} },
	"EffectEvidenceSynthesis":           func() Resource { return &EffectEvidenceSynthesis{} },
	"Encounter":                         func() Resource { return &Encounter{} },
	"Endpoint":                          func() Resource { return &Endpoint{} },
	"EnrollmentRequest":                 func() Resource { return &EnrollmentRequest{} },
	"EnrollmentResponse":                func() Resource { return &EnrollmentResponse{} },
	"EpisodeOfCare":                     func() Resource { return &EpisodeOfCare{} },
	"EventDefinition":                   func() Resource { return &EventDefinition{} },
	"Evidence":                          func() Resource { return &Evidence{} },
	"EvidenceVariable":                  func() Resource { return &EvidenceVariable{} },
	"ExampleScenario":                   func() Resource { return &ExampleScenario{} },
	"ExplanationOfBenefit":              func() Resource { return &ExplanationOfBenefit{} },
	"FamilyMemberHistory":               func() Resource { return &FamilyMemberHistory{} },
	"Flag":                              func() Resource { return &Flag{} },
	"Goal":                              func() Resource { return &Goal{} },
	"GraphDefinition":                   func() Resource { return &GraphDefinition{} },
	"Group":                             func() Resource { return &Group{} },
	"GuidanceResponse":                  func() Resource { return &GuidanceResponse{} },
	"HealthcareService":                 func() Resource { return &HealthcareService{} },
	"ImagingStudy":                      func() Resource { return &ImagingStudy{} },
	"Immunization":                      func() Resource { return &Immunization{} },
	"ImmunizationEvaluation":            func() Resource { return &ImmunizationEvaluation{} },
	"ImmunizationRecommendation":        func() Resource { return &ImmunizationRecommendation{} },
	"ImplementationGuide":               func() Resource { return &ImplementationGuide{} },
	"InsurancePlan":                     func() Resource { return &InsurancePlan{} },
	"Invoice":                           func() Resource { return &Invoice{} },
	"Library":                           func() Resource { return &Library{} },
	"Linkage":                           func() Resource { return &Linkage{} },
	"List":                              func() Resource { return &List{} },
	"Location":                          func() Resource { return &Location{} },
	"Measure":                           func() Resource { return &Measure{} },
	"MeasureReport":                     func() Resource { return &MeasureReport{} },
	"Media":                             func() Resource { return &Media{} },
	"Medication":                        func() Resource { return &Medication{} },
	"MedicationAdministration":          func() Resource { return &MedicationAdministration{} },
	"MedicationDispense":                func() Resource { return &MedicationDispense{} },
	"MedicationKnowledge":               func() Resource { return &MedicationKnowledge{} },
	"MedicationRequest":                 func() Resource { return &MedicationRequest{} },
	"MedicationStatement":               func() Resource { return &MedicationStatement{} },
	"MedicinalProduct":                  func() Resource { return &MedicinalProduct{} },
	"MedicinalProductAuthorization":     func() Resource { return &MedicinalProductAuthorization{} },
	"MedicinalProductContraindication":  func() Resource { return &MedicinalProductContraindication{} },
	"MedicinalProductIndication":        func() Resource { return &MedicinalProductIndication{} },
	"MedicinalProductIngredient":        func() Resource { return &MedicinalProductIngredient{} },
	"MedicinalProductInteraction":       func() Resource { return &MedicinalProductInteraction{} },
	"MedicinalProductManufactured":      func() Resource { return &MedicinalProductManufactured{} },
	"MedicinalProductPackaged":          func() Resource { return &MedicinalProductPackaged{} },
	"MedicinalProductPharmaceutical":    func() Resource { return &MedicinalProductPharmaceutical{} },
	"MedicinalProductUndesirableEffect": func() Resource { return &MedicinalProductUndesirableEffect{} },
	"MessageDefinition":                 func() Resource { return &MessageDefinition{} },
	"MessageHeader":                     func() Resource { return &MessageHeader{} },
	"MolecularSequence":                 func() Resource { return &MolecularSequence{} },
	"NamingSystem":                      func() Resource { return &NamingSystem{} },
	"NutritionOrder":                    func() Resource { return &NutritionOrder{} },
	"Observation":                       func() Resource { return &Observation{} },
	"ObservationDefinition":             func() Resource { return &ObservationDefinition{} },
	"OperationDefinition":               func() Resource { return &OperationDefinition{} },
	"OperationOutcome":                  func() Resource { return &OperationOutcome{} },
	"Organization":                      func() Resource { return &Organization{} },
	"OrganizationAffiliation":           func() Resource { return &OrganizationAffiliation{} },
	"Parameters":                        func() Resource { return &Parameters{} },
	"Patient":                           func() Resource { return &Patient{} },
	"PaymentNotice":                     func() Resource { return &PaymentNotice{} },
	"PaymentReconciliation":             func() Resource { return &PaymentReconciliation{} },
	"Person":                            func() Resource { return &Person{} },
	"PlanDefinition":                    func() Resource { return &PlanDefinition{} },
	"Practitioner":                      func() Resource { return &Practitioner{} },
	"PractitionerRole":                  func() Resource { return &PractitionerRole{} },
	"Procedure":                         func() Resource { return &Procedure{} },
	"Provenance":                        func() Resource { return &Provenance{} },
	"Questionnaire":                     func() Resource { return &Questionnaire{} },
	"QuestionnaireResponse":             func() Resource { return &QuestionnaireResponse{} },
	"RelatedPerson":                     func() Resource { return &RelatedPerson{} },
	"RequestGroup":                      func() Resource { return &RequestGroup{} },
	"ResearchDefinition":                func() Resource { return &ResearchDefinition{} },
	"ResearchElementDefinition":         func() Resource { return &ResearchElementDefinition{} },
	"ResearchStudy":                     func() Resource { return &ResearchStudy{} },
	"ResearchSubject":                   func() Resource { return &ResearchSubject{} },
	"RiskAssessment":                    func() Resource { return &RiskAssessment{} },
	"RiskEvidenceSynthesis":             func() Resource { return &RiskEvidenceSynthesis{} },
	"Schedule":                          func() Resource { return &Schedule{} },
	"SearchParameter":                   func() Resource { return &SearchParameter{} },
	"ServiceRequest":                    func() Resource { return &ServiceRequest{} },
	"Slot":                              func() Resource { return &Slot{} },
	"Specimen":                          func() Resource { return &Specimen{} },
	"SpecimenDefinition":                func() Resource { return &SpecimenDefinition{} },
	"StructureDefinition":               func() Resource { return &StructureDefinition{} },
	"StructureMap":                      func() Resource { return &StructureMap{} },
	"Subscription":                      func() Resource { return &Subscription{} },
	"Substance":                         func() Resource { return &Substance{} },
	"SubstanceNucleicAcid":              func() Resource { return &SubstanceNucleicAcid{} },
	"SubstancePolymer":                  func() Resource { return &SubstancePolymer{} },
	"SubstanceProtein":                  func() Resource { return &SubstanceProtein{} },
	"SubstanceReferenceInformation":     func() Resource { return &SubstanceReferenceInformation{} },
	"SubstanceSourceMaterial":           func() Resource { return &SubstanceSourceMaterial{} },
	"SubstanceSpecification":            func() Resource { return &SubstanceSpecification{} },
	"SupplyDelivery":                    func() Resource { return &SupplyDelivery{} },
	"SupplyRequest":                     func() Resource { return &SupplyRequest{} },
	"Task":                              func() Resource { return &Task{} },
	"TerminologyCapabilities":           func() Resource { return &TerminologyCapabilities{} },
	"TestReport":                        func() Resource { return &TestReport{} },
	"TestScript":                        func() Resource { return &TestScript{} },
	"ValueSet":                          func() Resource { return &ValueSet{} },
	"VerificationResult":                func() Resource { return &VerificationResult{} },
	"VisionPrescription":                func() Resource { return &VisionPrescription{} },
}

// NewResource creates an empty instance of the specified resource type.
// Returns an error if the resource type is unknown.
func NewResource(resourceType string) (Resource, error) {
	factory, ok := resourceFactories[resourceType]
	if !ok {
		return nil, fmt.Errorf("unknown resource type: %s", resourceType)
	}
	return factory(), nil
}

// UnmarshalResource deserializes JSON to the correct resource type.
// It first peeks at the resourceType field to determine the type,
// then unmarshals the full JSON into the appropriate struct.
func UnmarshalResource(data []byte) (Resource, error) {
	resourceType, err := GetResourceType(data)
	if err != nil {
		return nil, fmt.Errorf("failed to get resource type: %w", err)
	}

	resource, err := NewResource(resourceType)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal(data, resource); err != nil {
		return nil, fmt.Errorf("failed to unmarshal %s: %w", resourceType, err)
	}

	return resource, nil
}

// GetResourceType extracts the resourceType from JSON without fully deserializing.
// This is useful for routing or validation before full deserialization.
func GetResourceType(data []byte) (string, error) {
	var peek struct {
		ResourceType string `json:"resourceType"`
	}
	if err := json.Unmarshal(data, &peek); err != nil {
		return "", fmt.Errorf("failed to parse JSON: %w", err)
	}
	if peek.ResourceType == "" {
		return "", fmt.Errorf("resourceType field is missing or empty")
	}
	return peek.ResourceType, nil
}

// IsKnownResourceType returns true if the given resource type is known.
func IsKnownResourceType(resourceType string) bool {
	_, ok := resourceFactories[resourceType]
	return ok
}

// AllResourceTypes returns a slice of all known resource type names.
func AllResourceTypes() []string {
	types := make([]string, 0, len(resourceFactories))
	for t := range resourceFactories {
		types = append(types, t)
	}
	return types
}
