// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4

package r4

import (
	"encoding/json"
	"fmt"
)

// PaymentReconciliation represents FHIR PaymentReconciliation.
type PaymentReconciliation struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Business Identifier for a payment reconciliation
	Identifier []Identifier `json:"identifier,omitempty"`
	// active | cancelled | draft | entered-in-error
	Status *FinancialResourceStatusCodes `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// Period covered
	Period *Period `json:"period,omitempty"`
	// Creation date
	Created *string `json:"created,omitempty"`
	// Extension for Created
	CreatedExt *Element `json:"_created,omitempty"`
	// Party generating payment
	PaymentIssuer *Reference `json:"paymentIssuer,omitempty"`
	// Reference to requesting resource
	Request *Reference `json:"request,omitempty"`
	// Responsible practitioner
	Requestor *Reference `json:"requestor,omitempty"`
	// queued | complete | error | partial
	Outcome *ClaimProcessingCodes `json:"outcome,omitempty"`
	// Extension for Outcome
	OutcomeExt *Element `json:"_outcome,omitempty"`
	// Disposition message
	Disposition *string `json:"disposition,omitempty"`
	// Extension for Disposition
	DispositionExt *Element `json:"_disposition,omitempty"`
	// When payment issued
	PaymentDate *string `json:"paymentDate,omitempty"`
	// Extension for PaymentDate
	PaymentDateExt *Element `json:"_paymentDate,omitempty"`
	// Total amount of Payment
	PaymentAmount Money `json:"paymentAmount"`
	// Business identifier for the payment
	PaymentIdentifier *Identifier `json:"paymentIdentifier,omitempty"`
	// Settlement particulars
	Detail []PaymentReconciliationDetail `json:"detail,omitempty"`
	// Printed form identifier
	FormCode *CodeableConcept `json:"formCode,omitempty"`
	// Note concerning processing
	ProcessNote []PaymentReconciliationProcessNote `json:"processNote,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *PaymentReconciliation) GetResourceType() string {
	return "PaymentReconciliation"
}

// GetId returns the resource's logical ID.
func (r *PaymentReconciliation) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *PaymentReconciliation) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *PaymentReconciliation) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *PaymentReconciliation) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *PaymentReconciliation) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *PaymentReconciliation) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *PaymentReconciliation) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *PaymentReconciliation) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *PaymentReconciliation) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r PaymentReconciliation) MarshalJSON() ([]byte, error) {
	r.ResourceType = "PaymentReconciliation"
	type Alias PaymentReconciliation
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *PaymentReconciliation) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias PaymentReconciliation
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
