// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4

package r4

import (
	"encoding/json"
	"fmt"
)

// MedicinalProductContraindication represents FHIR MedicinalProductContraindication.
type MedicinalProductContraindication struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// The medication for which this is an indication
	Subject []Reference `json:"subject,omitempty"`
	// The disease, symptom or procedure for the contraindication
	Disease *CodeableConcept `json:"disease,omitempty"`
	// The status of the disease or symptom for the contraindication
	DiseaseStatus *CodeableConcept `json:"diseaseStatus,omitempty"`
	// A comorbidity (concurrent condition) or coinfection
	Comorbidity []CodeableConcept `json:"comorbidity,omitempty"`
	// Information about the use of the medicinal product in relation to other therapies as part of the indication
	TherapeuticIndication []Reference `json:"therapeuticIndication,omitempty"`
	// Information about the use of the medicinal product in relation to other therapies described as part of the indication
	OtherTherapy []MedicinalProductContraindicationOtherTherapy `json:"otherTherapy,omitempty"`
	// The population group to which this applies
	Population []Population `json:"population,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *MedicinalProductContraindication) GetResourceType() string {
	return "MedicinalProductContraindication"
}

// GetId returns the resource's logical ID.
func (r *MedicinalProductContraindication) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *MedicinalProductContraindication) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *MedicinalProductContraindication) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *MedicinalProductContraindication) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *MedicinalProductContraindication) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *MedicinalProductContraindication) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *MedicinalProductContraindication) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *MedicinalProductContraindication) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *MedicinalProductContraindication) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r MedicinalProductContraindication) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicinalProductContraindication"
	type Alias MedicinalProductContraindication
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *MedicinalProductContraindication) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias MedicinalProductContraindication
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
