// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4

package r4

import (
	"encoding/json"
	"fmt"
)

// SubstanceSpecification represents FHIR SubstanceSpecification.
type SubstanceSpecification struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifier by which this substance is known
	Identifier *Identifier `json:"identifier,omitempty"`
	// High level categorization, e.g. polymer or nucleic acid
	Type *CodeableConcept `json:"type,omitempty"`
	// Status of substance within the catalogue e.g. approved
	Status *CodeableConcept `json:"status,omitempty"`
	// If the substance applies to only human or veterinary use
	Domain *CodeableConcept `json:"domain,omitempty"`
	// Textual description of the substance
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// Supporting literature
	Source []Reference `json:"source,omitempty"`
	// Textual comment about this record of a substance
	Comment *string `json:"comment,omitempty"`
	// Extension for Comment
	CommentExt *Element `json:"_comment,omitempty"`
	// Moiety, for structural modifications
	Moiety []SubstanceSpecificationMoiety `json:"moiety,omitempty"`
	// General specifications for this substance, including how it is related to other substances
	Property []SubstanceSpecificationProperty `json:"property,omitempty"`
	// General information detailing this substance
	ReferenceInformation *Reference `json:"referenceInformation,omitempty"`
	// Structural information
	Structure *SubstanceSpecificationStructure `json:"structure,omitempty"`
	// Codes associated with the substance
	Code []SubstanceSpecificationCode `json:"code,omitempty"`
	// Names applicable to this substance
	Name []SubstanceSpecificationName `json:"name,omitempty"`
	// The molecular weight or weight range (for proteins, polymers or nucleic acids)
	MolecularWeight []SubstanceSpecificationStructureIsotopeMolecularWeight `json:"molecularWeight,omitempty"`
	// A link between this substance and another, with details of the relationship
	Relationship []SubstanceSpecificationRelationship `json:"relationship,omitempty"`
	// Data items specific to nucleic acids
	NucleicAcid *Reference `json:"nucleicAcid,omitempty"`
	// Data items specific to polymers
	Polymer *Reference `json:"polymer,omitempty"`
	// Data items specific to proteins
	Protein *Reference `json:"protein,omitempty"`
	// Material or taxonomic/anatomical source for the substance
	SourceMaterial *Reference `json:"sourceMaterial,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *SubstanceSpecification) GetResourceType() string {
	return "SubstanceSpecification"
}

// GetId returns the resource's logical ID.
func (r *SubstanceSpecification) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *SubstanceSpecification) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *SubstanceSpecification) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *SubstanceSpecification) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *SubstanceSpecification) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *SubstanceSpecification) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *SubstanceSpecification) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *SubstanceSpecification) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *SubstanceSpecification) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r SubstanceSpecification) MarshalJSON() ([]byte, error) {
	r.ResourceType = "SubstanceSpecification"
	type Alias SubstanceSpecification
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *SubstanceSpecification) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias SubstanceSpecification
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
