// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (backbone elements)
// Package: r4b

package r4b

// EvidenceVariableCategory represents the EvidenceVariable.category backbone element.
// A grouping for ordinal or polychotomous variables
type EvidenceVariableCategory struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Description of the grouping
	Name *string `json:"name,omitempty"`
	// Definition of the grouping
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty"`
	// Definition of the grouping
	ValueQuantity *Quantity `json:"valueQuantity,omitempty"`
	// Definition of the grouping
	ValueRange *Range `json:"valueRange,omitempty"`
}

// EvidenceVariableCharacteristic represents the EvidenceVariable.characteristic backbone element.
// What defines the members of the evidence element
type EvidenceVariableCharacteristic struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Natural language description of the characteristic
	Description *string `json:"description,omitempty"`
	// What code or expression defines members?
	DefinitionReference *Reference `json:"definitionReference,omitempty"`
	// What code or expression defines members?
	DefinitionCanonical *string `json:"definitionCanonical,omitempty"`
	// Extension for DefinitionCanonical
	DefinitionCanonicalExt *Element `json:"_definitionCanonical,omitempty"`
	// What code or expression defines members?
	DefinitionCodeableConcept *CodeableConcept `json:"definitionCodeableConcept,omitempty"`
	// What code or expression defines members?
	DefinitionExpression *Expression `json:"definitionExpression,omitempty"`
	// Method used for describing characteristic
	Method *CodeableConcept `json:"method,omitempty"`
	// Device used for determining characteristic
	Device *Reference `json:"device,omitempty"`
	// Whether the characteristic includes or excludes members
	Exclude *bool `json:"exclude,omitempty"`
	// Observation time from study start
	TimeFromStart *EvidenceVariableCharacteristicTimeFromStart `json:"timeFromStart,omitempty"`
	// mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median
	GroupMeasure *GroupMeasure `json:"groupMeasure,omitempty"`
}

// EvidenceVariableCharacteristicTimeFromStart represents the EvidenceVariable.characteristic.timeFromStart backbone element.
// Observation time from study start
type EvidenceVariableCharacteristicTimeFromStart struct {
	// Unique id for inter-element referencing
	Id *string `json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Human readable description
	Description *string `json:"description,omitempty"`
	// Used to express the observation at a defined amount of time after the study start
	Quantity *Quantity `json:"quantity,omitempty"`
	// Used to express the observation within a period after the study start
	Range *Range `json:"range,omitempty"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty"`
}
