// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4b

package r4b

// =============================================================================
// ImmunizationRecommendation - Fluent Builder
// =============================================================================

// ImmunizationRecommendationBuilder provides a fluent API for constructing ImmunizationRecommendation resources.
type ImmunizationRecommendationBuilder struct {
	immunizationRecommendation *ImmunizationRecommendation
}

// NewImmunizationRecommendationBuilder creates a new ImmunizationRecommendationBuilder.
func NewImmunizationRecommendationBuilder() *ImmunizationRecommendationBuilder {
	return &ImmunizationRecommendationBuilder{
		immunizationRecommendation: &ImmunizationRecommendation{},
	}
}

// Build returns the constructed ImmunizationRecommendation resource.
func (b *ImmunizationRecommendationBuilder) Build() *ImmunizationRecommendation {
	return b.immunizationRecommendation
}

// SetId sets the Id field.
func (b *ImmunizationRecommendationBuilder) SetId(v string) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *ImmunizationRecommendationBuilder) SetMeta(v Meta) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *ImmunizationRecommendationBuilder) SetImplicitRules(v string) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *ImmunizationRecommendationBuilder) SetLanguage(v string) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Language = &v
	return b
}

// SetText sets the Text field.
func (b *ImmunizationRecommendationBuilder) SetText(v Narrative) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *ImmunizationRecommendationBuilder) AddContained(v Resource) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Contained = append(b.immunizationRecommendation.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *ImmunizationRecommendationBuilder) AddExtension(v Extension) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Extension = append(b.immunizationRecommendation.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *ImmunizationRecommendationBuilder) AddModifierExtension(v Extension) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.ModifierExtension = append(b.immunizationRecommendation.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *ImmunizationRecommendationBuilder) AddIdentifier(v Identifier) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Identifier = append(b.immunizationRecommendation.Identifier, v)
	return b
}

// SetPatient sets the Patient field.
func (b *ImmunizationRecommendationBuilder) SetPatient(v Reference) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Patient = v
	return b
}

// SetDate sets the Date field.
func (b *ImmunizationRecommendationBuilder) SetDate(v string) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Date = &v
	return b
}

// SetAuthority sets the Authority field.
func (b *ImmunizationRecommendationBuilder) SetAuthority(v Reference) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Authority = &v
	return b
}

// AddRecommendation adds a Recommendation element.
func (b *ImmunizationRecommendationBuilder) AddRecommendation(v ImmunizationRecommendationRecommendation) *ImmunizationRecommendationBuilder {
	b.immunizationRecommendation.Recommendation = append(b.immunizationRecommendation.Recommendation, v)
	return b
}
