// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (fluent builders)
// Package: r4b

package r4b

// =============================================================================
// Invoice - Fluent Builder
// =============================================================================

// InvoiceBuilder provides a fluent API for constructing Invoice resources.
type InvoiceBuilder struct {
	invoice *Invoice
}

// NewInvoiceBuilder creates a new InvoiceBuilder.
func NewInvoiceBuilder() *InvoiceBuilder {
	return &InvoiceBuilder{
		invoice: &Invoice{},
	}
}

// Build returns the constructed Invoice resource.
func (b *InvoiceBuilder) Build() *Invoice {
	return b.invoice
}

// SetId sets the Id field.
func (b *InvoiceBuilder) SetId(v string) *InvoiceBuilder {
	b.invoice.Id = &v
	return b
}

// SetMeta sets the Meta field.
func (b *InvoiceBuilder) SetMeta(v Meta) *InvoiceBuilder {
	b.invoice.Meta = &v
	return b
}

// SetImplicitRules sets the ImplicitRules field.
func (b *InvoiceBuilder) SetImplicitRules(v string) *InvoiceBuilder {
	b.invoice.ImplicitRules = &v
	return b
}

// SetLanguage sets the Language field.
func (b *InvoiceBuilder) SetLanguage(v string) *InvoiceBuilder {
	b.invoice.Language = &v
	return b
}

// SetText sets the Text field.
func (b *InvoiceBuilder) SetText(v Narrative) *InvoiceBuilder {
	b.invoice.Text = &v
	return b
}

// AddContained adds a Contained element.
func (b *InvoiceBuilder) AddContained(v Resource) *InvoiceBuilder {
	b.invoice.Contained = append(b.invoice.Contained, v)
	return b
}

// AddExtension adds a Extension element.
func (b *InvoiceBuilder) AddExtension(v Extension) *InvoiceBuilder {
	b.invoice.Extension = append(b.invoice.Extension, v)
	return b
}

// AddModifierExtension adds a ModifierExtension element.
func (b *InvoiceBuilder) AddModifierExtension(v Extension) *InvoiceBuilder {
	b.invoice.ModifierExtension = append(b.invoice.ModifierExtension, v)
	return b
}

// AddIdentifier adds a Identifier element.
func (b *InvoiceBuilder) AddIdentifier(v Identifier) *InvoiceBuilder {
	b.invoice.Identifier = append(b.invoice.Identifier, v)
	return b
}

// SetStatus sets the Status field.
func (b *InvoiceBuilder) SetStatus(v InvoiceStatus) *InvoiceBuilder {
	b.invoice.Status = &v
	return b
}

// SetCancelledReason sets the CancelledReason field.
func (b *InvoiceBuilder) SetCancelledReason(v string) *InvoiceBuilder {
	b.invoice.CancelledReason = &v
	return b
}

// SetType sets the Type field.
func (b *InvoiceBuilder) SetType(v CodeableConcept) *InvoiceBuilder {
	b.invoice.Type = &v
	return b
}

// SetSubject sets the Subject field.
func (b *InvoiceBuilder) SetSubject(v Reference) *InvoiceBuilder {
	b.invoice.Subject = &v
	return b
}

// SetRecipient sets the Recipient field.
func (b *InvoiceBuilder) SetRecipient(v Reference) *InvoiceBuilder {
	b.invoice.Recipient = &v
	return b
}

// SetDate sets the Date field.
func (b *InvoiceBuilder) SetDate(v string) *InvoiceBuilder {
	b.invoice.Date = &v
	return b
}

// AddParticipant adds a Participant element.
func (b *InvoiceBuilder) AddParticipant(v InvoiceParticipant) *InvoiceBuilder {
	b.invoice.Participant = append(b.invoice.Participant, v)
	return b
}

// SetIssuer sets the Issuer field.
func (b *InvoiceBuilder) SetIssuer(v Reference) *InvoiceBuilder {
	b.invoice.Issuer = &v
	return b
}

// SetAccount sets the Account field.
func (b *InvoiceBuilder) SetAccount(v Reference) *InvoiceBuilder {
	b.invoice.Account = &v
	return b
}

// AddLineItem adds a LineItem element.
func (b *InvoiceBuilder) AddLineItem(v InvoiceLineItem) *InvoiceBuilder {
	b.invoice.LineItem = append(b.invoice.LineItem, v)
	return b
}

// AddTotalPriceComponent adds a TotalPriceComponent element.
func (b *InvoiceBuilder) AddTotalPriceComponent(v InvoiceLineItemPriceComponent) *InvoiceBuilder {
	b.invoice.TotalPriceComponent = append(b.invoice.TotalPriceComponent, v)
	return b
}

// SetTotalNet sets the TotalNet field.
func (b *InvoiceBuilder) SetTotalNet(v Money) *InvoiceBuilder {
	b.invoice.TotalNet = &v
	return b
}

// SetTotalGross sets the TotalGross field.
func (b *InvoiceBuilder) SetTotalGross(v Money) *InvoiceBuilder {
	b.invoice.TotalGross = &v
	return b
}

// SetPaymentTerms sets the PaymentTerms field.
func (b *InvoiceBuilder) SetPaymentTerms(v string) *InvoiceBuilder {
	b.invoice.PaymentTerms = &v
	return b
}

// AddNote adds a Note element.
func (b *InvoiceBuilder) AddNote(v Annotation) *InvoiceBuilder {
	b.invoice.Note = append(b.invoice.Note, v)
	return b
}
