// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR ValueSets (codesystems)
// Package: r4b

package r4b

// FHIRVersion represents FHIRVersion.
type FHIRVersion string

// FHIRVersion values.
const (
	// FHIRVersion001 - 0.01
	FHIRVersion001 FHIRVersion = "0.01"
	// FHIRVersion005 - 0.05
	FHIRVersion005 FHIRVersion = "0.05"
	// FHIRVersion006 - 0.06
	FHIRVersion006 FHIRVersion = "0.06"
	// FHIRVersion011 - 0.11
	FHIRVersion011 FHIRVersion = "0.11"
	// FHIRVersion0080 - 0.0.80
	FHIRVersion0080 FHIRVersion = "0.0.80"
	// FHIRVersion0081 - 0.0.81
	FHIRVersion0081 FHIRVersion = "0.0.81"
	// FHIRVersion0082 - 0.0.82
	FHIRVersion0082 FHIRVersion = "0.0.82"
	// FHIRVersion040 - 0.4.0
	FHIRVersion040 FHIRVersion = "0.4.0"
	// FHIRVersion050 - 0.5.0
	FHIRVersion050 FHIRVersion = "0.5.0"
	// FHIRVersion100 - 1.0.0
	FHIRVersion100 FHIRVersion = "1.0.0"
	// FHIRVersion101 - 1.0.1
	FHIRVersion101 FHIRVersion = "1.0.1"
	// FHIRVersion102 - 1.0.2
	FHIRVersion102 FHIRVersion = "1.0.2"
	// FHIRVersion110 - 1.1.0
	FHIRVersion110 FHIRVersion = "1.1.0"
	// FHIRVersion140 - 1.4.0
	FHIRVersion140 FHIRVersion = "1.4.0"
	// FHIRVersion160 - 1.6.0
	FHIRVersion160 FHIRVersion = "1.6.0"
	// FHIRVersion180 - 1.8.0
	FHIRVersion180 FHIRVersion = "1.8.0"
	// FHIRVersion300 - 3.0.0
	FHIRVersion300 FHIRVersion = "3.0.0"
	// FHIRVersion301 - 3.0.1
	FHIRVersion301 FHIRVersion = "3.0.1"
	// FHIRVersion302 - 3.0.2
	FHIRVersion302 FHIRVersion = "3.0.2"
	// FHIRVersion330 - 3.3.0
	FHIRVersion330 FHIRVersion = "3.3.0"
	// FHIRVersion350 - 3.5.0
	FHIRVersion350 FHIRVersion = "3.5.0"
	// FHIRVersion400 - 4.0.0
	FHIRVersion400 FHIRVersion = "4.0.0"
	// FHIRVersion401 - 4.0.1
	FHIRVersion401 FHIRVersion = "4.0.1"
	// FHIRVersion410 - 4.1.0
	FHIRVersion410 FHIRVersion = "4.1.0"
	// FHIRVersion430Cibuild - 4.3.0-cibuild
	FHIRVersion430Cibuild FHIRVersion = "4.3.0-cibuild"
	// FHIRVersion430Snapshot1 - 4.3.0-snapshot1
	FHIRVersion430Snapshot1 FHIRVersion = "4.3.0-snapshot1"
	// FHIRVersion430 - 4.3.0
	FHIRVersion430 FHIRVersion = "4.3.0"
)

// AccountStatus represents AccountStatus.
type AccountStatus string

// AccountStatus values.
const (
	// AccountStatusActive - Active
	AccountStatusActive AccountStatus = "active"
	// AccountStatusInactive - Inactive
	AccountStatusInactive AccountStatus = "inactive"
	// AccountStatusEnteredInError - Entered in error
	AccountStatusEnteredInError AccountStatus = "entered-in-error"
	// AccountStatusOnHold - On Hold
	AccountStatusOnHold AccountStatus = "on-hold"
	// AccountStatusUnknown - Unknown
	AccountStatusUnknown AccountStatus = "unknown"
)

// AddressType represents AddressType.
type AddressType string

// AddressType values.
const (
	// AddressTypePostal - Postal
	AddressTypePostal AddressType = "postal"
	// AddressTypePhysical - Physical
	AddressTypePhysical AddressType = "physical"
	// AddressTypeBoth - Postal & Physical
	AddressTypeBoth AddressType = "both"
)

// AddressUse represents AddressUse.
type AddressUse string

// AddressUse values.
const (
	// AddressUseHome - Home
	AddressUseHome AddressUse = "home"
	// AddressUseWork - Work
	AddressUseWork AddressUse = "work"
	// AddressUseTemp - Temporary
	AddressUseTemp AddressUse = "temp"
	// AddressUseOld - Old / Incorrect
	AddressUseOld AddressUse = "old"
	// AddressUseBilling - Billing
	AddressUseBilling AddressUse = "billing"
)

// AdministrativeGender represents AdministrativeGender.
type AdministrativeGender string

// AdministrativeGender values.
const (
	// AdministrativeGenderMale - Male
	AdministrativeGenderMale AdministrativeGender = "male"
	// AdministrativeGenderFemale - Female
	AdministrativeGenderFemale AdministrativeGender = "female"
	// AdministrativeGenderOther - Other
	AdministrativeGenderOther AdministrativeGender = "other"
	// AdministrativeGenderUnknown - Unknown
	AdministrativeGenderUnknown AdministrativeGender = "unknown"
)

// AdverseEventActuality represents AdverseEventActuality.
type AdverseEventActuality string

// AdverseEventActuality values.
const (
	// AdverseEventActualityActual - Adverse Event
	AdverseEventActualityActual AdverseEventActuality = "actual"
	// AdverseEventActualityPotential - Potential Adverse Event
	AdverseEventActualityPotential AdverseEventActuality = "potential"
)

// AllergyIntoleranceCategory represents AllergyIntoleranceCategory.
type AllergyIntoleranceCategory string

// AllergyIntoleranceCategory values.
const (
	// AllergyIntoleranceCategoryFood - Food
	AllergyIntoleranceCategoryFood AllergyIntoleranceCategory = "food"
	// AllergyIntoleranceCategoryMedication - Medication
	AllergyIntoleranceCategoryMedication AllergyIntoleranceCategory = "medication"
	// AllergyIntoleranceCategoryEnvironment - Environment
	AllergyIntoleranceCategoryEnvironment AllergyIntoleranceCategory = "environment"
	// AllergyIntoleranceCategoryBiologic - Biologic
	AllergyIntoleranceCategoryBiologic AllergyIntoleranceCategory = "biologic"
)

// AllergyIntoleranceCriticality represents AllergyIntoleranceCriticality.
type AllergyIntoleranceCriticality string

// AllergyIntoleranceCriticality values.
const (
	// AllergyIntoleranceCriticalityLow - Low Risk
	AllergyIntoleranceCriticalityLow AllergyIntoleranceCriticality = "low"
	// AllergyIntoleranceCriticalityHigh - High Risk
	AllergyIntoleranceCriticalityHigh AllergyIntoleranceCriticality = "high"
	// AllergyIntoleranceCriticalityUnableToAssess - Unable to Assess Risk
	AllergyIntoleranceCriticalityUnableToAssess AllergyIntoleranceCriticality = "unable-to-assess"
)

// AllergyIntoleranceType represents AllergyIntoleranceType.
type AllergyIntoleranceType string

// AllergyIntoleranceType values.
const (
	// AllergyIntoleranceTypeAllergy - Allergy
	AllergyIntoleranceTypeAllergy AllergyIntoleranceType = "allergy"
	// AllergyIntoleranceTypeIntolerance - Intolerance
	AllergyIntoleranceTypeIntolerance AllergyIntoleranceType = "intolerance"
)

// AppointmentStatus represents AppointmentStatus.
type AppointmentStatus string

// AppointmentStatus values.
const (
	// AppointmentStatusProposed - Proposed
	AppointmentStatusProposed AppointmentStatus = "proposed"
	// AppointmentStatusPending - Pending
	AppointmentStatusPending AppointmentStatus = "pending"
	// AppointmentStatusBooked - Booked
	AppointmentStatusBooked AppointmentStatus = "booked"
	// AppointmentStatusArrived - Arrived
	AppointmentStatusArrived AppointmentStatus = "arrived"
	// AppointmentStatusFulfilled - Fulfilled
	AppointmentStatusFulfilled AppointmentStatus = "fulfilled"
	// AppointmentStatusCancelled - Cancelled
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	// AppointmentStatusNoshow - No Show
	AppointmentStatusNoshow AppointmentStatus = "noshow"
	// AppointmentStatusEnteredInError - Entered in error
	AppointmentStatusEnteredInError AppointmentStatus = "entered-in-error"
	// AppointmentStatusCheckedIn - Checked In
	AppointmentStatusCheckedIn AppointmentStatus = "checked-in"
	// AppointmentStatusWaitlist - Waitlisted
	AppointmentStatusWaitlist AppointmentStatus = "waitlist"
)

// AuditEventAction represents AuditEventAction.
type AuditEventAction string

// AuditEventAction values.
const (
	// AuditEventActionC - Create
	AuditEventActionC AuditEventAction = "C"
	// AuditEventActionR - Read/View/Print
	AuditEventActionR AuditEventAction = "R"
	// AuditEventActionU - Update
	AuditEventActionU AuditEventAction = "U"
	// AuditEventActionD - Delete
	AuditEventActionD AuditEventAction = "D"
	// AuditEventActionE - Execute
	AuditEventActionE AuditEventAction = "E"
)

// AuditEventOutcome represents AuditEventOutcome.
type AuditEventOutcome string

// AuditEventOutcome values.
const (
	// AuditEventOutcome0 - Success
	AuditEventOutcome0 AuditEventOutcome = "0"
	// AuditEventOutcome4 - Minor failure
	AuditEventOutcome4 AuditEventOutcome = "4"
	// AuditEventOutcome8 - Serious failure
	AuditEventOutcome8 AuditEventOutcome = "8"
	// AuditEventOutcome12 - Major failure
	AuditEventOutcome12 AuditEventOutcome = "12"
)

// BundleType represents BundleType.
type BundleType string

// BundleType values.
const (
	// BundleTypeDocument - Document
	BundleTypeDocument BundleType = "document"
	// BundleTypeMessage - Message
	BundleTypeMessage BundleType = "message"
	// BundleTypeTransaction - Transaction
	BundleTypeTransaction BundleType = "transaction"
	// BundleTypeTransactionResponse - Transaction Response
	BundleTypeTransactionResponse BundleType = "transaction-response"
	// BundleTypeBatch - Batch
	BundleTypeBatch BundleType = "batch"
	// BundleTypeBatchResponse - Batch Response
	BundleTypeBatchResponse BundleType = "batch-response"
	// BundleTypeHistory - History List
	BundleTypeHistory BundleType = "history"
	// BundleTypeSearchset - Search Results
	BundleTypeSearchset BundleType = "searchset"
	// BundleTypeCollection - Collection
	BundleTypeCollection BundleType = "collection"
)

// CapabilityStatementKind represents CapabilityStatementKind.
type CapabilityStatementKind string

// CapabilityStatementKind values.
const (
	// CapabilityStatementKindInstance - Instance
	CapabilityStatementKindInstance CapabilityStatementKind = "instance"
	// CapabilityStatementKindCapability - Capability
	CapabilityStatementKindCapability CapabilityStatementKind = "capability"
	// CapabilityStatementKindRequirements - Requirements
	CapabilityStatementKindRequirements CapabilityStatementKind = "requirements"
)

// CarePlanIntent represents Care Plan Intent.
type CarePlanIntent string

// CarePlanIntent values.
const (
	CarePlanIntentProposal CarePlanIntent = "proposal"
	CarePlanIntentPlan     CarePlanIntent = "plan"
	CarePlanIntentOrder    CarePlanIntent = "order"
	CarePlanIntentOption   CarePlanIntent = "option"
)

// CareTeamStatus represents CareTeamStatus.
type CareTeamStatus string

// CareTeamStatus values.
const (
	// CareTeamStatusProposed - Proposed
	CareTeamStatusProposed CareTeamStatus = "proposed"
	// CareTeamStatusActive - Active
	CareTeamStatusActive CareTeamStatus = "active"
	// CareTeamStatusSuspended - Suspended
	CareTeamStatusSuspended CareTeamStatus = "suspended"
	// CareTeamStatusInactive - Inactive
	CareTeamStatusInactive CareTeamStatus = "inactive"
	// CareTeamStatusEnteredInError - Entered in Error
	CareTeamStatusEnteredInError CareTeamStatus = "entered-in-error"
)

// CharacteristicCombination represents CharacteristicCombination.
type CharacteristicCombination string

// CharacteristicCombination values.
const (
	// CharacteristicCombinationIntersection - intersection
	CharacteristicCombinationIntersection CharacteristicCombination = "intersection"
	// CharacteristicCombinationUnion - union
	CharacteristicCombinationUnion CharacteristicCombination = "union"
)

// ChargeItemStatus represents ChargeItemStatus.
type ChargeItemStatus string

// ChargeItemStatus values.
const (
	// ChargeItemStatusPlanned - Planned
	ChargeItemStatusPlanned ChargeItemStatus = "planned"
	// ChargeItemStatusBillable - Billable
	ChargeItemStatusBillable ChargeItemStatus = "billable"
	// ChargeItemStatusNotBillable - Not billable
	ChargeItemStatusNotBillable ChargeItemStatus = "not-billable"
	// ChargeItemStatusAborted - Aborted
	ChargeItemStatusAborted ChargeItemStatus = "aborted"
	// ChargeItemStatusBilled - Billed
	ChargeItemStatusBilled ChargeItemStatus = "billed"
	// ChargeItemStatusEnteredInError - Entered in Error
	ChargeItemStatusEnteredInError ChargeItemStatus = "entered-in-error"
	// ChargeItemStatusUnknown - Unknown
	ChargeItemStatusUnknown ChargeItemStatus = "unknown"
)

// Use represents Use.
type Use string

// Use values.
const (
	// UseClaim - Claim
	UseClaim Use = "claim"
	// UsePreauthorization - Preauthorization
	UsePreauthorization Use = "preauthorization"
	// UsePredetermination - Predetermination
	UsePredetermination Use = "predetermination"
)

// ClinicalUseDefinitionType represents ClinicalUseDefinitionType.
type ClinicalUseDefinitionType string

// ClinicalUseDefinitionType values.
const (
	// ClinicalUseDefinitionTypeIndication - Indication
	ClinicalUseDefinitionTypeIndication ClinicalUseDefinitionType = "indication"
	// ClinicalUseDefinitionTypeContraindication - Contraindication
	ClinicalUseDefinitionTypeContraindication ClinicalUseDefinitionType = "contraindication"
	// ClinicalUseDefinitionTypeInteraction - Interaction
	ClinicalUseDefinitionTypeInteraction ClinicalUseDefinitionType = "interaction"
	// ClinicalUseDefinitionTypeUndesirableEffect - Undesirable Effect
	ClinicalUseDefinitionTypeUndesirableEffect ClinicalUseDefinitionType = "undesirable-effect"
	// ClinicalUseDefinitionTypeWarning - Warning
	ClinicalUseDefinitionTypeWarning ClinicalUseDefinitionType = "warning"
)

// ClinicalImpressionStatus represents Clinical Impression Status.
type ClinicalImpressionStatus string

// ClinicalImpressionStatus values.
const (
	ClinicalImpressionStatusInProgress     ClinicalImpressionStatus = "in-progress"
	ClinicalImpressionStatusCompleted      ClinicalImpressionStatus = "completed"
	ClinicalImpressionStatusEnteredInError ClinicalImpressionStatus = "entered-in-error"
)

// CodeSearchSupport represents CodeSearchSupport.
type CodeSearchSupport string

// CodeSearchSupport values.
const (
	// CodeSearchSupportExplicit - Explicit Codes
	CodeSearchSupportExplicit CodeSearchSupport = "explicit"
	// CodeSearchSupportAll - Implicit Codes
	CodeSearchSupportAll CodeSearchSupport = "all"
)

// CodeSystemContentMode represents CodeSystemContentMode.
type CodeSystemContentMode string

// CodeSystemContentMode values.
const (
	// CodeSystemContentModeNotPresent - Not Present
	CodeSystemContentModeNotPresent CodeSystemContentMode = "not-present"
	// CodeSystemContentModeExample - Example
	CodeSystemContentModeExample CodeSystemContentMode = "example"
	// CodeSystemContentModeFragment - Fragment
	CodeSystemContentModeFragment CodeSystemContentMode = "fragment"
	// CodeSystemContentModeComplete - Complete
	CodeSystemContentModeComplete CodeSystemContentMode = "complete"
	// CodeSystemContentModeSupplement - Supplement
	CodeSystemContentModeSupplement CodeSystemContentMode = "supplement"
)

// CodeSystemHierarchyMeaning represents CodeSystemHierarchyMeaning.
type CodeSystemHierarchyMeaning string

// CodeSystemHierarchyMeaning values.
const (
	// CodeSystemHierarchyMeaningGroupedBy - Grouped By
	CodeSystemHierarchyMeaningGroupedBy CodeSystemHierarchyMeaning = "grouped-by"
	// CodeSystemHierarchyMeaningIsA - Is-A
	CodeSystemHierarchyMeaningIsA CodeSystemHierarchyMeaning = "is-a"
	// CodeSystemHierarchyMeaningPartOf - Part Of
	CodeSystemHierarchyMeaningPartOf CodeSystemHierarchyMeaning = "part-of"
	// CodeSystemHierarchyMeaningClassifiedWith - Classified With
	CodeSystemHierarchyMeaningClassifiedWith CodeSystemHierarchyMeaning = "classified-with"
)

// CompartmentType represents CompartmentType.
type CompartmentType string

// CompartmentType values.
const (
	// CompartmentTypePatient - Patient
	CompartmentTypePatient CompartmentType = "Patient"
	// CompartmentTypeEncounter - Encounter
	CompartmentTypeEncounter CompartmentType = "Encounter"
	// CompartmentTypeRelatedperson - RelatedPerson
	CompartmentTypeRelatedperson CompartmentType = "RelatedPerson"
	// CompartmentTypePractitioner - Practitioner
	CompartmentTypePractitioner CompartmentType = "Practitioner"
	// CompartmentTypeDevice - Device
	CompartmentTypeDevice CompartmentType = "Device"
)

// CompositionStatus represents CompositionStatus.
type CompositionStatus string

// CompositionStatus values.
const (
	// CompositionStatusPreliminary - Preliminary
	CompositionStatusPreliminary CompositionStatus = "preliminary"
	// CompositionStatusFinal - Final
	CompositionStatusFinal CompositionStatus = "final"
	// CompositionStatusAmended - Amended
	CompositionStatusAmended CompositionStatus = "amended"
	// CompositionStatusEnteredInError - Entered in Error
	CompositionStatusEnteredInError CompositionStatus = "entered-in-error"
)

// ConsentState represents ConsentState.
type ConsentState string

// ConsentState values.
const (
	// ConsentStateDraft - Pending
	ConsentStateDraft ConsentState = "draft"
	// ConsentStateProposed - Proposed
	ConsentStateProposed ConsentState = "proposed"
	// ConsentStateActive - Active
	ConsentStateActive ConsentState = "active"
	// ConsentStateRejected - Rejected
	ConsentStateRejected ConsentState = "rejected"
	// ConsentStateInactive - Inactive
	ConsentStateInactive ConsentState = "inactive"
	// ConsentStateEnteredInError - Entered in Error
	ConsentStateEnteredInError ConsentState = "entered-in-error"
)

// ContactPointSystem represents ContactPointSystem.
type ContactPointSystem string

// ContactPointSystem values.
const (
	// ContactPointSystemPhone - Phone
	ContactPointSystemPhone ContactPointSystem = "phone"
	// ContactPointSystemFax - Fax
	ContactPointSystemFax ContactPointSystem = "fax"
	// ContactPointSystemEmail - Email
	ContactPointSystemEmail ContactPointSystem = "email"
	// ContactPointSystemPager - Pager
	ContactPointSystemPager ContactPointSystem = "pager"
	// ContactPointSystemUrl - URL
	ContactPointSystemUrl ContactPointSystem = "url"
	// ContactPointSystemSms - SMS
	ContactPointSystemSms ContactPointSystem = "sms"
	// ContactPointSystemOther - Other
	ContactPointSystemOther ContactPointSystem = "other"
)

// ContactPointUse represents ContactPointUse.
type ContactPointUse string

// ContactPointUse values.
const (
	// ContactPointUseHome - Home
	ContactPointUseHome ContactPointUse = "home"
	// ContactPointUseWork - Work
	ContactPointUseWork ContactPointUse = "work"
	// ContactPointUseTemp - Temp
	ContactPointUseTemp ContactPointUse = "temp"
	// ContactPointUseOld - Old
	ContactPointUseOld ContactPointUse = "old"
	// ContactPointUseMobile - Mobile
	ContactPointUseMobile ContactPointUse = "mobile"
)

// ContractResourceStatusCodes represents Contract Resource Status Codes.
type ContractResourceStatusCodes string

// ContractResourceStatusCodes values.
const (
	// ContractResourceStatusCodesAmended - Amended
	ContractResourceStatusCodesAmended ContractResourceStatusCodes = "amended"
	// ContractResourceStatusCodesAppended - Appended
	ContractResourceStatusCodesAppended ContractResourceStatusCodes = "appended"
	// ContractResourceStatusCodesCancelled - Cancelled
	ContractResourceStatusCodesCancelled ContractResourceStatusCodes = "cancelled"
	// ContractResourceStatusCodesDisputed - Disputed
	ContractResourceStatusCodesDisputed ContractResourceStatusCodes = "disputed"
	// ContractResourceStatusCodesEnteredInError - Entered in Error
	ContractResourceStatusCodesEnteredInError ContractResourceStatusCodes = "entered-in-error"
	// ContractResourceStatusCodesExecutable - Executable
	ContractResourceStatusCodesExecutable ContractResourceStatusCodes = "executable"
	// ContractResourceStatusCodesExecuted - Executed
	ContractResourceStatusCodesExecuted ContractResourceStatusCodes = "executed"
	// ContractResourceStatusCodesNegotiable - Negotiable
	ContractResourceStatusCodesNegotiable ContractResourceStatusCodes = "negotiable"
	// ContractResourceStatusCodesOffered - Offered
	ContractResourceStatusCodesOffered ContractResourceStatusCodes = "offered"
	// ContractResourceStatusCodesPolicy - Policy
	ContractResourceStatusCodesPolicy ContractResourceStatusCodes = "policy"
	// ContractResourceStatusCodesRejected - Rejected
	ContractResourceStatusCodesRejected ContractResourceStatusCodes = "rejected"
	// ContractResourceStatusCodesRenewed - Renewed
	ContractResourceStatusCodesRenewed ContractResourceStatusCodes = "renewed"
	// ContractResourceStatusCodesRevoked - Revoked
	ContractResourceStatusCodesRevoked ContractResourceStatusCodes = "revoked"
	// ContractResourceStatusCodesResolved - Resolved
	ContractResourceStatusCodesResolved ContractResourceStatusCodes = "resolved"
	// ContractResourceStatusCodesTerminated - Terminated
	ContractResourceStatusCodesTerminated ContractResourceStatusCodes = "terminated"
)

// ContributorType represents ContributorType.
type ContributorType string

// ContributorType values.
const (
	// ContributorTypeAuthor - Author
	ContributorTypeAuthor ContributorType = "author"
	// ContributorTypeEditor - Editor
	ContributorTypeEditor ContributorType = "editor"
	// ContributorTypeReviewer - Reviewer
	ContributorTypeReviewer ContributorType = "reviewer"
	// ContributorTypeEndorser - Endorser
	ContributorTypeEndorser ContributorType = "endorser"
)

// DetectedIssueSeverity represents DetectedIssueSeverity.
type DetectedIssueSeverity string

// DetectedIssueSeverity values.
const (
	// DetectedIssueSeverityHigh - High
	DetectedIssueSeverityHigh DetectedIssueSeverity = "high"
	// DetectedIssueSeverityModerate - Moderate
	DetectedIssueSeverityModerate DetectedIssueSeverity = "moderate"
	// DetectedIssueSeverityLow - Low
	DetectedIssueSeverityLow DetectedIssueSeverity = "low"
)

// DeviceUseStatementStatus represents DeviceUseStatementStatus.
type DeviceUseStatementStatus string

// DeviceUseStatementStatus values.
const (
	// DeviceUseStatementStatusActive - Active
	DeviceUseStatementStatusActive DeviceUseStatementStatus = "active"
	// DeviceUseStatementStatusCompleted - Completed
	DeviceUseStatementStatusCompleted DeviceUseStatementStatus = "completed"
	// DeviceUseStatementStatusEnteredInError - Entered in Error
	DeviceUseStatementStatusEnteredInError DeviceUseStatementStatus = "entered-in-error"
	// DeviceUseStatementStatusIntended - Intended
	DeviceUseStatementStatusIntended DeviceUseStatementStatus = "intended"
	// DeviceUseStatementStatusStopped - Stopped
	DeviceUseStatementStatusStopped DeviceUseStatementStatus = "stopped"
	// DeviceUseStatementStatusOnHold - On Hold
	DeviceUseStatementStatusOnHold DeviceUseStatementStatus = "on-hold"
)

// FHIRDeviceStatus represents FHIRDeviceStatus.
type FHIRDeviceStatus string

// FHIRDeviceStatus values.
const (
	// FHIRDeviceStatusActive - Active
	FHIRDeviceStatusActive FHIRDeviceStatus = "active"
	// FHIRDeviceStatusInactive - Inactive
	FHIRDeviceStatusInactive FHIRDeviceStatus = "inactive"
	// FHIRDeviceStatusEnteredInError - Entered in Error
	FHIRDeviceStatusEnteredInError FHIRDeviceStatus = "entered-in-error"
	// FHIRDeviceStatusUnknown - Unknown
	FHIRDeviceStatusUnknown FHIRDeviceStatus = "unknown"
)

// DiagnosticReportStatus represents DiagnosticReportStatus.
type DiagnosticReportStatus string

// DiagnosticReportStatus values.
const (
	// DiagnosticReportStatusRegistered - Registered
	DiagnosticReportStatusRegistered DiagnosticReportStatus = "registered"
	// DiagnosticReportStatusPartial - Partial
	DiagnosticReportStatusPartial DiagnosticReportStatus = "partial"
	// DiagnosticReportStatusPreliminary - Preliminary
	DiagnosticReportStatusPreliminary DiagnosticReportStatus = "preliminary"
	// DiagnosticReportStatusFinal - Final
	DiagnosticReportStatusFinal DiagnosticReportStatus = "final"
	// DiagnosticReportStatusAmended - Amended
	DiagnosticReportStatusAmended DiagnosticReportStatus = "amended"
	// DiagnosticReportStatusCorrected - Corrected
	DiagnosticReportStatusCorrected DiagnosticReportStatus = "corrected"
	// DiagnosticReportStatusAppended - Appended
	DiagnosticReportStatusAppended DiagnosticReportStatus = "appended"
	// DiagnosticReportStatusCancelled - Cancelled
	DiagnosticReportStatusCancelled DiagnosticReportStatus = "cancelled"
	// DiagnosticReportStatusEnteredInError - Entered in Error
	DiagnosticReportStatusEnteredInError DiagnosticReportStatus = "entered-in-error"
	// DiagnosticReportStatusUnknown - Unknown
	DiagnosticReportStatusUnknown DiagnosticReportStatus = "unknown"
)

// DocumentReferenceStatus represents DocumentReferenceStatus.
type DocumentReferenceStatus string

// DocumentReferenceStatus values.
const (
	// DocumentReferenceStatusCurrent - Current
	DocumentReferenceStatusCurrent DocumentReferenceStatus = "current"
	// DocumentReferenceStatusSuperseded - Superseded
	DocumentReferenceStatusSuperseded DocumentReferenceStatus = "superseded"
	// DocumentReferenceStatusEnteredInError - Entered in Error
	DocumentReferenceStatusEnteredInError DocumentReferenceStatus = "entered-in-error"
)

// EligibilityRequestPurpose represents EligibilityRequestPurpose.
type EligibilityRequestPurpose string

// EligibilityRequestPurpose values.
const (
	// EligibilityRequestPurposeAuthRequirements - Coverage auth-requirements
	EligibilityRequestPurposeAuthRequirements EligibilityRequestPurpose = "auth-requirements"
	// EligibilityRequestPurposeBenefits - Coverage benefits
	EligibilityRequestPurposeBenefits EligibilityRequestPurpose = "benefits"
	// EligibilityRequestPurposeDiscovery - Coverage Discovery
	EligibilityRequestPurposeDiscovery EligibilityRequestPurpose = "discovery"
	// EligibilityRequestPurposeValidation - Coverage Validation
	EligibilityRequestPurposeValidation EligibilityRequestPurpose = "validation"
)

// EligibilityResponsePurpose represents EligibilityResponsePurpose.
type EligibilityResponsePurpose string

// EligibilityResponsePurpose values.
const (
	// EligibilityResponsePurposeAuthRequirements - Coverage auth-requirements
	EligibilityResponsePurposeAuthRequirements EligibilityResponsePurpose = "auth-requirements"
	// EligibilityResponsePurposeBenefits - Coverage benefits
	EligibilityResponsePurposeBenefits EligibilityResponsePurpose = "benefits"
	// EligibilityResponsePurposeDiscovery - Coverage Discovery
	EligibilityResponsePurposeDiscovery EligibilityResponsePurpose = "discovery"
	// EligibilityResponsePurposeValidation - Coverage Validation
	EligibilityResponsePurposeValidation EligibilityResponsePurpose = "validation"
)

// EncounterStatus represents EncounterStatus.
type EncounterStatus string

// EncounterStatus values.
const (
	// EncounterStatusPlanned - Planned
	EncounterStatusPlanned EncounterStatus = "planned"
	// EncounterStatusArrived - Arrived
	EncounterStatusArrived EncounterStatus = "arrived"
	// EncounterStatusTriaged - Triaged
	EncounterStatusTriaged EncounterStatus = "triaged"
	// EncounterStatusInProgress - In Progress
	EncounterStatusInProgress EncounterStatus = "in-progress"
	// EncounterStatusOnleave - On Leave
	EncounterStatusOnleave EncounterStatus = "onleave"
	// EncounterStatusFinished - Finished
	EncounterStatusFinished EncounterStatus = "finished"
	// EncounterStatusCancelled - Cancelled
	EncounterStatusCancelled EncounterStatus = "cancelled"
	// EncounterStatusEnteredInError - Entered in Error
	EncounterStatusEnteredInError EncounterStatus = "entered-in-error"
	// EncounterStatusUnknown - Unknown
	EncounterStatusUnknown EncounterStatus = "unknown"
)

// EndpointStatus represents EndpointStatus.
type EndpointStatus string

// EndpointStatus values.
const (
	// EndpointStatusActive - Active
	EndpointStatusActive EndpointStatus = "active"
	// EndpointStatusSuspended - Suspended
	EndpointStatusSuspended EndpointStatus = "suspended"
	// EndpointStatusError - Error
	EndpointStatusError EndpointStatus = "error"
	// EndpointStatusOff - Off
	EndpointStatusOff EndpointStatus = "off"
	// EndpointStatusEnteredInError - Entered in error
	EndpointStatusEnteredInError EndpointStatus = "entered-in-error"
	// EndpointStatusTest - Test
	EndpointStatusTest EndpointStatus = "test"
)

// EpisodeOfCareStatus represents EpisodeOfCareStatus.
type EpisodeOfCareStatus string

// EpisodeOfCareStatus values.
const (
	// EpisodeOfCareStatusPlanned - Planned
	EpisodeOfCareStatusPlanned EpisodeOfCareStatus = "planned"
	// EpisodeOfCareStatusWaitlist - Waitlist
	EpisodeOfCareStatusWaitlist EpisodeOfCareStatus = "waitlist"
	// EpisodeOfCareStatusActive - Active
	EpisodeOfCareStatusActive EpisodeOfCareStatus = "active"
	// EpisodeOfCareStatusOnhold - On Hold
	EpisodeOfCareStatusOnhold EpisodeOfCareStatus = "onhold"
	// EpisodeOfCareStatusFinished - Finished
	EpisodeOfCareStatusFinished EpisodeOfCareStatus = "finished"
	// EpisodeOfCareStatusCancelled - Cancelled
	EpisodeOfCareStatusCancelled EpisodeOfCareStatus = "cancelled"
	// EpisodeOfCareStatusEnteredInError - Entered in Error
	EpisodeOfCareStatusEnteredInError EpisodeOfCareStatus = "entered-in-error"
)

// EventStatus represents EventStatus.
type EventStatus string

// EventStatus values.
const (
	// EventStatusPreparation - Preparation
	EventStatusPreparation EventStatus = "preparation"
	// EventStatusInProgress - In Progress
	EventStatusInProgress EventStatus = "in-progress"
	// EventStatusNotDone - Not Done
	EventStatusNotDone EventStatus = "not-done"
	// EventStatusOnHold - On Hold
	EventStatusOnHold EventStatus = "on-hold"
	// EventStatusStopped - Stopped
	EventStatusStopped EventStatus = "stopped"
	// EventStatusCompleted - Completed
	EventStatusCompleted EventStatus = "completed"
	// EventStatusEnteredInError - Entered in Error
	EventStatusEnteredInError EventStatus = "entered-in-error"
	// EventStatusUnknown - Unknown
	EventStatusUnknown EventStatus = "unknown"
)

// ExplanationOfBenefitStatus represents ExplanationOfBenefitStatus.
type ExplanationOfBenefitStatus string

// ExplanationOfBenefitStatus values.
const (
	// ExplanationOfBenefitStatusActive - Active
	ExplanationOfBenefitStatusActive ExplanationOfBenefitStatus = "active"
	// ExplanationOfBenefitStatusCancelled - Cancelled
	ExplanationOfBenefitStatusCancelled ExplanationOfBenefitStatus = "cancelled"
	// ExplanationOfBenefitStatusDraft - Draft
	ExplanationOfBenefitStatusDraft ExplanationOfBenefitStatus = "draft"
	// ExplanationOfBenefitStatusEnteredInError - Entered In Error
	ExplanationOfBenefitStatusEnteredInError ExplanationOfBenefitStatus = "entered-in-error"
)

// FlagStatus represents FlagStatus.
type FlagStatus string

// FlagStatus values.
const (
	// FlagStatusActive - Active
	FlagStatusActive FlagStatus = "active"
	// FlagStatusInactive - Inactive
	FlagStatusInactive FlagStatus = "inactive"
	// FlagStatusEnteredInError - Entered in Error
	FlagStatusEnteredInError FlagStatus = "entered-in-error"
)

// FinancialResourceStatusCodes represents Financial Resource Status Codes.
type FinancialResourceStatusCodes string

// FinancialResourceStatusCodes values.
const (
	// FinancialResourceStatusCodesActive - Active
	FinancialResourceStatusCodesActive FinancialResourceStatusCodes = "active"
	// FinancialResourceStatusCodesCancelled - Cancelled
	FinancialResourceStatusCodesCancelled FinancialResourceStatusCodes = "cancelled"
	// FinancialResourceStatusCodesDraft - Draft
	FinancialResourceStatusCodesDraft FinancialResourceStatusCodes = "draft"
	// FinancialResourceStatusCodesEnteredInError - Entered in Error
	FinancialResourceStatusCodesEnteredInError FinancialResourceStatusCodes = "entered-in-error"
)

// GoalLifecycleStatus represents GoalLifecycleStatus.
type GoalLifecycleStatus string

// GoalLifecycleStatus values.
const (
	// GoalLifecycleStatusProposed - Proposed
	GoalLifecycleStatusProposed GoalLifecycleStatus = "proposed"
	// GoalLifecycleStatusPlanned - Planned
	GoalLifecycleStatusPlanned GoalLifecycleStatus = "planned"
	// GoalLifecycleStatusAccepted - Accepted
	GoalLifecycleStatusAccepted GoalLifecycleStatus = "accepted"
	// GoalLifecycleStatusActive - Active
	GoalLifecycleStatusActive GoalLifecycleStatus = "active"
	// GoalLifecycleStatusOnHold - On Hold
	GoalLifecycleStatusOnHold GoalLifecycleStatus = "on-hold"
	// GoalLifecycleStatusCompleted - Completed
	GoalLifecycleStatusCompleted GoalLifecycleStatus = "completed"
	// GoalLifecycleStatusCancelled - Cancelled
	GoalLifecycleStatusCancelled GoalLifecycleStatus = "cancelled"
	// GoalLifecycleStatusEnteredInError - Entered in Error
	GoalLifecycleStatusEnteredInError GoalLifecycleStatus = "entered-in-error"
	// GoalLifecycleStatusRejected - Rejected
	GoalLifecycleStatusRejected GoalLifecycleStatus = "rejected"
)

// GroupType represents GroupType.
type GroupType string

// GroupType values.
const (
	// GroupTypePerson - Person
	GroupTypePerson GroupType = "person"
	// GroupTypeAnimal - Animal
	GroupTypeAnimal GroupType = "animal"
	// GroupTypePractitioner - Practitioner
	GroupTypePractitioner GroupType = "practitioner"
	// GroupTypeDevice - Device
	GroupTypeDevice GroupType = "device"
	// GroupTypeMedication - Medication
	GroupTypeMedication GroupType = "medication"
	// GroupTypeSubstance - Substance
	GroupTypeSubstance GroupType = "substance"
)

// GuidanceResponseStatus represents GuidanceResponseStatus.
type GuidanceResponseStatus string

// GuidanceResponseStatus values.
const (
	// GuidanceResponseStatusSuccess - Success
	GuidanceResponseStatusSuccess GuidanceResponseStatus = "success"
	// GuidanceResponseStatusDataRequested - Data Requested
	GuidanceResponseStatusDataRequested GuidanceResponseStatus = "data-requested"
	// GuidanceResponseStatusDataRequired - Data Required
	GuidanceResponseStatusDataRequired GuidanceResponseStatus = "data-required"
	// GuidanceResponseStatusInProgress - In Progress
	GuidanceResponseStatusInProgress GuidanceResponseStatus = "in-progress"
	// GuidanceResponseStatusFailure - Failure
	GuidanceResponseStatusFailure GuidanceResponseStatus = "failure"
	// GuidanceResponseStatusEnteredInError - Entered In Error
	GuidanceResponseStatusEnteredInError GuidanceResponseStatus = "entered-in-error"
)

// FamilyHistoryStatus represents FamilyHistoryStatus.
type FamilyHistoryStatus string

// FamilyHistoryStatus values.
const (
	// FamilyHistoryStatusPartial - Partial
	FamilyHistoryStatusPartial FamilyHistoryStatus = "partial"
	// FamilyHistoryStatusCompleted - Completed
	FamilyHistoryStatusCompleted FamilyHistoryStatus = "completed"
	// FamilyHistoryStatusEnteredInError - Entered in Error
	FamilyHistoryStatusEnteredInError FamilyHistoryStatus = "entered-in-error"
	// FamilyHistoryStatusHealthUnknown - Health Unknown
	FamilyHistoryStatusHealthUnknown FamilyHistoryStatus = "health-unknown"
)

// IdentifierUse represents IdentifierUse.
type IdentifierUse string

// IdentifierUse values.
const (
	// IdentifierUseUsual - Usual
	IdentifierUseUsual IdentifierUse = "usual"
	// IdentifierUseOfficial - Official
	IdentifierUseOfficial IdentifierUse = "official"
	// IdentifierUseTemp - Temp
	IdentifierUseTemp IdentifierUse = "temp"
	// IdentifierUseSecondary - Secondary
	IdentifierUseSecondary IdentifierUse = "secondary"
	// IdentifierUseOld - Old
	IdentifierUseOld IdentifierUse = "old"
)

// ImagingStudyStatus represents ImagingStudyStatus.
type ImagingStudyStatus string

// ImagingStudyStatus values.
const (
	// ImagingStudyStatusRegistered - Registered
	ImagingStudyStatusRegistered ImagingStudyStatus = "registered"
	// ImagingStudyStatusAvailable - Available
	ImagingStudyStatusAvailable ImagingStudyStatus = "available"
	// ImagingStudyStatusCancelled - Cancelled
	ImagingStudyStatusCancelled ImagingStudyStatus = "cancelled"
	// ImagingStudyStatusEnteredInError - Entered in Error
	ImagingStudyStatusEnteredInError ImagingStudyStatus = "entered-in-error"
	// ImagingStudyStatusUnknown - Unknown
	ImagingStudyStatusUnknown ImagingStudyStatus = "unknown"
)

// ImmunizationEvaluationStatusCodes represents Immunization Evaluation Status Codes.
type ImmunizationEvaluationStatusCodes string

// ImmunizationEvaluationStatusCodes values.
const (
	ImmunizationEvaluationStatusCodesCompleted      ImmunizationEvaluationStatusCodes = "completed"
	ImmunizationEvaluationStatusCodesEnteredInError ImmunizationEvaluationStatusCodes = "entered-in-error"
)

// ImmunizationStatusCodes represents Immunization Status Codes.
type ImmunizationStatusCodes string

// ImmunizationStatusCodes values.
const (
	ImmunizationStatusCodesCompleted      ImmunizationStatusCodes = "completed"
	ImmunizationStatusCodesEnteredInError ImmunizationStatusCodes = "entered-in-error"
	ImmunizationStatusCodesNotDone        ImmunizationStatusCodes = "not-done"
)

// InvoiceStatus represents InvoiceStatus.
type InvoiceStatus string

// InvoiceStatus values.
const (
	// InvoiceStatusDraft - draft
	InvoiceStatusDraft InvoiceStatus = "draft"
	// InvoiceStatusIssued - issued
	InvoiceStatusIssued InvoiceStatus = "issued"
	// InvoiceStatusBalanced - balanced
	InvoiceStatusBalanced InvoiceStatus = "balanced"
	// InvoiceStatusCancelled - cancelled
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
	// InvoiceStatusEnteredInError - entered in error
	InvoiceStatusEnteredInError InvoiceStatus = "entered-in-error"
)

// ListMode represents ListMode.
type ListMode string

// ListMode values.
const (
	// ListModeWorking - Working List
	ListModeWorking ListMode = "working"
	// ListModeSnapshot - Snapshot List
	ListModeSnapshot ListMode = "snapshot"
	// ListModeChanges - Change List
	ListModeChanges ListMode = "changes"
)

// ListStatus represents ListStatus.
type ListStatus string

// ListStatus values.
const (
	// ListStatusCurrent - Current
	ListStatusCurrent ListStatus = "current"
	// ListStatusRetired - Retired
	ListStatusRetired ListStatus = "retired"
	// ListStatusEnteredInError - Entered In Error
	ListStatusEnteredInError ListStatus = "entered-in-error"
)

// LocationMode represents LocationMode.
type LocationMode string

// LocationMode values.
const (
	// LocationModeInstance - Instance
	LocationModeInstance LocationMode = "instance"
	// LocationModeKind - Kind
	LocationModeKind LocationMode = "kind"
)

// LocationStatus represents LocationStatus.
type LocationStatus string

// LocationStatus values.
const (
	// LocationStatusActive - Active
	LocationStatusActive LocationStatus = "active"
	// LocationStatusSuspended - Suspended
	LocationStatusSuspended LocationStatus = "suspended"
	// LocationStatusInactive - Inactive
	LocationStatusInactive LocationStatus = "inactive"
)

// MeasureReportStatus represents MeasureReportStatus.
type MeasureReportStatus string

// MeasureReportStatus values.
const (
	// MeasureReportStatusComplete - Complete
	MeasureReportStatusComplete MeasureReportStatus = "complete"
	// MeasureReportStatusPending - Pending
	MeasureReportStatusPending MeasureReportStatus = "pending"
	// MeasureReportStatusError - Error
	MeasureReportStatusError MeasureReportStatus = "error"
)

// MeasureReportType represents MeasureReportType.
type MeasureReportType string

// MeasureReportType values.
const (
	// MeasureReportTypeIndividual - Individual
	MeasureReportTypeIndividual MeasureReportType = "individual"
	// MeasureReportTypeSubjectList - Subject List
	MeasureReportTypeSubjectList MeasureReportType = "subject-list"
	// MeasureReportTypeSummary - Summary
	MeasureReportTypeSummary MeasureReportType = "summary"
	// MeasureReportTypeDataCollection - Data Collection
	MeasureReportTypeDataCollection MeasureReportType = "data-collection"
)

// MedicationAdministrationStatusCodes represents allowed values for the MedicationAdministration Status Codes code system.
type MedicationAdministrationStatusCodes string

// MedicationAdministrationStatusCodes values.
const (
	// MedicationAdministrationStatusCodesInProgress - In Progress
	MedicationAdministrationStatusCodesInProgress MedicationAdministrationStatusCodes = "in-progress"
	// MedicationAdministrationStatusCodesNotDone - Not Done
	MedicationAdministrationStatusCodesNotDone MedicationAdministrationStatusCodes = "not-done"
	// MedicationAdministrationStatusCodesOnHold - On Hold
	MedicationAdministrationStatusCodesOnHold MedicationAdministrationStatusCodes = "on-hold"
	// MedicationAdministrationStatusCodesCompleted - Completed
	MedicationAdministrationStatusCodesCompleted MedicationAdministrationStatusCodes = "completed"
	// MedicationAdministrationStatusCodesEnteredInError - Entered in Error
	MedicationAdministrationStatusCodesEnteredInError MedicationAdministrationStatusCodes = "entered-in-error"
	// MedicationAdministrationStatusCodesStopped - Stopped
	MedicationAdministrationStatusCodesStopped MedicationAdministrationStatusCodes = "stopped"
	// MedicationAdministrationStatusCodesUnknown - Unknown
	MedicationAdministrationStatusCodesUnknown MedicationAdministrationStatusCodes = "unknown"
)

// MedicationStatementStatusCodes represents allowed values for the MedicationStatement Status Codes code system.
type MedicationStatementStatusCodes string

// MedicationStatementStatusCodes values.
const (
	// MedicationStatementStatusCodesActive - Active
	MedicationStatementStatusCodesActive MedicationStatementStatusCodes = "active"
	// MedicationStatementStatusCodesCompleted - Completed
	MedicationStatementStatusCodesCompleted MedicationStatementStatusCodes = "completed"
	// MedicationStatementStatusCodesEnteredInError - Entered in Error
	MedicationStatementStatusCodesEnteredInError MedicationStatementStatusCodes = "entered-in-error"
	// MedicationStatementStatusCodesIntended - Intended
	MedicationStatementStatusCodesIntended MedicationStatementStatusCodes = "intended"
	// MedicationStatementStatusCodesStopped - Stopped
	MedicationStatementStatusCodesStopped MedicationStatementStatusCodes = "stopped"
	// MedicationStatementStatusCodesOnHold - On Hold
	MedicationStatementStatusCodesOnHold MedicationStatementStatusCodes = "on-hold"
	// MedicationStatementStatusCodesUnknown - Unknown
	MedicationStatementStatusCodesUnknown MedicationStatementStatusCodes = "unknown"
	// MedicationStatementStatusCodesNotTaken - Not Taken
	MedicationStatementStatusCodesNotTaken MedicationStatementStatusCodes = "not-taken"
)

// MedicationStatusCodes represents allowed values for the Medication Status Codes code system.
type MedicationStatusCodes string

// MedicationStatusCodes values.
const (
	// MedicationStatusCodesActive - Active
	MedicationStatusCodesActive MedicationStatusCodes = "active"
	// MedicationStatusCodesInactive - Inactive
	MedicationStatusCodesInactive MedicationStatusCodes = "inactive"
	// MedicationStatusCodesEnteredInError - Entered in Error
	MedicationStatusCodesEnteredInError MedicationStatusCodes = "entered-in-error"
)

// MedicationDispenseStatusCodes represents allowed values for the MedicationDispense Status Codes code system.
type MedicationDispenseStatusCodes string

// MedicationDispenseStatusCodes values.
const (
	// MedicationDispenseStatusCodesPreparation - Preparation
	MedicationDispenseStatusCodesPreparation MedicationDispenseStatusCodes = "preparation"
	// MedicationDispenseStatusCodesInProgress - In Progress
	MedicationDispenseStatusCodesInProgress MedicationDispenseStatusCodes = "in-progress"
	// MedicationDispenseStatusCodesCancelled - Cancelled
	MedicationDispenseStatusCodesCancelled MedicationDispenseStatusCodes = "cancelled"
	// MedicationDispenseStatusCodesOnHold - On Hold
	MedicationDispenseStatusCodesOnHold MedicationDispenseStatusCodes = "on-hold"
	// MedicationDispenseStatusCodesCompleted - Completed
	MedicationDispenseStatusCodesCompleted MedicationDispenseStatusCodes = "completed"
	// MedicationDispenseStatusCodesEnteredInError - Entered in Error
	MedicationDispenseStatusCodesEnteredInError MedicationDispenseStatusCodes = "entered-in-error"
	// MedicationDispenseStatusCodesStopped - Stopped
	MedicationDispenseStatusCodesStopped MedicationDispenseStatusCodes = "stopped"
	// MedicationDispenseStatusCodesDeclined - Declined
	MedicationDispenseStatusCodesDeclined MedicationDispenseStatusCodes = "declined"
	// MedicationDispenseStatusCodesUnknown - Unknown
	MedicationDispenseStatusCodesUnknown MedicationDispenseStatusCodes = "unknown"
)

// MedicationKnowledgeStatusCodes represents allowed values for the MedicationKnowledge Status Codes code system.
type MedicationKnowledgeStatusCodes string

// MedicationKnowledgeStatusCodes values.
const (
	// MedicationKnowledgeStatusCodesActive - Active
	MedicationKnowledgeStatusCodesActive MedicationKnowledgeStatusCodes = "active"
	// MedicationKnowledgeStatusCodesInactive - Inactive
	MedicationKnowledgeStatusCodesInactive MedicationKnowledgeStatusCodes = "inactive"
	// MedicationKnowledgeStatusCodesEnteredInError - Entered in Error
	MedicationKnowledgeStatusCodesEnteredInError MedicationKnowledgeStatusCodes = "entered-in-error"
)

// MedicationRequestIntent represents allowed values for the medicationRequest Intent code system.
type MedicationRequestIntent string

// MedicationRequestIntent values.
const (
	// MedicationRequestIntentProposal - Proposal
	MedicationRequestIntentProposal MedicationRequestIntent = "proposal"
	// MedicationRequestIntentPlan - Plan
	MedicationRequestIntentPlan MedicationRequestIntent = "plan"
	// MedicationRequestIntentOrder - Order
	MedicationRequestIntentOrder MedicationRequestIntent = "order"
	// MedicationRequestIntentOriginalOrder - Original Order
	MedicationRequestIntentOriginalOrder MedicationRequestIntent = "original-order"
	// MedicationRequestIntentReflexOrder - Reflex Order
	MedicationRequestIntentReflexOrder MedicationRequestIntent = "reflex-order"
	// MedicationRequestIntentFillerOrder - Filler Order
	MedicationRequestIntentFillerOrder MedicationRequestIntent = "filler-order"
	// MedicationRequestIntentInstanceOrder - Instance Order
	MedicationRequestIntentInstanceOrder MedicationRequestIntent = "instance-order"
	// MedicationRequestIntentOption - Option
	MedicationRequestIntentOption MedicationRequestIntent = "option"
)

// MedicationrequestStatus represents allowed values for the medicationrequest Status code system.
type MedicationrequestStatus string

// MedicationrequestStatus values.
const (
	// MedicationrequestStatusActive - Active
	MedicationrequestStatusActive MedicationrequestStatus = "active"
	// MedicationrequestStatusOnHold - On Hold
	MedicationrequestStatusOnHold MedicationrequestStatus = "on-hold"
	// MedicationrequestStatusCancelled - Cancelled
	MedicationrequestStatusCancelled MedicationrequestStatus = "cancelled"
	// MedicationrequestStatusCompleted - Completed
	MedicationrequestStatusCompleted MedicationrequestStatus = "completed"
	// MedicationrequestStatusEnteredInError - Entered in Error
	MedicationrequestStatusEnteredInError MedicationrequestStatus = "entered-in-error"
	// MedicationrequestStatusStopped - Stopped
	MedicationrequestStatusStopped MedicationrequestStatus = "stopped"
	// MedicationrequestStatusDraft - Draft
	MedicationrequestStatusDraft MedicationrequestStatus = "draft"
	// MedicationrequestStatusUnknown - Unknown
	MedicationrequestStatusUnknown MedicationrequestStatus = "unknown"
)

// MessageSignificanceCategory represents MessageSignificanceCategory.
type MessageSignificanceCategory string

// MessageSignificanceCategory values.
const (
	// MessageSignificanceCategoryConsequence - Consequence
	MessageSignificanceCategoryConsequence MessageSignificanceCategory = "consequence"
	// MessageSignificanceCategoryCurrency - Currency
	MessageSignificanceCategoryCurrency MessageSignificanceCategory = "currency"
	// MessageSignificanceCategoryNotification - Notification
	MessageSignificanceCategoryNotification MessageSignificanceCategory = "notification"
)

// Messageheaderresponserequest represents messageheader-response-request.
type Messageheaderresponserequest string

// Messageheaderresponserequest values.
const (
	// MessageheaderresponserequestAlways - Always
	MessageheaderresponserequestAlways Messageheaderresponserequest = "always"
	// MessageheaderresponserequestOnError - Error/reject conditions only
	MessageheaderresponserequestOnError Messageheaderresponserequest = "on-error"
	// MessageheaderresponserequestNever - Never
	MessageheaderresponserequestNever Messageheaderresponserequest = "never"
	// MessageheaderresponserequestOnSuccess - Successful completion only
	MessageheaderresponserequestOnSuccess Messageheaderresponserequest = "on-success"
)

// DeviceMetricCategory represents DeviceMetricCategory.
type DeviceMetricCategory string

// DeviceMetricCategory values.
const (
	// DeviceMetricCategoryMeasurement - Measurement
	DeviceMetricCategoryMeasurement DeviceMetricCategory = "measurement"
	// DeviceMetricCategorySetting - Setting
	DeviceMetricCategorySetting DeviceMetricCategory = "setting"
	// DeviceMetricCategoryCalculation - Calculation
	DeviceMetricCategoryCalculation DeviceMetricCategory = "calculation"
	// DeviceMetricCategoryUnspecified - Unspecified
	DeviceMetricCategoryUnspecified DeviceMetricCategory = "unspecified"
)

// DeviceMetricColor represents DeviceMetricColor.
type DeviceMetricColor string

// DeviceMetricColor values.
const (
	// DeviceMetricColorBlack - Color Black
	DeviceMetricColorBlack DeviceMetricColor = "black"
	// DeviceMetricColorRed - Color Red
	DeviceMetricColorRed DeviceMetricColor = "red"
	// DeviceMetricColorGreen - Color Green
	DeviceMetricColorGreen DeviceMetricColor = "green"
	// DeviceMetricColorYellow - Color Yellow
	DeviceMetricColorYellow DeviceMetricColor = "yellow"
	// DeviceMetricColorBlue - Color Blue
	DeviceMetricColorBlue DeviceMetricColor = "blue"
	// DeviceMetricColorMagenta - Color Magenta
	DeviceMetricColorMagenta DeviceMetricColor = "magenta"
	// DeviceMetricColorCyan - Color Cyan
	DeviceMetricColorCyan DeviceMetricColor = "cyan"
	// DeviceMetricColorWhite - Color White
	DeviceMetricColorWhite DeviceMetricColor = "white"
)

// DeviceMetricOperationalStatus represents DeviceMetricOperationalStatus.
type DeviceMetricOperationalStatus string

// DeviceMetricOperationalStatus values.
const (
	// DeviceMetricOperationalStatusOn - On
	DeviceMetricOperationalStatusOn DeviceMetricOperationalStatus = "on"
	// DeviceMetricOperationalStatusOff - Off
	DeviceMetricOperationalStatusOff DeviceMetricOperationalStatus = "off"
	// DeviceMetricOperationalStatusStandby - Standby
	DeviceMetricOperationalStatusStandby DeviceMetricOperationalStatus = "standby"
	// DeviceMetricOperationalStatusEnteredInError - Entered In Error
	DeviceMetricOperationalStatusEnteredInError DeviceMetricOperationalStatus = "entered-in-error"
)

// NameUse represents NameUse.
type NameUse string

// NameUse values.
const (
	// NameUseUsual - Usual
	NameUseUsual NameUse = "usual"
	// NameUseOfficial - Official
	NameUseOfficial NameUse = "official"
	// NameUseTemp - Temp
	NameUseTemp NameUse = "temp"
	// NameUseNickname - Nickname
	NameUseNickname NameUse = "nickname"
	// NameUseAnonymous - Anonymous
	NameUseAnonymous NameUse = "anonymous"
	// NameUseOld - Old
	NameUseOld NameUse = "old"
	// NameUseMaiden - Name changed for Marriage
	NameUseMaiden NameUse = "maiden"
)

// NamingSystemType represents NamingSystemType.
type NamingSystemType string

// NamingSystemType values.
const (
	// NamingSystemTypeCodesystem - Code System
	NamingSystemTypeCodesystem NamingSystemType = "codesystem"
	// NamingSystemTypeIdentifier - Identifier
	NamingSystemTypeIdentifier NamingSystemType = "identifier"
	// NamingSystemTypeRoot - Root
	NamingSystemTypeRoot NamingSystemType = "root"
)

// NarrativeStatus represents NarrativeStatus.
type NarrativeStatus string

// NarrativeStatus values.
const (
	// NarrativeStatusGenerated - Generated
	NarrativeStatusGenerated NarrativeStatus = "generated"
	// NarrativeStatusExtensions - Extensions
	NarrativeStatusExtensions NarrativeStatus = "extensions"
	// NarrativeStatusAdditional - Additional
	NarrativeStatusAdditional NarrativeStatus = "additional"
	// NarrativeStatusEmpty - Empty
	NarrativeStatusEmpty NarrativeStatus = "empty"
)

// NutritionProductStatus represents NutritionProductStatus.
type NutritionProductStatus string

// NutritionProductStatus values.
const (
	// NutritionProductStatusActive - Active
	NutritionProductStatusActive NutritionProductStatus = "active"
	// NutritionProductStatusInactive - Inactive
	NutritionProductStatusInactive NutritionProductStatus = "inactive"
	// NutritionProductStatusEnteredInError - Entered in Error
	NutritionProductStatusEnteredInError NutritionProductStatus = "entered-in-error"
)

// ObservationStatus represents ObservationStatus.
type ObservationStatus string

// ObservationStatus values.
const (
	// ObservationStatusRegistered - Registered
	ObservationStatusRegistered ObservationStatus = "registered"
	// ObservationStatusPreliminary - Preliminary
	ObservationStatusPreliminary ObservationStatus = "preliminary"
	// ObservationStatusFinal - Final
	ObservationStatusFinal ObservationStatus = "final"
	// ObservationStatusAmended - Amended
	ObservationStatusAmended ObservationStatus = "amended"
	// ObservationStatusCorrected - Corrected
	ObservationStatusCorrected ObservationStatus = "corrected"
	// ObservationStatusCancelled - Cancelled
	ObservationStatusCancelled ObservationStatus = "cancelled"
	// ObservationStatusEnteredInError - Entered in Error
	ObservationStatusEnteredInError ObservationStatus = "entered-in-error"
	// ObservationStatusUnknown - Unknown
	ObservationStatusUnknown ObservationStatus = "unknown"
)

// OperationKind represents OperationKind.
type OperationKind string

// OperationKind values.
const (
	// OperationKindOperation - Operation
	OperationKindOperation OperationKind = "operation"
	// OperationKindQuery - Query
	OperationKindQuery OperationKind = "query"
)

// OperationParameterUse represents OperationParameterUse.
type OperationParameterUse string

// OperationParameterUse values.
const (
	// OperationParameterUseIn - In
	OperationParameterUseIn OperationParameterUse = "in"
	// OperationParameterUseOut - Out
	OperationParameterUseOut OperationParameterUse = "out"
)

// ParticipationStatus represents ParticipationStatus.
type ParticipationStatus string

// ParticipationStatus values.
const (
	// ParticipationStatusAccepted - Accepted
	ParticipationStatusAccepted ParticipationStatus = "accepted"
	// ParticipationStatusDeclined - Declined
	ParticipationStatusDeclined ParticipationStatus = "declined"
	// ParticipationStatusTentative - Tentative
	ParticipationStatusTentative ParticipationStatus = "tentative"
	// ParticipationStatusNeedsAction - Needs Action
	ParticipationStatusNeedsAction ParticipationStatus = "needs-action"
)

// ObservationDataType represents ObservationDataType.
type ObservationDataType string

// ObservationDataType values.
const (
	// ObservationDataTypeQuantity - Quantity
	ObservationDataTypeQuantity ObservationDataType = "Quantity"
	// ObservationDataTypeCodeableconcept - CodeableConcept
	ObservationDataTypeCodeableconcept ObservationDataType = "CodeableConcept"
	// ObservationDataTypeString - string
	ObservationDataTypeString ObservationDataType = "string"
	// ObservationDataTypeBoolean - boolean
	ObservationDataTypeBoolean ObservationDataType = "boolean"
	// ObservationDataTypeInteger - integer
	ObservationDataTypeInteger ObservationDataType = "integer"
	// ObservationDataTypeRange - Range
	ObservationDataTypeRange ObservationDataType = "Range"
	// ObservationDataTypeRatio - Ratio
	ObservationDataTypeRatio ObservationDataType = "Ratio"
	// ObservationDataTypeSampleddata - SampledData
	ObservationDataTypeSampleddata ObservationDataType = "SampledData"
	// ObservationDataTypeTime - time
	ObservationDataTypeTime ObservationDataType = "time"
	// ObservationDataTypeDatetime - dateTime
	ObservationDataTypeDatetime ObservationDataType = "dateTime"
	// ObservationDataTypePeriod - Period
	ObservationDataTypePeriod ObservationDataType = "Period"
)

// BiologicallyDerivedProductCategory represents BiologicallyDerivedProductCategory.
type BiologicallyDerivedProductCategory string

// BiologicallyDerivedProductCategory values.
const (
	// BiologicallyDerivedProductCategoryOrgan - Organ
	BiologicallyDerivedProductCategoryOrgan BiologicallyDerivedProductCategory = "organ"
	// BiologicallyDerivedProductCategoryTissue - Tissue
	BiologicallyDerivedProductCategoryTissue BiologicallyDerivedProductCategory = "tissue"
	// BiologicallyDerivedProductCategoryFluid - Fluid
	BiologicallyDerivedProductCategoryFluid BiologicallyDerivedProductCategory = "fluid"
	// BiologicallyDerivedProductCategoryCells - Cells
	BiologicallyDerivedProductCategoryCells BiologicallyDerivedProductCategory = "cells"
	// BiologicallyDerivedProductCategoryBiologicalagent - BiologicalAgent
	BiologicallyDerivedProductCategoryBiologicalagent BiologicallyDerivedProductCategory = "biologicalAgent"
)

// BiologicallyDerivedProductStatus represents BiologicallyDerivedProductStatus.
type BiologicallyDerivedProductStatus string

// BiologicallyDerivedProductStatus values.
const (
	// BiologicallyDerivedProductStatusAvailable - Available
	BiologicallyDerivedProductStatusAvailable BiologicallyDerivedProductStatus = "available"
	// BiologicallyDerivedProductStatusUnavailable - Unavailable
	BiologicallyDerivedProductStatusUnavailable BiologicallyDerivedProductStatus = "unavailable"
)

// PropertyRepresentation represents PropertyRepresentation.
type PropertyRepresentation string

// PropertyRepresentation values.
const (
	// PropertyRepresentationXmlattr - XML Attribute
	PropertyRepresentationXmlattr PropertyRepresentation = "xmlAttr"
	// PropertyRepresentationXmltext - XML Text
	PropertyRepresentationXmltext PropertyRepresentation = "xmlText"
	// PropertyRepresentationTypeattr - Type Attribute
	PropertyRepresentationTypeattr PropertyRepresentation = "typeAttr"
	// PropertyRepresentationCdatext - CDA Text Format
	PropertyRepresentationCdatext PropertyRepresentation = "cdaText"
	// PropertyRepresentationXhtml - XHTML
	PropertyRepresentationXhtml PropertyRepresentation = "xhtml"
)

// PublicationStatus represents PublicationStatus.
type PublicationStatus string

// PublicationStatus values.
const (
	// PublicationStatusDraft - Draft
	PublicationStatusDraft PublicationStatus = "draft"
	// PublicationStatusActive - Active
	PublicationStatusActive PublicationStatus = "active"
	// PublicationStatusRetired - Retired
	PublicationStatusRetired PublicationStatus = "retired"
	// PublicationStatusUnknown - Unknown
	PublicationStatusUnknown PublicationStatus = "unknown"
)

// QuantityComparator represents QuantityComparator.
type QuantityComparator string

// QuantityComparator values.
const (
	// QuantityComparatorLessThan - Less than
	QuantityComparatorLessThan QuantityComparator = "<"
	// QuantityComparatorLessOrEqual - Less or Equal to
	QuantityComparatorLessOrEqual QuantityComparator = "<="
	// QuantityComparatorGreaterOrEqual - Greater or Equal to
	QuantityComparatorGreaterOrEqual QuantityComparator = ">="
	// QuantityComparatorGreaterThan - Greater than
	QuantityComparatorGreaterThan QuantityComparator = ">"
)

// QuestionnaireResponseStatus represents QuestionnaireResponseStatus.
type QuestionnaireResponseStatus string

// QuestionnaireResponseStatus values.
const (
	// QuestionnaireResponseStatusInProgress - In Progress
	QuestionnaireResponseStatusInProgress QuestionnaireResponseStatus = "in-progress"
	// QuestionnaireResponseStatusCompleted - Completed
	QuestionnaireResponseStatusCompleted QuestionnaireResponseStatus = "completed"
	// QuestionnaireResponseStatusAmended - Amended
	QuestionnaireResponseStatusAmended QuestionnaireResponseStatus = "amended"
	// QuestionnaireResponseStatusEnteredInError - Entered in Error
	QuestionnaireResponseStatusEnteredInError QuestionnaireResponseStatus = "entered-in-error"
	// QuestionnaireResponseStatusStopped - Stopped
	QuestionnaireResponseStatusStopped QuestionnaireResponseStatus = "stopped"
)

// RelatedArtifactType represents RelatedArtifactType.
type RelatedArtifactType string

// RelatedArtifactType values.
const (
	// RelatedArtifactTypeDocumentation - Documentation
	RelatedArtifactTypeDocumentation RelatedArtifactType = "documentation"
	// RelatedArtifactTypeJustification - Justification
	RelatedArtifactTypeJustification RelatedArtifactType = "justification"
	// RelatedArtifactTypeCitation - Citation
	RelatedArtifactTypeCitation RelatedArtifactType = "citation"
	// RelatedArtifactTypePredecessor - Predecessor
	RelatedArtifactTypePredecessor RelatedArtifactType = "predecessor"
	// RelatedArtifactTypeSuccessor - Successor
	RelatedArtifactTypeSuccessor RelatedArtifactType = "successor"
	// RelatedArtifactTypeDerivedFrom - Derived From
	RelatedArtifactTypeDerivedFrom RelatedArtifactType = "derived-from"
	// RelatedArtifactTypeDependsOn - Depends On
	RelatedArtifactTypeDependsOn RelatedArtifactType = "depends-on"
	// RelatedArtifactTypeComposedOf - Composed Of
	RelatedArtifactTypeComposedOf RelatedArtifactType = "composed-of"
)

// RemittanceOutcome represents RemittanceOutcome.
type RemittanceOutcome string

// RemittanceOutcome values.
const (
	// RemittanceOutcomeQueued - Queued
	RemittanceOutcomeQueued RemittanceOutcome = "queued"
	// RemittanceOutcomeComplete - Complete
	RemittanceOutcomeComplete RemittanceOutcome = "complete"
	// RemittanceOutcomeError - Error
	RemittanceOutcomeError RemittanceOutcome = "error"
	// RemittanceOutcomePartial - Partial
	RemittanceOutcomePartial RemittanceOutcome = "partial"
)

// TestReportResult represents TestReportResult.
type TestReportResult string

// TestReportResult values.
const (
	// TestReportResultPass - Pass
	TestReportResultPass TestReportResult = "pass"
	// TestReportResultFail - Fail
	TestReportResultFail TestReportResult = "fail"
	// TestReportResultPending - Pending
	TestReportResultPending TestReportResult = "pending"
)

// TestReportStatus represents TestReportStatus.
type TestReportStatus string

// TestReportStatus values.
const (
	// TestReportStatusCompleted - Completed
	TestReportStatusCompleted TestReportStatus = "completed"
	// TestReportStatusInProgress - In Progress
	TestReportStatusInProgress TestReportStatus = "in-progress"
	// TestReportStatusWaiting - Waiting
	TestReportStatusWaiting TestReportStatus = "waiting"
	// TestReportStatusStopped - Stopped
	TestReportStatusStopped TestReportStatus = "stopped"
	// TestReportStatusEnteredInError - Entered In Error
	TestReportStatusEnteredInError TestReportStatus = "entered-in-error"
)

// RequestIntent represents RequestIntent.
type RequestIntent string

// RequestIntent values.
const (
	// RequestIntentProposal - Proposal
	RequestIntentProposal RequestIntent = "proposal"
	// RequestIntentPlan - Plan
	RequestIntentPlan RequestIntent = "plan"
	// RequestIntentDirective - Directive
	RequestIntentDirective RequestIntent = "directive"
	// RequestIntentOrder - Order
	RequestIntentOrder RequestIntent = "order"
	// RequestIntentOriginalOrder - Original Order
	RequestIntentOriginalOrder RequestIntent = "original-order"
	// RequestIntentReflexOrder - Reflex Order
	RequestIntentReflexOrder RequestIntent = "reflex-order"
	// RequestIntentFillerOrder - Filler Order
	RequestIntentFillerOrder RequestIntent = "filler-order"
	// RequestIntentInstanceOrder - Instance Order
	RequestIntentInstanceOrder RequestIntent = "instance-order"
	// RequestIntentOption - Option
	RequestIntentOption RequestIntent = "option"
)

// RequestPriority represents RequestPriority.
type RequestPriority string

// RequestPriority values.
const (
	// RequestPriorityRoutine - Routine
	RequestPriorityRoutine RequestPriority = "routine"
	// RequestPriorityUrgent - Urgent
	RequestPriorityUrgent RequestPriority = "urgent"
	// RequestPriorityAsap - ASAP
	RequestPriorityAsap RequestPriority = "asap"
	// RequestPriorityStat - STAT
	RequestPriorityStat RequestPriority = "stat"
)

// RequestResourceType represents RequestResourceType.
type RequestResourceType string

// RequestResourceType values.
const (
	// RequestResourceTypeAppointment - Appointment
	RequestResourceTypeAppointment RequestResourceType = "Appointment"
	// RequestResourceTypeAppointmentresponse - AppointmentResponse
	RequestResourceTypeAppointmentresponse RequestResourceType = "AppointmentResponse"
	// RequestResourceTypeCareplan - CarePlan
	RequestResourceTypeCareplan RequestResourceType = "CarePlan"
	// RequestResourceTypeClaim - Claim
	RequestResourceTypeClaim RequestResourceType = "Claim"
	// RequestResourceTypeCommunicationrequest - CommunicationRequest
	RequestResourceTypeCommunicationrequest RequestResourceType = "CommunicationRequest"
	// RequestResourceTypeContract - Contract
	RequestResourceTypeContract RequestResourceType = "Contract"
	// RequestResourceTypeDevicerequest - DeviceRequest
	RequestResourceTypeDevicerequest RequestResourceType = "DeviceRequest"
	// RequestResourceTypeEnrollmentrequest - EnrollmentRequest
	RequestResourceTypeEnrollmentrequest RequestResourceType = "EnrollmentRequest"
	// RequestResourceTypeImmunizationrecommendation - ImmunizationRecommendation
	RequestResourceTypeImmunizationrecommendation RequestResourceType = "ImmunizationRecommendation"
	// RequestResourceTypeMedicationrequest - MedicationRequest
	RequestResourceTypeMedicationrequest RequestResourceType = "MedicationRequest"
	// RequestResourceTypeNutritionorder - NutritionOrder
	RequestResourceTypeNutritionorder RequestResourceType = "NutritionOrder"
	// RequestResourceTypeServicerequest - ServiceRequest
	RequestResourceTypeServicerequest RequestResourceType = "ServiceRequest"
	// RequestResourceTypeSupplyrequest - SupplyRequest
	RequestResourceTypeSupplyrequest RequestResourceType = "SupplyRequest"
	// RequestResourceTypeTask - Task
	RequestResourceTypeTask RequestResourceType = "Task"
	// RequestResourceTypeVisionprescription - VisionPrescription
	RequestResourceTypeVisionprescription RequestResourceType = "VisionPrescription"
)

// RequestStatus represents RequestStatus.
type RequestStatus string

// RequestStatus values.
const (
	// RequestStatusDraft - Draft
	RequestStatusDraft RequestStatus = "draft"
	// RequestStatusActive - Active
	RequestStatusActive RequestStatus = "active"
	// RequestStatusOnHold - On Hold
	RequestStatusOnHold RequestStatus = "on-hold"
	// RequestStatusRevoked - Revoked
	RequestStatusRevoked RequestStatus = "revoked"
	// RequestStatusCompleted - Completed
	RequestStatusCompleted RequestStatus = "completed"
	// RequestStatusEnteredInError - Entered in Error
	RequestStatusEnteredInError RequestStatus = "entered-in-error"
	// RequestStatusUnknown - Unknown
	RequestStatusUnknown RequestStatus = "unknown"
)

// ResearchElementType represents ResearchElementType.
type ResearchElementType string

// ResearchElementType values.
const (
	// ResearchElementTypePopulation - Population
	ResearchElementTypePopulation ResearchElementType = "population"
	// ResearchElementTypeExposure - Exposure
	ResearchElementTypeExposure ResearchElementType = "exposure"
	// ResearchElementTypeOutcome - Outcome
	ResearchElementTypeOutcome ResearchElementType = "outcome"
)

// ResearchStudyStatus represents ResearchStudyStatus.
type ResearchStudyStatus string

// ResearchStudyStatus values.
const (
	// ResearchStudyStatusActive - Active
	ResearchStudyStatusActive ResearchStudyStatus = "active"
	// ResearchStudyStatusAdministrativelyCompleted - Administratively Completed
	ResearchStudyStatusAdministrativelyCompleted ResearchStudyStatus = "administratively-completed"
	// ResearchStudyStatusApproved - Approved
	ResearchStudyStatusApproved ResearchStudyStatus = "approved"
	// ResearchStudyStatusClosedToAccrual - Closed to Accrual
	ResearchStudyStatusClosedToAccrual ResearchStudyStatus = "closed-to-accrual"
	// ResearchStudyStatusClosedToAccrualAndIntervention - Closed to Accrual and Intervention
	ResearchStudyStatusClosedToAccrualAndIntervention ResearchStudyStatus = "closed-to-accrual-and-intervention"
	// ResearchStudyStatusCompleted - Completed
	ResearchStudyStatusCompleted ResearchStudyStatus = "completed"
	// ResearchStudyStatusDisapproved - Disapproved
	ResearchStudyStatusDisapproved ResearchStudyStatus = "disapproved"
	// ResearchStudyStatusInReview - In Review
	ResearchStudyStatusInReview ResearchStudyStatus = "in-review"
	// ResearchStudyStatusTemporarilyClosedToAccrual - Temporarily Closed to Accrual
	ResearchStudyStatusTemporarilyClosedToAccrual ResearchStudyStatus = "temporarily-closed-to-accrual"
	// ResearchStudyStatusTemporarilyClosedToAccrualAndIntervention - Temporarily Closed to Accrual and Intervention
	ResearchStudyStatusTemporarilyClosedToAccrualAndIntervention ResearchStudyStatus = "temporarily-closed-to-accrual-and-intervention"
	// ResearchStudyStatusWithdrawn - Withdrawn
	ResearchStudyStatusWithdrawn ResearchStudyStatus = "withdrawn"
)

// ResearchSubjectStatus represents ResearchSubjectStatus.
type ResearchSubjectStatus string

// ResearchSubjectStatus values.
const (
	// ResearchSubjectStatusCandidate - Candidate
	ResearchSubjectStatusCandidate ResearchSubjectStatus = "candidate"
	// ResearchSubjectStatusEligible - Eligible
	ResearchSubjectStatusEligible ResearchSubjectStatus = "eligible"
	// ResearchSubjectStatusFollowUp - Follow-up
	ResearchSubjectStatusFollowUp ResearchSubjectStatus = "follow-up"
	// ResearchSubjectStatusIneligible - Ineligible
	ResearchSubjectStatusIneligible ResearchSubjectStatus = "ineligible"
	// ResearchSubjectStatusNotRegistered - Not Registered
	ResearchSubjectStatusNotRegistered ResearchSubjectStatus = "not-registered"
	// ResearchSubjectStatusOffStudy - Off-study
	ResearchSubjectStatusOffStudy ResearchSubjectStatus = "off-study"
	// ResearchSubjectStatusOnStudy - On-study
	ResearchSubjectStatusOnStudy ResearchSubjectStatus = "on-study"
	// ResearchSubjectStatusOnStudyIntervention - On-study-intervention
	ResearchSubjectStatusOnStudyIntervention ResearchSubjectStatus = "on-study-intervention"
	// ResearchSubjectStatusOnStudyObservation - On-study-observation
	ResearchSubjectStatusOnStudyObservation ResearchSubjectStatus = "on-study-observation"
	// ResearchSubjectStatusPendingOnStudy - Pending on-study
	ResearchSubjectStatusPendingOnStudy ResearchSubjectStatus = "pending-on-study"
	// ResearchSubjectStatusPotentialCandidate - Potential Candidate
	ResearchSubjectStatusPotentialCandidate ResearchSubjectStatus = "potential-candidate"
	// ResearchSubjectStatusScreening - Screening
	ResearchSubjectStatusScreening ResearchSubjectStatus = "screening"
	// ResearchSubjectStatusWithdrawn - Withdrawn
	ResearchSubjectStatusWithdrawn ResearchSubjectStatus = "withdrawn"
)

// SearchComparator represents SearchComparator.
type SearchComparator string

// SearchComparator values.
const (
	// SearchComparatorEq - Equals
	SearchComparatorEq SearchComparator = "eq"
	// SearchComparatorNe - Not Equals
	SearchComparatorNe SearchComparator = "ne"
	// SearchComparatorGt - Greater Than
	SearchComparatorGt SearchComparator = "gt"
	// SearchComparatorLt - Less Than
	SearchComparatorLt SearchComparator = "lt"
	// SearchComparatorGe - Greater or Equals
	SearchComparatorGe SearchComparator = "ge"
	// SearchComparatorLe - Less of Equal
	SearchComparatorLe SearchComparator = "le"
	// SearchComparatorSa - Starts After
	SearchComparatorSa SearchComparator = "sa"
	// SearchComparatorEb - Ends Before
	SearchComparatorEb SearchComparator = "eb"
	// SearchComparatorAp - Approximately
	SearchComparatorAp SearchComparator = "ap"
)

// SearchModifierCode represents SearchModifierCode.
type SearchModifierCode string

// SearchModifierCode values.
const (
	// SearchModifierCodeMissing - Missing
	SearchModifierCodeMissing SearchModifierCode = "missing"
	// SearchModifierCodeExact - Exact
	SearchModifierCodeExact SearchModifierCode = "exact"
	// SearchModifierCodeContains - Contains
	SearchModifierCodeContains SearchModifierCode = "contains"
	// SearchModifierCodeNot - Not
	SearchModifierCodeNot SearchModifierCode = "not"
	// SearchModifierCodeText - Text
	SearchModifierCodeText SearchModifierCode = "text"
	// SearchModifierCodeIn - In
	SearchModifierCodeIn SearchModifierCode = "in"
	// SearchModifierCodeNotIn - Not In
	SearchModifierCodeNotIn SearchModifierCode = "not-in"
	// SearchModifierCodeBelow - Below
	SearchModifierCodeBelow SearchModifierCode = "below"
	// SearchModifierCodeAbove - Above
	SearchModifierCodeAbove SearchModifierCode = "above"
	// SearchModifierCodeType - Type
	SearchModifierCodeType SearchModifierCode = "type"
	// SearchModifierCodeIdentifier - Identifier
	SearchModifierCodeIdentifier SearchModifierCode = "identifier"
	// SearchModifierCodeOftype - Of Type
	SearchModifierCodeOftype SearchModifierCode = "ofType"
)

// SearchParamType represents SearchParamType.
type SearchParamType string

// SearchParamType values.
const (
	// SearchParamTypeNumber - Number
	SearchParamTypeNumber SearchParamType = "number"
	// SearchParamTypeDate - Date/DateTime
	SearchParamTypeDate SearchParamType = "date"
	// SearchParamTypeString - String
	SearchParamTypeString SearchParamType = "string"
	// SearchParamTypeToken - Token
	SearchParamTypeToken SearchParamType = "token"
	// SearchParamTypeReference - Reference
	SearchParamTypeReference SearchParamType = "reference"
	// SearchParamTypeComposite - Composite
	SearchParamTypeComposite SearchParamType = "composite"
	// SearchParamTypeQuantity - Quantity
	SearchParamTypeQuantity SearchParamType = "quantity"
	// SearchParamTypeUri - URI
	SearchParamTypeUri SearchParamType = "uri"
	// SearchParamTypeSpecial - Special
	SearchParamTypeSpecial SearchParamType = "special"
)

// XPathUsageType represents XPathUsageType.
type XPathUsageType string

// XPathUsageType values.
const (
	// XPathUsageTypeNormal - Normal
	XPathUsageTypeNormal XPathUsageType = "normal"
	// XPathUsageTypePhonetic - Phonetic
	XPathUsageTypePhonetic XPathUsageType = "phonetic"
	// XPathUsageTypeNearby - Nearby
	XPathUsageTypeNearby XPathUsageType = "nearby"
	// XPathUsageTypeDistance - Distance
	XPathUsageTypeDistance XPathUsageType = "distance"
	// XPathUsageTypeOther - Other
	XPathUsageTypeOther XPathUsageType = "other"
)

// SequenceType represents sequenceType.
type SequenceType string

// SequenceType values.
const (
	// SequenceTypeAa - AA Sequence
	SequenceTypeAa SequenceType = "aa"
	// SequenceTypeDna - DNA Sequence
	SequenceTypeDna SequenceType = "dna"
	// SequenceTypeRna - RNA Sequence
	SequenceTypeRna SequenceType = "rna"
)

// SlotStatus represents SlotStatus.
type SlotStatus string

// SlotStatus values.
const (
	// SlotStatusBusy - Busy
	SlotStatusBusy SlotStatus = "busy"
	// SlotStatusFree - Free
	SlotStatusFree SlotStatus = "free"
	// SlotStatusBusyUnavailable - Busy (Unavailable)
	SlotStatusBusyUnavailable SlotStatus = "busy-unavailable"
	// SlotStatusBusyTentative - Busy (Tentative)
	SlotStatusBusyTentative SlotStatus = "busy-tentative"
	// SlotStatusEnteredInError - Entered in error
	SlotStatusEnteredInError SlotStatus = "entered-in-error"
)

// SpecimenStatus represents SpecimenStatus.
type SpecimenStatus string

// SpecimenStatus values.
const (
	// SpecimenStatusAvailable - Available
	SpecimenStatusAvailable SpecimenStatus = "available"
	// SpecimenStatusUnavailable - Unavailable
	SpecimenStatusUnavailable SpecimenStatus = "unavailable"
	// SpecimenStatusUnsatisfactory - Unsatisfactory
	SpecimenStatusUnsatisfactory SpecimenStatus = "unsatisfactory"
	// SpecimenStatusEnteredInError - Entered in Error
	SpecimenStatusEnteredInError SpecimenStatus = "entered-in-error"
)

// StructureDefinitionKind represents StructureDefinitionKind.
type StructureDefinitionKind string

// StructureDefinitionKind values.
const (
	// StructureDefinitionKindPrimitiveType - Primitive Data Type
	StructureDefinitionKindPrimitiveType StructureDefinitionKind = "primitive-type"
	// StructureDefinitionKindComplexType - Complex Data Type
	StructureDefinitionKindComplexType StructureDefinitionKind = "complex-type"
	// StructureDefinitionKindResource - Resource
	StructureDefinitionKindResource StructureDefinitionKind = "resource"
	// StructureDefinitionKindLogical - Logical
	StructureDefinitionKindLogical StructureDefinitionKind = "logical"
)

// SubscriptionNotificationType represents SubscriptionNotificationType.
type SubscriptionNotificationType string

// SubscriptionNotificationType values.
const (
	// SubscriptionNotificationTypeHandshake - Handshake
	SubscriptionNotificationTypeHandshake SubscriptionNotificationType = "handshake"
	// SubscriptionNotificationTypeHeartbeat - Heartbeat
	SubscriptionNotificationTypeHeartbeat SubscriptionNotificationType = "heartbeat"
	// SubscriptionNotificationTypeEventNotification - Event Notification
	SubscriptionNotificationTypeEventNotification SubscriptionNotificationType = "event-notification"
	// SubscriptionNotificationTypeQueryStatus - Query Status
	SubscriptionNotificationTypeQueryStatus SubscriptionNotificationType = "query-status"
	// SubscriptionNotificationTypeQueryEvent - Query Event
	SubscriptionNotificationTypeQueryEvent SubscriptionNotificationType = "query-event"
)

// SubscriptionStatusCodes represents SubscriptionStatusCodes.
type SubscriptionStatusCodes string

// SubscriptionStatusCodes values.
const (
	// SubscriptionStatusCodesRequested - Requested
	SubscriptionStatusCodesRequested SubscriptionStatusCodes = "requested"
	// SubscriptionStatusCodesActive - Active
	SubscriptionStatusCodesActive SubscriptionStatusCodes = "active"
	// SubscriptionStatusCodesError - Error
	SubscriptionStatusCodesError SubscriptionStatusCodes = "error"
	// SubscriptionStatusCodesOff - Off
	SubscriptionStatusCodesOff SubscriptionStatusCodes = "off"
)

// FHIRSubstanceStatus represents FHIRSubstanceStatus.
type FHIRSubstanceStatus string

// FHIRSubstanceStatus values.
const (
	// FHIRSubstanceStatusActive - Active
	FHIRSubstanceStatusActive FHIRSubstanceStatus = "active"
	// FHIRSubstanceStatusInactive - Inactive
	FHIRSubstanceStatusInactive FHIRSubstanceStatus = "inactive"
	// FHIRSubstanceStatusEnteredInError - Entered in Error
	FHIRSubstanceStatusEnteredInError FHIRSubstanceStatus = "entered-in-error"
)

// SupplyDeliveryStatus represents SupplyDeliveryStatus.
type SupplyDeliveryStatus string

// SupplyDeliveryStatus values.
const (
	// SupplyDeliveryStatusInProgress - In Progress
	SupplyDeliveryStatusInProgress SupplyDeliveryStatus = "in-progress"
	// SupplyDeliveryStatusCompleted - Delivered
	SupplyDeliveryStatusCompleted SupplyDeliveryStatus = "completed"
	// SupplyDeliveryStatusAbandoned - Abandoned
	SupplyDeliveryStatusAbandoned SupplyDeliveryStatus = "abandoned"
	// SupplyDeliveryStatusEnteredInError - Entered In Error
	SupplyDeliveryStatusEnteredInError SupplyDeliveryStatus = "entered-in-error"
)

// SupplyRequestStatus represents SupplyRequestStatus.
type SupplyRequestStatus string

// SupplyRequestStatus values.
const (
	// SupplyRequestStatusDraft - Draft
	SupplyRequestStatusDraft SupplyRequestStatus = "draft"
	// SupplyRequestStatusActive - Active
	SupplyRequestStatusActive SupplyRequestStatus = "active"
	// SupplyRequestStatusSuspended - Suspended
	SupplyRequestStatusSuspended SupplyRequestStatus = "suspended"
	// SupplyRequestStatusCancelled - Cancelled
	SupplyRequestStatusCancelled SupplyRequestStatus = "cancelled"
	// SupplyRequestStatusCompleted - Completed
	SupplyRequestStatusCompleted SupplyRequestStatus = "completed"
	// SupplyRequestStatusEnteredInError - Entered in Error
	SupplyRequestStatusEnteredInError SupplyRequestStatus = "entered-in-error"
	// SupplyRequestStatusUnknown - Unknown
	SupplyRequestStatusUnknown SupplyRequestStatus = "unknown"
)

// TaskIntent represents TaskIntent.
type TaskIntent string

// TaskIntent values.
const (
	// TaskIntentUnknown - Unknown
	TaskIntentUnknown       TaskIntent = "unknown"
	TaskIntentProposal      TaskIntent = "proposal"
	TaskIntentPlan          TaskIntent = "plan"
	TaskIntentOrder         TaskIntent = "order"
	TaskIntentOriginalOrder TaskIntent = "original-order"
	TaskIntentReflexOrder   TaskIntent = "reflex-order"
	TaskIntentFillerOrder   TaskIntent = "filler-order"
	TaskIntentInstanceOrder TaskIntent = "instance-order"
	TaskIntentOption        TaskIntent = "option"
)

// TaskStatus represents TaskStatus.
type TaskStatus string

// TaskStatus values.
const (
	// TaskStatusDraft - Draft
	TaskStatusDraft TaskStatus = "draft"
	// TaskStatusRequested - Requested
	TaskStatusRequested TaskStatus = "requested"
	// TaskStatusReceived - Received
	TaskStatusReceived TaskStatus = "received"
	// TaskStatusAccepted - Accepted
	TaskStatusAccepted TaskStatus = "accepted"
	// TaskStatusRejected - Rejected
	TaskStatusRejected TaskStatus = "rejected"
	// TaskStatusReady - Ready
	TaskStatusReady TaskStatus = "ready"
	// TaskStatusCancelled - Cancelled
	TaskStatusCancelled TaskStatus = "cancelled"
	// TaskStatusInProgress - In Progress
	TaskStatusInProgress TaskStatus = "in-progress"
	// TaskStatusOnHold - On Hold
	TaskStatusOnHold TaskStatus = "on-hold"
	// TaskStatusFailed - Failed
	TaskStatusFailed TaskStatus = "failed"
	// TaskStatusCompleted - Completed
	TaskStatusCompleted TaskStatus = "completed"
	// TaskStatusEnteredInError - Entered in Error
	TaskStatusEnteredInError TaskStatus = "entered-in-error"
)

// TriggerType represents TriggerType.
type TriggerType string

// TriggerType values.
const (
	// TriggerTypeNamedEvent - Named Event
	TriggerTypeNamedEvent TriggerType = "named-event"
	// TriggerTypePeriodic - Periodic
	TriggerTypePeriodic TriggerType = "periodic"
	// TriggerTypeDataChanged - Data Changed
	TriggerTypeDataChanged TriggerType = "data-changed"
	// TriggerTypeDataAdded - Data Added
	TriggerTypeDataAdded TriggerType = "data-added"
	// TriggerTypeDataModified - Data Updated
	TriggerTypeDataModified TriggerType = "data-modified"
	// TriggerTypeDataRemoved - Data Removed
	TriggerTypeDataRemoved TriggerType = "data-removed"
	// TriggerTypeDataAccessed - Data Accessed
	TriggerTypeDataAccessed TriggerType = "data-accessed"
	// TriggerTypeDataAccessEnded - Data Access Ended
	TriggerTypeDataAccessEnded TriggerType = "data-access-ended"
)

// TypeDerivationRule represents TypeDerivationRule.
type TypeDerivationRule string

// TypeDerivationRule values.
const (
	// TypeDerivationRuleSpecialization - Specialization
	TypeDerivationRuleSpecialization TypeDerivationRule = "specialization"
	// TypeDerivationRuleConstraint - Constraint
	TypeDerivationRuleConstraint TypeDerivationRule = "constraint"
)

// EvidenceVariableHandling represents EvidenceVariableHandling.
type EvidenceVariableHandling string

// EvidenceVariableHandling values.
const (
	// EvidenceVariableHandlingContinuous - continuous variable
	EvidenceVariableHandlingContinuous EvidenceVariableHandling = "continuous"
	// EvidenceVariableHandlingDichotomous - dichotomous variable
	EvidenceVariableHandlingDichotomous EvidenceVariableHandling = "dichotomous"
	// EvidenceVariableHandlingOrdinal - ordinal variable
	EvidenceVariableHandlingOrdinal EvidenceVariableHandling = "ordinal"
	// EvidenceVariableHandlingPolychotomous - polychotomous variable
	EvidenceVariableHandlingPolychotomous EvidenceVariableHandling = "polychotomous"
)

// VariableType represents VariableType.
type VariableType string

// VariableType values.
const (
	// VariableTypeDichotomous - Dichotomous
	VariableTypeDichotomous VariableType = "dichotomous"
	// VariableTypeContinuous - Continuous
	VariableTypeContinuous VariableType = "continuous"
	// VariableTypeDescriptive - Descriptive
	VariableTypeDescriptive VariableType = "descriptive"
)

// Status represents allowed values for the status code system.
type Status string

// Status values.
const (
	// StatusAttested - Attested
	StatusAttested Status = "attested"
	// StatusValidated - Validated
	StatusValidated Status = "validated"
	// StatusInProcess - In process
	StatusInProcess Status = "in-process"
	// StatusReqRevalid - Requires revalidation
	StatusReqRevalid Status = "req-revalid"
	// StatusValFail - Validation failed
	StatusValFail Status = "val-fail"
	// StatusRevalFail - Re-Validation failed
	StatusRevalFail Status = "reval-fail"
)
