// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// NutritionProduct - Functional Options
// =============================================================================

// NutritionProductOption is a functional option for configuring a NutritionProduct.
type NutritionProductOption func(*NutritionProduct)

// NewNutritionProduct creates a new NutritionProduct with the given options.
func NewNutritionProduct(opts ...NutritionProductOption) *NutritionProduct {
	r := &NutritionProduct{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithNutritionProductId sets the Id field.
func WithNutritionProductId(v string) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Id = &v
	}
}

// WithNutritionProductMeta sets the Meta field.
func WithNutritionProductMeta(v Meta) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Meta = &v
	}
}

// WithNutritionProductImplicitRules sets the ImplicitRules field.
func WithNutritionProductImplicitRules(v string) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.ImplicitRules = &v
	}
}

// WithNutritionProductLanguage sets the Language field.
func WithNutritionProductLanguage(v string) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Language = &v
	}
}

// WithNutritionProductText sets the Text field.
func WithNutritionProductText(v Narrative) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Text = &v
	}
}

// WithNutritionProductContained adds a Contained to the NutritionProduct.
func WithNutritionProductContained(v Resource) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Contained = append(r.Contained, v)
	}
}

// WithNutritionProductExtension adds a Extension to the NutritionProduct.
func WithNutritionProductExtension(v Extension) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Extension = append(r.Extension, v)
	}
}

// WithNutritionProductModifierExtension adds a ModifierExtension to the NutritionProduct.
func WithNutritionProductModifierExtension(v Extension) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithNutritionProductStatus sets the Status field.
func WithNutritionProductStatus(v NutritionProductStatus) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Status = &v
	}
}

// WithNutritionProductCategory adds a Category to the NutritionProduct.
func WithNutritionProductCategory(v CodeableConcept) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Category = append(r.Category, v)
	}
}

// WithNutritionProductCode sets the Code field.
func WithNutritionProductCode(v CodeableConcept) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Code = &v
	}
}

// WithNutritionProductManufacturer adds a Manufacturer to the NutritionProduct.
func WithNutritionProductManufacturer(v Reference) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Manufacturer = append(r.Manufacturer, v)
	}
}

// WithNutritionProductNutrient adds a Nutrient to the NutritionProduct.
func WithNutritionProductNutrient(v NutritionProductNutrient) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Nutrient = append(r.Nutrient, v)
	}
}

// WithNutritionProductIngredient adds a Ingredient to the NutritionProduct.
func WithNutritionProductIngredient(v NutritionProductIngredient) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Ingredient = append(r.Ingredient, v)
	}
}

// WithNutritionProductKnownAllergen adds a KnownAllergen to the NutritionProduct.
func WithNutritionProductKnownAllergen(v CodeableReference) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.KnownAllergen = append(r.KnownAllergen, v)
	}
}

// WithNutritionProductProductCharacteristic adds a ProductCharacteristic to the NutritionProduct.
func WithNutritionProductProductCharacteristic(v NutritionProductProductCharacteristic) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.ProductCharacteristic = append(r.ProductCharacteristic, v)
	}
}

// WithNutritionProductInstance sets the Instance field.
func WithNutritionProductInstance(v NutritionProductInstance) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Instance = &v
	}
}

// WithNutritionProductNote adds a Note to the NutritionProduct.
func WithNutritionProductNote(v Annotation) NutritionProductOption {
	return func(r *NutritionProduct) {
		r.Note = append(r.Note, v)
	}
}
