// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// ActivityDefinition - Functional Options
// =============================================================================

// ActivityDefinitionOption is a functional option for configuring a ActivityDefinition.
type ActivityDefinitionOption func(*ActivityDefinition)

// NewActivityDefinition creates a new ActivityDefinition with the given options.
func NewActivityDefinition(opts ...ActivityDefinitionOption) *ActivityDefinition {
	r := &ActivityDefinition{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithActivityDefinitionId sets the Id field.
func WithActivityDefinitionId(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Id = &v
	}
}

// WithActivityDefinitionMeta sets the Meta field.
func WithActivityDefinitionMeta(v Meta) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Meta = &v
	}
}

// WithActivityDefinitionImplicitRules sets the ImplicitRules field.
func WithActivityDefinitionImplicitRules(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ImplicitRules = &v
	}
}

// WithActivityDefinitionLanguage sets the Language field.
func WithActivityDefinitionLanguage(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Language = &v
	}
}

// WithActivityDefinitionText sets the Text field.
func WithActivityDefinitionText(v Narrative) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Text = &v
	}
}

// WithActivityDefinitionContained adds a Contained to the ActivityDefinition.
func WithActivityDefinitionContained(v Resource) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Contained = append(r.Contained, v)
	}
}

// WithActivityDefinitionExtension adds a Extension to the ActivityDefinition.
func WithActivityDefinitionExtension(v Extension) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Extension = append(r.Extension, v)
	}
}

// WithActivityDefinitionModifierExtension adds a ModifierExtension to the ActivityDefinition.
func WithActivityDefinitionModifierExtension(v Extension) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithActivityDefinitionUrl sets the Url field.
func WithActivityDefinitionUrl(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Url = &v
	}
}

// WithActivityDefinitionIdentifier adds a Identifier to the ActivityDefinition.
func WithActivityDefinitionIdentifier(v Identifier) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithActivityDefinitionVersion sets the Version field.
func WithActivityDefinitionVersion(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Version = &v
	}
}

// WithActivityDefinitionName sets the Name field.
func WithActivityDefinitionName(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Name = &v
	}
}

// WithActivityDefinitionTitle sets the Title field.
func WithActivityDefinitionTitle(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Title = &v
	}
}

// WithActivityDefinitionSubtitle sets the Subtitle field.
func WithActivityDefinitionSubtitle(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Subtitle = &v
	}
}

// WithActivityDefinitionStatus sets the Status field.
func WithActivityDefinitionStatus(v PublicationStatus) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Status = &v
	}
}

// WithActivityDefinitionExperimental sets the Experimental field.
func WithActivityDefinitionExperimental(v bool) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Experimental = &v
	}
}

// WithActivityDefinitionSubjectCodeableConcept sets the SubjectCodeableConcept field.
func WithActivityDefinitionSubjectCodeableConcept(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.SubjectCodeableConcept = &v
	}
}

// WithActivityDefinitionSubjectReference sets the SubjectReference field.
func WithActivityDefinitionSubjectReference(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.SubjectReference = &v
	}
}

// WithActivityDefinitionSubjectCanonical sets the SubjectCanonical field.
func WithActivityDefinitionSubjectCanonical(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.SubjectCanonical = &v
	}
}

// WithActivityDefinitionSubjectCanonicalExt sets the SubjectCanonicalExt field.
func WithActivityDefinitionSubjectCanonicalExt(v Element) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.SubjectCanonicalExt = &v
	}
}

// WithActivityDefinitionDate sets the Date field.
func WithActivityDefinitionDate(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Date = &v
	}
}

// WithActivityDefinitionPublisher sets the Publisher field.
func WithActivityDefinitionPublisher(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Publisher = &v
	}
}

// WithActivityDefinitionContact adds a Contact to the ActivityDefinition.
func WithActivityDefinitionContact(v ContactDetail) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Contact = append(r.Contact, v)
	}
}

// WithActivityDefinitionDescription sets the Description field.
func WithActivityDefinitionDescription(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Description = &v
	}
}

// WithActivityDefinitionUseContext adds a UseContext to the ActivityDefinition.
func WithActivityDefinitionUseContext(v UsageContext) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.UseContext = append(r.UseContext, v)
	}
}

// WithActivityDefinitionJurisdiction adds a Jurisdiction to the ActivityDefinition.
func WithActivityDefinitionJurisdiction(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Jurisdiction = append(r.Jurisdiction, v)
	}
}

// WithActivityDefinitionPurpose sets the Purpose field.
func WithActivityDefinitionPurpose(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Purpose = &v
	}
}

// WithActivityDefinitionUsage sets the Usage field.
func WithActivityDefinitionUsage(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Usage = &v
	}
}

// WithActivityDefinitionCopyright sets the Copyright field.
func WithActivityDefinitionCopyright(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Copyright = &v
	}
}

// WithActivityDefinitionApprovalDate sets the ApprovalDate field.
func WithActivityDefinitionApprovalDate(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ApprovalDate = &v
	}
}

// WithActivityDefinitionLastReviewDate sets the LastReviewDate field.
func WithActivityDefinitionLastReviewDate(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.LastReviewDate = &v
	}
}

// WithActivityDefinitionEffectivePeriod sets the EffectivePeriod field.
func WithActivityDefinitionEffectivePeriod(v Period) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.EffectivePeriod = &v
	}
}

// WithActivityDefinitionTopic adds a Topic to the ActivityDefinition.
func WithActivityDefinitionTopic(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Topic = append(r.Topic, v)
	}
}

// WithActivityDefinitionAuthor adds a Author to the ActivityDefinition.
func WithActivityDefinitionAuthor(v ContactDetail) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Author = append(r.Author, v)
	}
}

// WithActivityDefinitionEditor adds a Editor to the ActivityDefinition.
func WithActivityDefinitionEditor(v ContactDetail) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Editor = append(r.Editor, v)
	}
}

// WithActivityDefinitionReviewer adds a Reviewer to the ActivityDefinition.
func WithActivityDefinitionReviewer(v ContactDetail) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Reviewer = append(r.Reviewer, v)
	}
}

// WithActivityDefinitionEndorser adds a Endorser to the ActivityDefinition.
func WithActivityDefinitionEndorser(v ContactDetail) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Endorser = append(r.Endorser, v)
	}
}

// WithActivityDefinitionRelatedArtifact adds a RelatedArtifact to the ActivityDefinition.
func WithActivityDefinitionRelatedArtifact(v RelatedArtifact) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.RelatedArtifact = append(r.RelatedArtifact, v)
	}
}

// WithActivityDefinitionLibrary adds a Library to the ActivityDefinition.
func WithActivityDefinitionLibrary(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Library = append(r.Library, v)
	}
}

// WithActivityDefinitionKind sets the Kind field.
func WithActivityDefinitionKind(v RequestResourceType) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Kind = &v
	}
}

// WithActivityDefinitionProfile sets the Profile field.
func WithActivityDefinitionProfile(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Profile = &v
	}
}

// WithActivityDefinitionCode sets the Code field.
func WithActivityDefinitionCode(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Code = &v
	}
}

// WithActivityDefinitionIntent sets the Intent field.
func WithActivityDefinitionIntent(v RequestIntent) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Intent = &v
	}
}

// WithActivityDefinitionPriority sets the Priority field.
func WithActivityDefinitionPriority(v RequestPriority) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Priority = &v
	}
}

// WithActivityDefinitionDoNotPerform sets the DoNotPerform field.
func WithActivityDefinitionDoNotPerform(v bool) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.DoNotPerform = &v
	}
}

// WithActivityDefinitionTimingTiming sets the TimingTiming field.
func WithActivityDefinitionTimingTiming(v Timing) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingTiming = &v
	}
}

// WithActivityDefinitionTimingDateTime sets the TimingDateTime field.
func WithActivityDefinitionTimingDateTime(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingDateTime = &v
	}
}

// WithActivityDefinitionTimingDateTimeExt sets the TimingDateTimeExt field.
func WithActivityDefinitionTimingDateTimeExt(v Element) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingDateTimeExt = &v
	}
}

// WithActivityDefinitionTimingAge sets the TimingAge field.
func WithActivityDefinitionTimingAge(v Age) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingAge = &v
	}
}

// WithActivityDefinitionTimingPeriod sets the TimingPeriod field.
func WithActivityDefinitionTimingPeriod(v Period) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingPeriod = &v
	}
}

// WithActivityDefinitionTimingRange sets the TimingRange field.
func WithActivityDefinitionTimingRange(v Range) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingRange = &v
	}
}

// WithActivityDefinitionTimingDuration sets the TimingDuration field.
func WithActivityDefinitionTimingDuration(v Duration) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.TimingDuration = &v
	}
}

// WithActivityDefinitionLocation sets the Location field.
func WithActivityDefinitionLocation(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Location = &v
	}
}

// WithActivityDefinitionParticipant adds a Participant to the ActivityDefinition.
func WithActivityDefinitionParticipant(v ActivityDefinitionParticipant) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Participant = append(r.Participant, v)
	}
}

// WithActivityDefinitionProductReference sets the ProductReference field.
func WithActivityDefinitionProductReference(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ProductReference = &v
	}
}

// WithActivityDefinitionProductCodeableConcept sets the ProductCodeableConcept field.
func WithActivityDefinitionProductCodeableConcept(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ProductCodeableConcept = &v
	}
}

// WithActivityDefinitionQuantity sets the Quantity field.
func WithActivityDefinitionQuantity(v Quantity) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Quantity = &v
	}
}

// WithActivityDefinitionDosage adds a Dosage to the ActivityDefinition.
func WithActivityDefinitionDosage(v Dosage) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Dosage = append(r.Dosage, v)
	}
}

// WithActivityDefinitionBodySite adds a BodySite to the ActivityDefinition.
func WithActivityDefinitionBodySite(v CodeableConcept) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.BodySite = append(r.BodySite, v)
	}
}

// WithActivityDefinitionSpecimenRequirement adds a SpecimenRequirement to the ActivityDefinition.
func WithActivityDefinitionSpecimenRequirement(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.SpecimenRequirement = append(r.SpecimenRequirement, v)
	}
}

// WithActivityDefinitionObservationRequirement adds a ObservationRequirement to the ActivityDefinition.
func WithActivityDefinitionObservationRequirement(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ObservationRequirement = append(r.ObservationRequirement, v)
	}
}

// WithActivityDefinitionObservationResultRequirement adds a ObservationResultRequirement to the ActivityDefinition.
func WithActivityDefinitionObservationResultRequirement(v Reference) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.ObservationResultRequirement = append(r.ObservationResultRequirement, v)
	}
}

// WithActivityDefinitionTransform sets the Transform field.
func WithActivityDefinitionTransform(v string) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.Transform = &v
	}
}

// WithActivityDefinitionDynamicValue adds a DynamicValue to the ActivityDefinition.
func WithActivityDefinitionDynamicValue(v ActivityDefinitionDynamicValue) ActivityDefinitionOption {
	return func(r *ActivityDefinition) {
		r.DynamicValue = append(r.DynamicValue, v)
	}
}
