// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// CompartmentDefinition - Functional Options
// =============================================================================

// CompartmentDefinitionOption is a functional option for configuring a CompartmentDefinition.
type CompartmentDefinitionOption func(*CompartmentDefinition)

// NewCompartmentDefinition creates a new CompartmentDefinition with the given options.
func NewCompartmentDefinition(opts ...CompartmentDefinitionOption) *CompartmentDefinition {
	r := &CompartmentDefinition{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithCompartmentDefinitionId sets the Id field.
func WithCompartmentDefinitionId(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Id = &v
	}
}

// WithCompartmentDefinitionMeta sets the Meta field.
func WithCompartmentDefinitionMeta(v Meta) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Meta = &v
	}
}

// WithCompartmentDefinitionImplicitRules sets the ImplicitRules field.
func WithCompartmentDefinitionImplicitRules(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.ImplicitRules = &v
	}
}

// WithCompartmentDefinitionLanguage sets the Language field.
func WithCompartmentDefinitionLanguage(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Language = &v
	}
}

// WithCompartmentDefinitionText sets the Text field.
func WithCompartmentDefinitionText(v Narrative) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Text = &v
	}
}

// WithCompartmentDefinitionContained adds a Contained to the CompartmentDefinition.
func WithCompartmentDefinitionContained(v Resource) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Contained = append(r.Contained, v)
	}
}

// WithCompartmentDefinitionExtension adds a Extension to the CompartmentDefinition.
func WithCompartmentDefinitionExtension(v Extension) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Extension = append(r.Extension, v)
	}
}

// WithCompartmentDefinitionModifierExtension adds a ModifierExtension to the CompartmentDefinition.
func WithCompartmentDefinitionModifierExtension(v Extension) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithCompartmentDefinitionUrl sets the Url field.
func WithCompartmentDefinitionUrl(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Url = &v
	}
}

// WithCompartmentDefinitionVersion sets the Version field.
func WithCompartmentDefinitionVersion(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Version = &v
	}
}

// WithCompartmentDefinitionName sets the Name field.
func WithCompartmentDefinitionName(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Name = &v
	}
}

// WithCompartmentDefinitionStatus sets the Status field.
func WithCompartmentDefinitionStatus(v PublicationStatus) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Status = &v
	}
}

// WithCompartmentDefinitionExperimental sets the Experimental field.
func WithCompartmentDefinitionExperimental(v bool) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Experimental = &v
	}
}

// WithCompartmentDefinitionDate sets the Date field.
func WithCompartmentDefinitionDate(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Date = &v
	}
}

// WithCompartmentDefinitionPublisher sets the Publisher field.
func WithCompartmentDefinitionPublisher(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Publisher = &v
	}
}

// WithCompartmentDefinitionContact adds a Contact to the CompartmentDefinition.
func WithCompartmentDefinitionContact(v ContactDetail) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Contact = append(r.Contact, v)
	}
}

// WithCompartmentDefinitionDescription sets the Description field.
func WithCompartmentDefinitionDescription(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Description = &v
	}
}

// WithCompartmentDefinitionUseContext adds a UseContext to the CompartmentDefinition.
func WithCompartmentDefinitionUseContext(v UsageContext) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.UseContext = append(r.UseContext, v)
	}
}

// WithCompartmentDefinitionPurpose sets the Purpose field.
func WithCompartmentDefinitionPurpose(v string) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Purpose = &v
	}
}

// WithCompartmentDefinitionCode sets the Code field.
func WithCompartmentDefinitionCode(v CompartmentType) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Code = &v
	}
}

// WithCompartmentDefinitionSearch sets the Search field.
func WithCompartmentDefinitionSearch(v bool) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Search = &v
	}
}

// WithCompartmentDefinitionResource adds a Resource to the CompartmentDefinition.
func WithCompartmentDefinitionResource(v CompartmentDefinitionResource) CompartmentDefinitionOption {
	return func(r *CompartmentDefinition) {
		r.Resource = append(r.Resource, v)
	}
}
