// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// SubstanceDefinition - Functional Options
// =============================================================================

// SubstanceDefinitionOption is a functional option for configuring a SubstanceDefinition.
type SubstanceDefinitionOption func(*SubstanceDefinition)

// NewSubstanceDefinition creates a new SubstanceDefinition with the given options.
func NewSubstanceDefinition(opts ...SubstanceDefinitionOption) *SubstanceDefinition {
	r := &SubstanceDefinition{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithSubstanceDefinitionId sets the Id field.
func WithSubstanceDefinitionId(v string) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Id = &v
	}
}

// WithSubstanceDefinitionMeta sets the Meta field.
func WithSubstanceDefinitionMeta(v Meta) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Meta = &v
	}
}

// WithSubstanceDefinitionImplicitRules sets the ImplicitRules field.
func WithSubstanceDefinitionImplicitRules(v string) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.ImplicitRules = &v
	}
}

// WithSubstanceDefinitionLanguage sets the Language field.
func WithSubstanceDefinitionLanguage(v string) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Language = &v
	}
}

// WithSubstanceDefinitionText sets the Text field.
func WithSubstanceDefinitionText(v Narrative) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Text = &v
	}
}

// WithSubstanceDefinitionContained adds a Contained to the SubstanceDefinition.
func WithSubstanceDefinitionContained(v Resource) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Contained = append(r.Contained, v)
	}
}

// WithSubstanceDefinitionExtension adds a Extension to the SubstanceDefinition.
func WithSubstanceDefinitionExtension(v Extension) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Extension = append(r.Extension, v)
	}
}

// WithSubstanceDefinitionModifierExtension adds a ModifierExtension to the SubstanceDefinition.
func WithSubstanceDefinitionModifierExtension(v Extension) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithSubstanceDefinitionIdentifier adds a Identifier to the SubstanceDefinition.
func WithSubstanceDefinitionIdentifier(v Identifier) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithSubstanceDefinitionVersion sets the Version field.
func WithSubstanceDefinitionVersion(v string) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Version = &v
	}
}

// WithSubstanceDefinitionStatus sets the Status field.
func WithSubstanceDefinitionStatus(v CodeableConcept) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Status = &v
	}
}

// WithSubstanceDefinitionClassification adds a Classification to the SubstanceDefinition.
func WithSubstanceDefinitionClassification(v CodeableConcept) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Classification = append(r.Classification, v)
	}
}

// WithSubstanceDefinitionDomain sets the Domain field.
func WithSubstanceDefinitionDomain(v CodeableConcept) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Domain = &v
	}
}

// WithSubstanceDefinitionGrade adds a Grade to the SubstanceDefinition.
func WithSubstanceDefinitionGrade(v CodeableConcept) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Grade = append(r.Grade, v)
	}
}

// WithSubstanceDefinitionDescription sets the Description field.
func WithSubstanceDefinitionDescription(v string) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Description = &v
	}
}

// WithSubstanceDefinitionInformationSource adds a InformationSource to the SubstanceDefinition.
func WithSubstanceDefinitionInformationSource(v Reference) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.InformationSource = append(r.InformationSource, v)
	}
}

// WithSubstanceDefinitionNote adds a Note to the SubstanceDefinition.
func WithSubstanceDefinitionNote(v Annotation) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Note = append(r.Note, v)
	}
}

// WithSubstanceDefinitionManufacturer adds a Manufacturer to the SubstanceDefinition.
func WithSubstanceDefinitionManufacturer(v Reference) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Manufacturer = append(r.Manufacturer, v)
	}
}

// WithSubstanceDefinitionSupplier adds a Supplier to the SubstanceDefinition.
func WithSubstanceDefinitionSupplier(v Reference) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Supplier = append(r.Supplier, v)
	}
}

// WithSubstanceDefinitionMoiety adds a Moiety to the SubstanceDefinition.
func WithSubstanceDefinitionMoiety(v SubstanceDefinitionMoiety) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Moiety = append(r.Moiety, v)
	}
}

// WithSubstanceDefinitionProperty adds a Property to the SubstanceDefinition.
func WithSubstanceDefinitionProperty(v SubstanceDefinitionProperty) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Property = append(r.Property, v)
	}
}

// WithSubstanceDefinitionMolecularWeight adds a MolecularWeight to the SubstanceDefinition.
func WithSubstanceDefinitionMolecularWeight(v SubstanceDefinitionMolecularWeight) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.MolecularWeight = append(r.MolecularWeight, v)
	}
}

// WithSubstanceDefinitionStructure sets the Structure field.
func WithSubstanceDefinitionStructure(v SubstanceDefinitionStructure) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Structure = &v
	}
}

// WithSubstanceDefinitionCode adds a Code to the SubstanceDefinition.
func WithSubstanceDefinitionCode(v SubstanceDefinitionCode) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Code = append(r.Code, v)
	}
}

// WithSubstanceDefinitionName adds a Name to the SubstanceDefinition.
func WithSubstanceDefinitionName(v SubstanceDefinitionName) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Name = append(r.Name, v)
	}
}

// WithSubstanceDefinitionRelationship adds a Relationship to the SubstanceDefinition.
func WithSubstanceDefinitionRelationship(v SubstanceDefinitionRelationship) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.Relationship = append(r.Relationship, v)
	}
}

// WithSubstanceDefinitionSourceMaterial sets the SourceMaterial field.
func WithSubstanceDefinitionSourceMaterial(v SubstanceDefinitionSourceMaterial) SubstanceDefinitionOption {
	return func(r *SubstanceDefinition) {
		r.SourceMaterial = &v
	}
}
