// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// Specimen - Functional Options
// =============================================================================

// SpecimenOption is a functional option for configuring a Specimen.
type SpecimenOption func(*Specimen)

// NewSpecimen creates a new Specimen with the given options.
func NewSpecimen(opts ...SpecimenOption) *Specimen {
	r := &Specimen{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithSpecimenId sets the Id field.
func WithSpecimenId(v string) SpecimenOption {
	return func(r *Specimen) {
		r.Id = &v
	}
}

// WithSpecimenMeta sets the Meta field.
func WithSpecimenMeta(v Meta) SpecimenOption {
	return func(r *Specimen) {
		r.Meta = &v
	}
}

// WithSpecimenImplicitRules sets the ImplicitRules field.
func WithSpecimenImplicitRules(v string) SpecimenOption {
	return func(r *Specimen) {
		r.ImplicitRules = &v
	}
}

// WithSpecimenLanguage sets the Language field.
func WithSpecimenLanguage(v string) SpecimenOption {
	return func(r *Specimen) {
		r.Language = &v
	}
}

// WithSpecimenText sets the Text field.
func WithSpecimenText(v Narrative) SpecimenOption {
	return func(r *Specimen) {
		r.Text = &v
	}
}

// WithSpecimenContained adds a Contained to the Specimen.
func WithSpecimenContained(v Resource) SpecimenOption {
	return func(r *Specimen) {
		r.Contained = append(r.Contained, v)
	}
}

// WithSpecimenExtension adds a Extension to the Specimen.
func WithSpecimenExtension(v Extension) SpecimenOption {
	return func(r *Specimen) {
		r.Extension = append(r.Extension, v)
	}
}

// WithSpecimenModifierExtension adds a ModifierExtension to the Specimen.
func WithSpecimenModifierExtension(v Extension) SpecimenOption {
	return func(r *Specimen) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithSpecimenIdentifier adds a Identifier to the Specimen.
func WithSpecimenIdentifier(v Identifier) SpecimenOption {
	return func(r *Specimen) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithSpecimenAccessionIdentifier sets the AccessionIdentifier field.
func WithSpecimenAccessionIdentifier(v Identifier) SpecimenOption {
	return func(r *Specimen) {
		r.AccessionIdentifier = &v
	}
}

// WithSpecimenStatus sets the Status field.
func WithSpecimenStatus(v SpecimenStatus) SpecimenOption {
	return func(r *Specimen) {
		r.Status = &v
	}
}

// WithSpecimenType sets the Type field.
func WithSpecimenType(v CodeableConcept) SpecimenOption {
	return func(r *Specimen) {
		r.Type = &v
	}
}

// WithSpecimenSubject sets the Subject field.
func WithSpecimenSubject(v Reference) SpecimenOption {
	return func(r *Specimen) {
		r.Subject = &v
	}
}

// WithSpecimenReceivedTime sets the ReceivedTime field.
func WithSpecimenReceivedTime(v string) SpecimenOption {
	return func(r *Specimen) {
		r.ReceivedTime = &v
	}
}

// WithSpecimenParent adds a Parent to the Specimen.
func WithSpecimenParent(v Reference) SpecimenOption {
	return func(r *Specimen) {
		r.Parent = append(r.Parent, v)
	}
}

// WithSpecimenRequest adds a Request to the Specimen.
func WithSpecimenRequest(v Reference) SpecimenOption {
	return func(r *Specimen) {
		r.Request = append(r.Request, v)
	}
}

// WithSpecimenCollection sets the Collection field.
func WithSpecimenCollection(v SpecimenCollection) SpecimenOption {
	return func(r *Specimen) {
		r.Collection = &v
	}
}

// WithSpecimenProcessing adds a Processing to the Specimen.
func WithSpecimenProcessing(v SpecimenProcessing) SpecimenOption {
	return func(r *Specimen) {
		r.Processing = append(r.Processing, v)
	}
}

// WithSpecimenContainer adds a Container to the Specimen.
func WithSpecimenContainer(v SpecimenContainer) SpecimenOption {
	return func(r *Specimen) {
		r.Container = append(r.Container, v)
	}
}

// WithSpecimenCondition adds a Condition to the Specimen.
func WithSpecimenCondition(v CodeableConcept) SpecimenOption {
	return func(r *Specimen) {
		r.Condition = append(r.Condition, v)
	}
}

// WithSpecimenNote adds a Note to the Specimen.
func WithSpecimenNote(v Annotation) SpecimenOption {
	return func(r *Specimen) {
		r.Note = append(r.Note, v)
	}
}
