// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (functional options)
// Package: r4b

package r4b

// =============================================================================
// Device - Functional Options
// =============================================================================

// DeviceOption is a functional option for configuring a Device.
type DeviceOption func(*Device)

// NewDevice creates a new Device with the given options.
func NewDevice(opts ...DeviceOption) *Device {
	r := &Device{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithDeviceId sets the Id field.
func WithDeviceId(v string) DeviceOption {
	return func(r *Device) {
		r.Id = &v
	}
}

// WithDeviceMeta sets the Meta field.
func WithDeviceMeta(v Meta) DeviceOption {
	return func(r *Device) {
		r.Meta = &v
	}
}

// WithDeviceImplicitRules sets the ImplicitRules field.
func WithDeviceImplicitRules(v string) DeviceOption {
	return func(r *Device) {
		r.ImplicitRules = &v
	}
}

// WithDeviceLanguage sets the Language field.
func WithDeviceLanguage(v string) DeviceOption {
	return func(r *Device) {
		r.Language = &v
	}
}

// WithDeviceText sets the Text field.
func WithDeviceText(v Narrative) DeviceOption {
	return func(r *Device) {
		r.Text = &v
	}
}

// WithDeviceContained adds a Contained to the Device.
func WithDeviceContained(v Resource) DeviceOption {
	return func(r *Device) {
		r.Contained = append(r.Contained, v)
	}
}

// WithDeviceExtension adds a Extension to the Device.
func WithDeviceExtension(v Extension) DeviceOption {
	return func(r *Device) {
		r.Extension = append(r.Extension, v)
	}
}

// WithDeviceModifierExtension adds a ModifierExtension to the Device.
func WithDeviceModifierExtension(v Extension) DeviceOption {
	return func(r *Device) {
		r.ModifierExtension = append(r.ModifierExtension, v)
	}
}

// WithDeviceIdentifier adds a Identifier to the Device.
func WithDeviceIdentifier(v Identifier) DeviceOption {
	return func(r *Device) {
		r.Identifier = append(r.Identifier, v)
	}
}

// WithDeviceDefinition sets the Definition field.
func WithDeviceDefinition(v Reference) DeviceOption {
	return func(r *Device) {
		r.Definition = &v
	}
}

// WithDeviceUdiCarrier adds a UdiCarrier to the Device.
func WithDeviceUdiCarrier(v DeviceUdiCarrier) DeviceOption {
	return func(r *Device) {
		r.UdiCarrier = append(r.UdiCarrier, v)
	}
}

// WithDeviceStatus sets the Status field.
func WithDeviceStatus(v FHIRDeviceStatus) DeviceOption {
	return func(r *Device) {
		r.Status = &v
	}
}

// WithDeviceStatusReason adds a StatusReason to the Device.
func WithDeviceStatusReason(v CodeableConcept) DeviceOption {
	return func(r *Device) {
		r.StatusReason = append(r.StatusReason, v)
	}
}

// WithDeviceDistinctIdentifier sets the DistinctIdentifier field.
func WithDeviceDistinctIdentifier(v string) DeviceOption {
	return func(r *Device) {
		r.DistinctIdentifier = &v
	}
}

// WithDeviceManufacturer sets the Manufacturer field.
func WithDeviceManufacturer(v string) DeviceOption {
	return func(r *Device) {
		r.Manufacturer = &v
	}
}

// WithDeviceManufactureDate sets the ManufactureDate field.
func WithDeviceManufactureDate(v string) DeviceOption {
	return func(r *Device) {
		r.ManufactureDate = &v
	}
}

// WithDeviceExpirationDate sets the ExpirationDate field.
func WithDeviceExpirationDate(v string) DeviceOption {
	return func(r *Device) {
		r.ExpirationDate = &v
	}
}

// WithDeviceLotNumber sets the LotNumber field.
func WithDeviceLotNumber(v string) DeviceOption {
	return func(r *Device) {
		r.LotNumber = &v
	}
}

// WithDeviceSerialNumber sets the SerialNumber field.
func WithDeviceSerialNumber(v string) DeviceOption {
	return func(r *Device) {
		r.SerialNumber = &v
	}
}

// WithDeviceDeviceName adds a DeviceName to the Device.
func WithDeviceDeviceName(v DeviceDeviceName) DeviceOption {
	return func(r *Device) {
		r.DeviceName = append(r.DeviceName, v)
	}
}

// WithDeviceModelNumber sets the ModelNumber field.
func WithDeviceModelNumber(v string) DeviceOption {
	return func(r *Device) {
		r.ModelNumber = &v
	}
}

// WithDevicePartNumber sets the PartNumber field.
func WithDevicePartNumber(v string) DeviceOption {
	return func(r *Device) {
		r.PartNumber = &v
	}
}

// WithDeviceType sets the Type field.
func WithDeviceType(v CodeableConcept) DeviceOption {
	return func(r *Device) {
		r.Type = &v
	}
}

// WithDeviceSpecialization adds a Specialization to the Device.
func WithDeviceSpecialization(v DeviceSpecialization) DeviceOption {
	return func(r *Device) {
		r.Specialization = append(r.Specialization, v)
	}
}

// WithDeviceVersion adds a Version to the Device.
func WithDeviceVersion(v DeviceVersion) DeviceOption {
	return func(r *Device) {
		r.Version = append(r.Version, v)
	}
}

// WithDeviceProperty adds a Property to the Device.
func WithDeviceProperty(v DeviceProperty) DeviceOption {
	return func(r *Device) {
		r.Property = append(r.Property, v)
	}
}

// WithDevicePatient sets the Patient field.
func WithDevicePatient(v Reference) DeviceOption {
	return func(r *Device) {
		r.Patient = &v
	}
}

// WithDeviceOwner sets the Owner field.
func WithDeviceOwner(v Reference) DeviceOption {
	return func(r *Device) {
		r.Owner = &v
	}
}

// WithDeviceContact adds a Contact to the Device.
func WithDeviceContact(v ContactPoint) DeviceOption {
	return func(r *Device) {
		r.Contact = append(r.Contact, v)
	}
}

// WithDeviceLocation sets the Location field.
func WithDeviceLocation(v Reference) DeviceOption {
	return func(r *Device) {
		r.Location = &v
	}
}

// WithDeviceUrl sets the Url field.
func WithDeviceUrl(v string) DeviceOption {
	return func(r *Device) {
		r.Url = &v
	}
}

// WithDeviceNote adds a Note to the Device.
func WithDeviceNote(v Annotation) DeviceOption {
	return func(r *Device) {
		r.Note = append(r.Note, v)
	}
}

// WithDeviceSafety adds a Safety to the Device.
func WithDeviceSafety(v CodeableConcept) DeviceOption {
	return func(r *Device) {
		r.Safety = append(r.Safety, v)
	}
}

// WithDeviceParent sets the Parent field.
func WithDeviceParent(v Reference) DeviceOption {
	return func(r *Device) {
		r.Parent = &v
	}
}
