// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4b

package r4b

import (
	"encoding/json"
	"fmt"
)

// SearchParameter represents FHIR SearchParameter.
type SearchParameter struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Canonical identifier for this search parameter, represented as a URI (globally unique)
	Url *string `json:"url,omitempty"`
	// Extension for Url
	UrlExt *Element `json:"_url,omitempty"`
	// Business version of the search parameter
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// Name for this search parameter (computer friendly)
	Name *string `json:"name,omitempty"`
	// Extension for Name
	NameExt *Element `json:"_name,omitempty"`
	// Original definition for the search parameter
	DerivedFrom *string `json:"derivedFrom,omitempty"`
	// Extension for DerivedFrom
	DerivedFromExt *Element `json:"_derivedFrom,omitempty"`
	// draft | active | retired | unknown
	Status *PublicationStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty"`
	// Extension for Experimental
	ExperimentalExt *Element `json:"_experimental,omitempty"`
	// Date last changed
	Date *string `json:"date,omitempty"`
	// Extension for Date
	DateExt *Element `json:"_date,omitempty"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty"`
	// Extension for Publisher
	PublisherExt *Element `json:"_publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty"`
	// Natural language description of the search parameter
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty"`
	// Intended jurisdiction for search parameter (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty"`
	// Why this search parameter is defined
	Purpose *string `json:"purpose,omitempty"`
	// Extension for Purpose
	PurposeExt *Element `json:"_purpose,omitempty"`
	// Code used in URL
	Code *string `json:"code,omitempty"`
	// Extension for Code
	CodeExt *Element `json:"_code,omitempty"`
	// The resource type(s) this search parameter applies to
	Base []string `json:"base,omitempty"`
	// Extension for Base
	BaseExt []Element `json:"_base,omitempty"`
	// number | date | string | token | reference | composite | quantity | uri | special
	Type *SearchParamType `json:"type,omitempty"`
	// Extension for Type
	TypeExt *Element `json:"_type,omitempty"`
	// FHIRPath expression that extracts the values
	Expression *string `json:"expression,omitempty"`
	// Extension for Expression
	ExpressionExt *Element `json:"_expression,omitempty"`
	// XPath that extracts the values
	Xpath *string `json:"xpath,omitempty"`
	// Extension for Xpath
	XpathExt *Element `json:"_xpath,omitempty"`
	// normal | phonetic | nearby | distance | other
	XpathUsage *XPathUsageType `json:"xpathUsage,omitempty"`
	// Extension for XpathUsage
	XpathUsageExt *Element `json:"_xpathUsage,omitempty"`
	// Types of resource (if a resource reference)
	Target []string `json:"target,omitempty"`
	// Extension for Target
	TargetExt []Element `json:"_target,omitempty"`
	// Allow multiple values per parameter (or)
	MultipleOr *bool `json:"multipleOr,omitempty"`
	// Extension for MultipleOr
	MultipleOrExt *Element `json:"_multipleOr,omitempty"`
	// Allow multiple parameters (and)
	MultipleAnd *bool `json:"multipleAnd,omitempty"`
	// Extension for MultipleAnd
	MultipleAndExt *Element `json:"_multipleAnd,omitempty"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator []SearchComparator `json:"comparator,omitempty"`
	// Extension for Comparator
	ComparatorExt []Element `json:"_comparator,omitempty"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | ofType
	Modifier []SearchModifierCode `json:"modifier,omitempty"`
	// Extension for Modifier
	ModifierExt []Element `json:"_modifier,omitempty"`
	// Chained names supported
	Chain []string `json:"chain,omitempty"`
	// Extension for Chain
	ChainExt []Element `json:"_chain,omitempty"`
	// For Composite resources to define the parts
	Component []SearchParameterComponent `json:"component,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *SearchParameter) GetResourceType() string {
	return "SearchParameter"
}

// GetId returns the resource's logical ID.
func (r *SearchParameter) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *SearchParameter) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *SearchParameter) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *SearchParameter) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *SearchParameter) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *SearchParameter) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *SearchParameter) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *SearchParameter) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *SearchParameter) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r SearchParameter) MarshalJSON() ([]byte, error) {
	r.ResourceType = "SearchParameter"
	type Alias SearchParameter
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *SearchParameter) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias SearchParameter
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
