// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4b

package r4b

import (
	"encoding/json"
	"fmt"
)

// Encounter represents FHIR Encounter.
type Encounter struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Identifier(s) by which this encounter is known
	Identifier []Identifier `json:"identifier,omitempty"`
	// planned | arrived | triaged | in-progress | onleave | finished | cancelled +
	Status *EncounterStatus `json:"status,omitempty"`
	// Extension for Status
	StatusExt *Element `json:"_status,omitempty"`
	// List of past encounter statuses
	StatusHistory []EncounterStatusHistory `json:"statusHistory,omitempty"`
	// Classification of patient encounter
	Class Coding `json:"class"`
	// List of past encounter classes
	ClassHistory []EncounterClassHistory `json:"classHistory,omitempty"`
	// Specific type of encounter
	Type []CodeableConcept `json:"type,omitempty"`
	// Specific type of service
	ServiceType *CodeableConcept `json:"serviceType,omitempty"`
	// Indicates the urgency of the encounter
	Priority *CodeableConcept `json:"priority,omitempty"`
	// The patient or group present at the encounter
	Subject *Reference `json:"subject,omitempty"`
	// Episode(s) of care that this encounter should be recorded against
	EpisodeOfCare []Reference `json:"episodeOfCare,omitempty"`
	// The ServiceRequest that initiated this encounter
	BasedOn []Reference `json:"basedOn,omitempty"`
	// List of participants involved in the encounter
	Participant []EncounterParticipant `json:"participant,omitempty"`
	// The appointment that scheduled this encounter
	Appointment []Reference `json:"appointment,omitempty"`
	// The start and end time of the encounter
	Period *Period `json:"period,omitempty"`
	// Quantity of time the encounter lasted (less time absent)
	Length *Duration `json:"length,omitempty"`
	// Coded reason the encounter takes place
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty"`
	// Reason the encounter takes place (reference)
	ReasonReference []Reference `json:"reasonReference,omitempty"`
	// The list of diagnosis relevant to this encounter
	Diagnosis []EncounterDiagnosis `json:"diagnosis,omitempty"`
	// The set of accounts that may be used for billing for this Encounter
	Account []Reference `json:"account,omitempty"`
	// Details about the admission to a healthcare service
	Hospitalization *EncounterHospitalization `json:"hospitalization,omitempty"`
	// List of locations where the patient has been
	Location []EncounterLocation `json:"location,omitempty"`
	// The organization (facility) responsible for this encounter
	ServiceProvider *Reference `json:"serviceProvider,omitempty"`
	// Another Encounter this encounter is part of
	PartOf *Reference `json:"partOf,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *Encounter) GetResourceType() string {
	return "Encounter"
}

// GetId returns the resource's logical ID.
func (r *Encounter) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *Encounter) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *Encounter) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *Encounter) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *Encounter) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *Encounter) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *Encounter) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *Encounter) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *Encounter) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r Encounter) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Encounter"
	type Alias Encounter
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *Encounter) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias Encounter
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
