// Code generated by gofhir. DO NOT EDIT.
// Source: FHIR StructureDefinitions (resources)
// Package: r4b

package r4b

import (
	"encoding/json"
	"fmt"
)

// MedicinalProductDefinition represents FHIR MedicinalProductDefinition.
type MedicinalProductDefinition struct {
	// FHIR resource type
	ResourceType string `json:"resourceType"`
	// Logical id of this artifact
	Id *string `json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *string `json:"implicitRules,omitempty"`
	// Extension for ImplicitRules
	ImplicitRulesExt *Element `json:"_implicitRules,omitempty"`
	// Language of the resource content
	Language *string `json:"language,omitempty"`
	// Extension for Language
	LanguageExt *Element `json:"_language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	// Business identifier for this product. Could be an MPID
	Identifier []Identifier `json:"identifier,omitempty"`
	// Regulatory type, e.g. Investigational or Authorized
	Type *CodeableConcept `json:"type,omitempty"`
	// If this medicine applies to human or veterinary uses
	Domain *CodeableConcept `json:"domain,omitempty"`
	// A business identifier relating to a specific version of the product
	Version *string `json:"version,omitempty"`
	// Extension for Version
	VersionExt *Element `json:"_version,omitempty"`
	// The status within the lifecycle of this product record
	Status *CodeableConcept `json:"status,omitempty"`
	// The date at which the given status became applicable
	StatusDate *string `json:"statusDate,omitempty"`
	// Extension for StatusDate
	StatusDateExt *Element `json:"_statusDate,omitempty"`
	// General description of this product
	Description *string `json:"description,omitempty"`
	// Extension for Description
	DescriptionExt *Element `json:"_description,omitempty"`
	// The dose form for a single part product, or combined form of a multiple part product
	CombinedPharmaceuticalDoseForm *CodeableConcept `json:"combinedPharmaceuticalDoseForm,omitempty"`
	// The path by which the product is taken into or makes contact with the body
	Route []CodeableConcept `json:"route,omitempty"`
	// Description of indication(s) for this product, used when structured indications are not required
	Indication *string `json:"indication,omitempty"`
	// Extension for Indication
	IndicationExt *Element `json:"_indication,omitempty"`
	// The legal status of supply of the medicinal product as classified by the regulator
	LegalStatusOfSupply *CodeableConcept `json:"legalStatusOfSupply,omitempty"`
	// Whether the Medicinal Product is subject to additional monitoring for regulatory reasons
	AdditionalMonitoringIndicator *CodeableConcept `json:"additionalMonitoringIndicator,omitempty"`
	// Whether the Medicinal Product is subject to special measures for regulatory reasons
	SpecialMeasures []CodeableConcept `json:"specialMeasures,omitempty"`
	// If authorised for use in children
	PediatricUseIndicator *CodeableConcept `json:"pediatricUseIndicator,omitempty"`
	// Allows the product to be classified by various systems
	Classification []CodeableConcept `json:"classification,omitempty"`
	// Marketing status of the medicinal product, in contrast to marketing authorization
	MarketingStatus []MarketingStatus `json:"marketingStatus,omitempty"`
	// Package type for the product
	PackagedMedicinalProduct []CodeableConcept `json:"packagedMedicinalProduct,omitempty"`
	// The ingredients of this medicinal product - when not detailed in other resources
	Ingredient []CodeableConcept `json:"ingredient,omitempty"`
	// Any component of the drug product which is not the chemical entity defined as the drug substance, or an excipient in the drug product
	Impurity []CodeableReference `json:"impurity,omitempty"`
	// Additional documentation about the medicinal product
	AttachedDocument []Reference `json:"attachedDocument,omitempty"`
	// A master file for the medicinal product (e.g. Pharmacovigilance System Master File)
	MasterFile []Reference `json:"masterFile,omitempty"`
	// A product specific contact, person (in a role), or an organization
	Contact []MedicinalProductDefinitionContact `json:"contact,omitempty"`
	// Clinical trials or studies that this product is involved in
	ClinicalTrial []Reference `json:"clinicalTrial,omitempty"`
	// A code that this product is known by, within some formal terminology
	Code []Coding `json:"code,omitempty"`
	// The product's name, including full name and possibly coded parts
	Name []MedicinalProductDefinitionName `json:"name,omitempty"`
	// Reference to another product, e.g. for linking authorised to investigational product
	CrossReference []MedicinalProductDefinitionCrossReference `json:"crossReference,omitempty"`
	// A manufacturing or administrative process for the medicinal product
	Operation []MedicinalProductDefinitionOperation `json:"operation,omitempty"`
	// Key product features such as "sugar free", "modified release"
	Characteristic []MedicinalProductDefinitionCharacteristic `json:"characteristic,omitempty"`
}

// GetResourceType returns the FHIR resource type.
func (r *MedicinalProductDefinition) GetResourceType() string {
	return "MedicinalProductDefinition"
}

// GetId returns the resource's logical ID.
func (r *MedicinalProductDefinition) GetId() *string {
	return r.Id
}

// SetId sets the resource's logical ID.
func (r *MedicinalProductDefinition) SetId(id string) {
	r.Id = &id
}

// GetMeta returns the resource's Meta element.
func (r *MedicinalProductDefinition) GetMeta() *Meta {
	return r.Meta
}

// SetMeta sets the resource's Meta element.
func (r *MedicinalProductDefinition) SetMeta(m *Meta) {
	r.Meta = m
}

// GetText returns the resource's narrative text.
func (r *MedicinalProductDefinition) GetText() *Narrative {
	return r.Text
}

// SetText sets the resource's narrative text.
func (r *MedicinalProductDefinition) SetText(t *Narrative) {
	r.Text = t
}

// GetContained returns the resource's contained resources.
func (r *MedicinalProductDefinition) GetContained() []Resource {
	return r.Contained
}

// GetExtension returns the resource's extensions.
func (r *MedicinalProductDefinition) GetExtension() []Extension {
	return r.Extension
}

// GetModifierExtension returns the resource's modifier extensions.
func (r *MedicinalProductDefinition) GetModifierExtension() []Extension {
	return r.ModifierExtension
}

// MarshalJSON ensures resourceType is always included in JSON output.
func (r MedicinalProductDefinition) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicinalProductDefinition"
	type Alias MedicinalProductDefinition
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON handles deserialization of polymorphic contained resources.
func (r *MedicinalProductDefinition) UnmarshalJSON(data []byte) error {
	// Use an alias to avoid infinite recursion
	type Alias MedicinalProductDefinition
	aux := &struct {
		Contained []json.RawMessage `json:"contained,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(r),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// Unmarshal each contained resource using the dispatcher
	if len(aux.Contained) > 0 {
		r.Contained = make([]Resource, len(aux.Contained))
		for i, raw := range aux.Contained {
			resource, err := UnmarshalResource(raw)
			if err != nil {
				return fmt.Errorf("failed to unmarshal contained[%d]: %w", i, err)
			}
			r.Contained[i] = resource
		}
	}

	return nil
}
